using ModelGenApp.Views;

namespace ModelGenApp.ViewModels;
public class EnumListViewModel: DispatchedCollection<EnumInfoViewModel>
{
  public EnumListViewModel(EnumTypeInfoViewModel owner, string name)
  {
    Owner = owner;
    Name = name;
    ShowDetailsCommand = new RelayCommand(ShowDetailsExecute, ShowDetailsCanExecute) { Name = "ShowDetailsCommand" };
  }

  [DataGridColumn(IsAutoGenerated = false)]
  public EnumTypeInfoViewModel Owner { get; private set; }


  public string Name
  {
    get { return _Name; }
    set
    {
      if (_Name != value)
      {
        _Name = value;
        NotifyPropertyChanged(nameof(Name));
      }
    }
  }
  private string _Name = null!;


  [DataGridColumn(IsAutoGenerated = false)]
  public string Caption => Owner.Caption +"."+this.Name?.ToLower();

  #region ShowDetailsCommand
  public Command ShowDetailsCommand
  {
    get { return _ShowDetailsCommand; }
    set
    {
      if (_ShowDetailsCommand != value)
      {
        _ShowDetailsCommand = value;
        NotifyPropertyChanged(nameof(_ShowDetailsCommand));
      }
    }
  }
  private Command _ShowDetailsCommand = null!;

  protected virtual bool ShowDetailsCanExecute()
  {
    return Count>0;
  }

  Window? window;
  protected virtual void ShowDetailsExecute()
  {
    if (window != null && window.IsVisible)
    {
      window.Topmost=true;
      window.Focus();
    }
    else
    {
      window = new TypeListWindow();
      window.DataContext = this;
      window.Show();
    }
  }
  #endregion


}
