namespace ModelGenApp.ViewModels;
public class EnumListViewModel: ObservableCollection<EnumInfoViewModel>
{
  public EnumListViewModel(EnumTypeInfoViewModel owner, string name)
  {
    Owner = owner;
    Name = name;
    ShowDetailsCommand = new RelayCommand(ShowDetailsExecute, ShowDetailsCanExecute) { Name = "ShowDetailsCommand" };
  }

  [DataGridColumn(IsAutoGenerated = false)]
  public EnumTypeInfoViewModel Owner { get; private set; }

  public string Name { get; private set; }

  [DataGridColumn(IsAutoGenerated = false)]
  public string Caption => Owner.Caption +"."+this.Name?.ToLower();

  [DataGridColumn(IsAutoGenerated = false)]
  public string Label => this.Name+":";

  [DataGridColumn(IsAutoGenerated = false)]
  public bool Visible => true;

  #region ShowDetailsCommand
  public Command ShowDetailsCommand  { get; private set; }

  protected virtual bool ShowDetailsCanExecute()
  {
    return Count>0;
  }

  Window? window;
  protected virtual void ShowDetailsExecute()
  {
    if (window != null && window.IsVisible)
    {
      window.Topmost=true;
      window.Focus();
    }
    else
    {
      window = new TypeInfoWindow();
      window.DataContext = Owner;
      window.Show();
    }
  }
  #endregion


}
