namespace ModelGenApp.ViewModels;
public class NamespaceListViewModel: DispatchedCollection<NamespaceViewModel>
{
  public NamespaceListViewModel(PhaseViewModel phase, NTS nts, string? filter)
  {
    Phase = phase;
    var namespaces = TypeManager.GetNamespaces(nts).OrderBy(item=>item);
    foreach (var ns in namespaces)
    {
      var nsVM = new NamespaceViewModel(phase, ns );
      var nsTypes = TypeManager.GetNamespaceTypes(ns).OrderBy(item=>item.Name).ToList();
      if (filter!=null)
      {
        if (filter == SummaryInfoKind.AcceptedTypes.ToString())
          nsTypes = nsTypes.Where(item => item.IsAccepted).ToList();
        if (filter == SummaryInfoKind.RejectedTypes.ToString())
          nsTypes = nsTypes.Where(item => item.IsRejected).ToList();
      }
      var nsTypesVM = nsTypes.Select(item=>new TypeInfoViewModel(item, nts.HasFlag(NTS.Origin))).ToList();
      nsVM.AllTypes.AddRange(nsTypesVM);
      var nsClassesVM = nsTypesVM.Where(item=>item.TypeKind==TypeKind.Class).ToList();
      nsVM.Classes.AddRange(nsClassesVM);
      var nsEnumsVM = nsTypesVM.Where(item=>item.TypeKind==TypeKind.Enum).ToList();
      nsVM.Enums.AddRange(nsEnumsVM);
      var nsInterfacesVM = nsTypesVM.Where(item=>item.TypeKind==TypeKind.Interface).ToList();
      nsVM.Interfaces.AddRange(nsInterfacesVM);
      var nsStructsVM = nsTypesVM.Where(item=>item.TypeKind==TypeKind.Struct).ToList();
      nsVM.Structs.AddRange(nsStructsVM);
      var nsOthersVM = nsTypesVM.Where(item=>item.TypeKind==TypeKind.Type).ToList();
      nsVM.Others.AddRange(nsOthersVM);
      Add(nsVM);
    }
  }

  [DataGridColumn(IsAutoGenerated = false)]
  public PhaseViewModel Phase { get; private set; }

  [DataGridColumn(IsAutoGenerated = false)]
  public NTS Kind
  {
    get { return _Kind; }
    set
    {
      if (_Kind != value)
      {
        _Kind = value;
        NotifyPropertyChanged(nameof(Kind));
      }
    }
  }
  private NTS _Kind;

}
