namespace ModelGenApp.ViewModels;
public class NamespaceViewModel: ViewModel
{
  public NamespaceViewModel(PhaseViewModel phaseViewModel, string name)
  {
    Owner = phaseViewModel;
    Name = name;
    AllTypes = new TypeListViewModel(this, "All types");
    Classes = new ClassListViewModel(this, "Classes");
    Enums = new EnumTypeListViewModel(this, "Enums");
    Interfaces= new ClassListViewModel(this, "Interfaces");
    Structs = new ClassListViewModel(this, "Structs");
    Others= new TypeListViewModel(this, "Others");
  }

  [DataGridColumn(IsAutoGenerated = false)]
  public PhaseViewModel Owner { get; private set; }


  public string Name
  {
    get { return _Name; }
    set
    {
      if (_Name != value)
      {
        _Name = value;
        NotifyPropertyChanged(nameof(Name));
      }
    }
  }
  private string _Name = null!;

  [DataGridColumn(IsAutoGenerated = false)]
  public string Caption => Owner.PhaseName +" "+this.Name;

  public TypeListViewModel AllTypes { get; set; }


  public ClassListViewModel Classes { get; set; }

  public EnumTypeListViewModel Enums { get; set; }

  public ClassListViewModel Interfaces { get; set; }

  public ClassListViewModel Structs { get; set; }

  public TypeListViewModel Others { get; set; }

}
