namespace ModelGenApp.ViewModels;

/// <summary>
/// Observable monitor for a single process phase
/// </summary>
public abstract partial class PhaseViewModel : ViewModel
{

  public PhaseViewModel(PPS phase, string name)
  {
    Phase = phase;
    PhaseName = name;
    ShowResultsCommand = new RelayCommand(ShowResultsExecute, ShowResultsCanExecute) { Name = "ShowResultsCommand" };
    ShowOverviewCommand = new RelayCommand(ShowOverviewExecute, ShowOverviewCanExecute) { Name = "ShowOverviewCommand" };
    PropertyChanged += PhaseMonitor_PropertyChanged;
  }

  private void PhaseMonitor_PropertyChanged(object? sender, System.ComponentModel.PropertyChangedEventArgs e)
  {
    NotifyCanExecuteChanged();
  }
  public void NotifyCanExecuteChanged()
  {
    ShowResultsCommand.NotifyCanExecuteChanged();
    ShowOverviewCommand.NotifyCanExecuteChanged();
  }

  /// <summary>
  /// ID of the process phase.
  /// </summary>
  public PPS Phase { get; private set; }

  ///// <summary>
  ///// Number of the process phase.
  ///// </summary>
  //[DataGridColumn(IsAutoGenerated = false)]
  //public int PhaseNumber { get; private set; }

  /// <summary>
  /// Name of the process phase.
  /// </summary>
  public string? PhaseName {get; set; }

  /// <summary>
  /// Percent of the phase advantage.
  /// </summary>
  public int Percentage
  {
    get { return _Percentage; }
    set
    {
      if (_Percentage != value)
      {
        _Percentage = value;
        NotifyPropertyChanged(nameof(Percentage));
      }
    }
  }
  private int _Percentage;

  #region Summary
  public SummaryViewModel SummaryVM
  {
    get { return _SummaryVM; }
    set
    {
      if (_SummaryVM != value)
      {
        _SummaryVM = value;
        NotifyPropertyChanged(nameof(SummaryVM));
      }
    }
  }
  private SummaryViewModel _SummaryVM = null!;

  public void SetSummary(SummaryInfo summary)
  {
    SummaryVM = new SummaryViewModel();
    if (summary.Summary != null)
      foreach (var info in summary.Summary)
        SummaryVM.Add(new SummaryValueViewModel { Name = info.Key.ToString().DeCamelCase(), InfoKind = info.Key, Value = info.Value });
    SummaryVM.PropertyChanged += SummaryVM_PropertyChanged;
  }

  private void SummaryVM_PropertyChanged(object? sender, System.ComponentModel.PropertyChangedEventArgs e)
  {
    if (e.PropertyName == nameof(SummaryVM.Filter))
    {
      var summary = sender as SummaryViewModel;
      if (summary != null)
      {
        var filter = summary.Filter;
        SetFilter(filter);
      }
    }
  }
  #endregion

  #region Namespaces
  public NamespaceListViewModel NamespacesVM
  {
    get { return _Namespaces; }
    set
    {
      if (_Namespaces != value)
      {
        _Namespaces = value;
        NotifyPropertyChanged(nameof(NamespacesVM));
      }
    }
  }
  private NamespaceListViewModel _Namespaces = null!;

  public virtual void GetNamespaces()
  {
    NamespacesVM = new NamespaceListViewModel(this, NamespaceTypeSelector, Filter);
  }

  public NTS NamespaceTypeSelector { get; protected set; }

  #endregion

  #region ShowResultsCommand
  /// <summary>
  /// Command to show phase result window.
  /// </summary>
  public Command ShowResultsCommand
  {
    get { return _ShowResultsCommand; }
    set
    {
      if (_ShowResultsCommand != value)
      {
        _ShowResultsCommand = value;
        NotifyPropertyChanged(nameof(_ShowResultsCommand));
      }
    }
  }
  private Command _ShowResultsCommand = null!;

  protected abstract void ShowResultsExecute();

  protected virtual bool ShowResultsCanExecute()
  {
    return Percentage == 100;
  }
  #endregion

  #region ShowOverviewCommand
  public Command ShowOverviewCommand
  {
    get { return _ShowOverviewCommand; }
    set
    {
      if (_ShowOverviewCommand != value)
      {
        _ShowOverviewCommand = value;
        NotifyPropertyChanged(nameof(ShowOverviewCommand));
      }
    }
  }
  private Command _ShowOverviewCommand = null!;

  protected virtual bool ShowOverviewCanExecute()
  {
    return Percentage == 100;
  }

  protected abstract void ShowOverviewExecute();
  #endregion

  #region Filter namespaces

  public string? Filter
  {
    get { return _Filter; }
    set
    {
      if (_Filter != value)
      {
        _Filter = value;
        NotifyPropertyChanged(nameof(Filter));
      }
    }
  }
  private string? _Filter;

  public async void SetFilter(string? filter)
  {
    Filter = filter;
    await Task.Run(() =>
    {
      GetNamespaces();
    });
  }
  #endregion

  public bool IsTargetNameVisible { get; protected set; }

}
