namespace ModelGenApp.ViewModels;
public class PropInfoViewModel : ViewModel<PropInfo>
{
  public PropInfoViewModel(PropInfo propInfo, bool isOriginal) : base(propInfo)
  {
    IsOriginal = isOriginal;
  }

  [DataGridColumn(IsAutoGenerated = false)]
  public bool IsOriginal { get; set; }

  public string Name
  {
    get
    {
      if (IsOriginal)
        return Model.Name;
      return Model.GetTargetName();
    }
  }

  public string Type
  {
    get
    {
      var propType = Model.PropertyType;
      if (propType!=null)
        return propType.GetFullName(IsOriginal);
      return string.Empty;

    }
  }
}

