using ModelGenApp.Views;

namespace ModelGenApp.ViewModels;
public class PropListViewModel: ObservableCollection<PropInfoViewModel>
{
  public PropListViewModel(ClassInfoViewModel owner, string name)
  {
    Owner = owner;
    Name = name;
    ShowDetailsCommand = new RelayCommand(ShowDetailsExecute, ShowDetailsCanExecute) { Name = "ShowDetailsCommand" };
  }

  [DataGridColumn(IsAutoGenerated = false)]
  public ClassInfoViewModel Owner { get; private set; }


  public string Name { get; private set; }

  [DataGridColumn(IsAutoGenerated = false)]
  public string Caption => Owner.Caption +"."+this.Name?.ToLower();

  #region ShowDetailsCommand
  public Command ShowDetailsCommand { get; private set; }
  protected virtual bool ShowDetailsCanExecute()
  {
    return Count>0;
  }

  Window? window;
  protected virtual void ShowDetailsExecute()
  {
    if (window != null && window.IsVisible)
    {
      window.Topmost=true;
      window.Focus();
    }
    else
    {
      window = new TypeListWindow();
      window.DataContext = this;
      window.Show();
    }
  }
  #endregion


}
