namespace ModelGenApp.ViewModels;
public class PropInfoViewModel : ViewModel<PropInfo>
{
  public PropInfoViewModel(PropInfo propInfo, bool isOriginal) : base(propInfo)
  {
    IsOriginal = isOriginal;
  }

  [DataGridColumn(IsAutoGenerated = false)]
  public bool IsOriginal { get; set; }

  public string Name
  {
    get
    {
      if (IsOriginal)
        return Model.Name;
      return Model.GetTargetName();
    }
  }

}

