using Qhta.MVVM;

namespace ModelGenApp.ViewModels;
public class TypeInfoViewModel : ViewModel<TypeInfo>
{
  public TypeInfoViewModel(TypeInfo typeInfo, bool isOriginal) : base(typeInfo)
  {
    IsOriginal = isOriginal;
  }

  public TypeKind TypeKind => Model.TypeKind;

  [DataGridColumn(IsAutoGenerated = false)]
  public bool IsOriginal { get; set; }

  public string Name
  {
    get
    {
      var name = Model.GetFullName(IsOriginal);
      if (name != null)
      {
        var str = name.ToString();
        var k = str.IndexOf('.');
        var l = str.IndexOf('<');
        if (l == -1)
          l = str.Length;
        if (k != -1 && k < l)
          str = str.Substring(k + 1);
        return str;
      }
      return string.Empty;
    }
  }

  /// <summary>
  /// Shown as Window.Title.
  /// </summary>
  [DataGridColumn(IsAutoGenerated = false)]
  public string Caption => Name;
}

