<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;618</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;618</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Math\OfficeMathArgumentTypeConverter.cs" />
    <Compile Remove="Packaging\WordCommentsExtensiblePartConverter.cs" />
    <Compile Remove="Packaging\WordprocessingCommentsExPartConverter.cs" />
    <Compile Remove="Packaging\WordprocessingCommentsIdsPartConverter.cs" />
    <Compile Remove="Wordprocessing\CommonRunConverter.cs" />
    <Compile Remove="Wordprocessing\ContentBlockContentConverter.cs" />
    <Compile Remove="Wordprocessing\DataBinding3Converter.cs" />
    <Compile Remove="Wordprocessing\Document\ExternalFileConverter.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DocumentModel.BaseTypes\DocumentModel.BaseTypes.csproj" />
    <ProjectReference Include="..\DocumentModel.Interfaces\DocumentModel.Interfaces.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Drawings.Diagram2\" />
    <Folder Include="Wordprocessing\Frames and framesets\" />
    <Folder Include="Wordprocessing\VBA\" />
    <Folder Include="Wordprocessing\Ruby\" />
  </ItemGroup>

</Project>