global using System;
global using System.Collections.ObjectModel;
global using System.Collections.Specialized;
global using System.Xml;
global using System.Xml.Serialization;
global using DocumentFormat.OpenXml;
global using DocumentFormat.OpenXml.VariantTypes;
global using Qhta.Collections;
global using Qhta.TypeUtils;