namespace DocumentModel.Wordprocessing;
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

/// <summary>
///   Defines IStyles.
/// </summary>
public partial class IStyles: ModelElement
{
  /// <summary>
  /// Defines IStyles.
  /// </summary>
  public DefinedStyles DefinedStyles { get; set; } = new DefinedStyles();

  [XmlIgnore]
  public IDictionary<string, IStyle> StyleIndex => DefinedStyles.StyleIndex;
  [XmlIgnore]
  public IEnumerable<IStyle> AllStyles => DefinedStyles;
  [XmlIgnore]
  public IEnumerable<IStyle> ParagraphStyles => DefinedStyles.Where(item => item.Type==StyleKind.IParagraph);
  [XmlIgnore]
  public IEnumerable<IStyle> CharacterStyles => DefinedStyles.Where(item => item.Type==StyleKind.Character);
  [XmlIgnore]
  public IEnumerable<IStyle> TableStyles => DefinedStyles.Where(item => item.Type==StyleKind.ITable);
  [XmlIgnore]
  public IEnumerable<IStyle> NumberingStyles => DefinedStyles.Where(item => item.Type==StyleKind.Numbering);


  public static IList<(string name, StyleKind kind, string? alias)> BuiltInStyleStubs = new()
  {
    ( "Value", StyleKind.IParagraph, null ),
    ( "Heading 1", StyleKind.IParagraph, null ),
    ( "Heading 2", StyleKind.IParagraph, null ),
    ( "Heading 3", StyleKind.IParagraph, null ),
    ( "Heading 4", StyleKind.IParagraph, null ),
    ( "Heading 5", StyleKind.IParagraph, null ),
    ( "Heading 6", StyleKind.IParagraph, null ),
    ( "Heading 7", StyleKind.IParagraph, null ),
    ( "Heading 8", StyleKind.IParagraph, null ),
    ( "Heading 9", StyleKind.IParagraph, null ),
    ( "IIndex 1", StyleKind.IParagraph, null ),
    ( "IIndex 2", StyleKind.IParagraph, null ),
    ( "IIndex 3", StyleKind.IParagraph, null ),
    ( "IIndex 4", StyleKind.IParagraph, null ),
    ( "IIndex 5", StyleKind.IParagraph, null ),
    ( "IIndex 6", StyleKind.IParagraph, null ),
    ( "IIndex 7", StyleKind.IParagraph, null ),
    ( "IIndex 8", StyleKind.IParagraph, null ),
    ( "IIndex 9", StyleKind.IParagraph, null ),
    ( "TOC 1", StyleKind.IParagraph, null ),
    ( "TOC 2", StyleKind.IParagraph, null ),
    ( "TOC 3", StyleKind.IParagraph, null ),
    ( "TOC 4", StyleKind.IParagraph, null ),
    ( "TOC 5", StyleKind.IParagraph, null ),
    ( "TOC 6", StyleKind.IParagraph, null ),
    ( "TOC 7", StyleKind.IParagraph, null ),
    ( "TOC 8", StyleKind.IParagraph, null ),
    ( "TOC 9", StyleKind.IParagraph, null ),
    ( "Value Indent", StyleKind.IParagraph, null ),
    ( "IFootnote Text", StyleKind.IParagraph, null ),
    ( "IComment Text", StyleKind.IParagraph, null ),
    ( "Header", StyleKind.IParagraph, null ),
    ( "Footer", StyleKind.IParagraph, null ),
    ( "IIndex Heading", StyleKind.IParagraph, null ),
    ( "Caption", StyleKind.IParagraph, null ),
    ( "ITable of Figures", StyleKind.IParagraph, null ),
    ( "IEnvelope Address", StyleKind.IParagraph, null ),
    ( "IEnvelope Return", StyleKind.IParagraph, null ),
    ( "IFootnote Reference", StyleKind.Character, null ),
    ( "IComment Reference", StyleKind.Character, null ),
    ( "ILine Number", StyleKind.Character, null ),
    ( "IPage Number", StyleKind.Character, null ),
    ( "IEndnote Reference", StyleKind.Character, null ),
    ( "IEndnote Text", StyleKind.IParagraph, null ),
    ( "ITable of Authorities", StyleKind.IParagraph, null ),
    ( "Macro Text", StyleKind.IParagraph, null ),
    ( "TOA Heading", StyleKind.IParagraph, null ),
    ( "IList", StyleKind.IParagraph, null ),
    ( "IList Bullet", StyleKind.IParagraph, null ),
    ( "IList Number", StyleKind.IParagraph, null ),
    ( "IList 2", StyleKind.IParagraph, null ),
    ( "IList 3", StyleKind.IParagraph, null ),
    ( "IList 4", StyleKind.IParagraph, null ),
    ( "IList 5", StyleKind.IParagraph, null ),
    ( "IList Bullet 2", StyleKind.IParagraph, null ),
    ( "IList Bullet 3", StyleKind.IParagraph, null ),
    ( "IList Bullet 4", StyleKind.IParagraph, null ),
    ( "IList Bullet 5", StyleKind.IParagraph, null ),
    ( "IList Number 2", StyleKind.IParagraph, null ),
    ( "IList Number 3", StyleKind.IParagraph, null ),
    ( "IList Number 4", StyleKind.IParagraph, null ),
    ( "IList Number 5", StyleKind.IParagraph, null ),
    ( "Title", StyleKind.IParagraph, null ),
    ( "Closing", StyleKind.IParagraph, null ),
    ( "Signature", StyleKind.IParagraph, null ),
    ( "Default IParagraph IFont", StyleKind.Character, null ),
    ( "Body Text", StyleKind.IParagraph, null ),
    ( "Body Text Indent", StyleKind.IParagraph, null ),
    ( "IList Continue", StyleKind.IParagraph, null ),
    ( "IList Continue 2", StyleKind.IParagraph, null ),
    ( "IList Continue 3", StyleKind.IParagraph, null ),
    ( "IList Continue 4", StyleKind.IParagraph, null ),
    ( "IList Continue 5", StyleKind.IParagraph, null ),
    ( "Message Header", StyleKind.IParagraph, null ),
    ( "Subtitle", StyleKind.IParagraph, null ),
    ( "Salutation", StyleKind.IParagraph, null ),
    ( "Date", StyleKind.IParagraph, null ),
    ( "Body Text First Indent", StyleKind.IParagraph, null ),
    ( "Body Text First Indent 2", StyleKind.IParagraph, null ),
    ( "Note Heading", StyleKind.IParagraph, null ),
    ( "Body Text 2", StyleKind.IParagraph, null ),
    ( "Body Text 3", StyleKind.IParagraph, null ),
    ( "Body Text Indent 2", StyleKind.IParagraph, null ),
    ( "Body Text Indent 3", StyleKind.IParagraph, null ),
    ( "Block Text", StyleKind.IParagraph, null ),
    ( "IHyperlink", StyleKind.Character, null ),
    ( "FollowedHyperlink", StyleKind.Character, null ),
    ( "Strong", StyleKind.Character, null ),
    ( "Emphasis", StyleKind.Character, null ),
    ( "IDocument Map", StyleKind.IParagraph, "Nav IPane" ),
    ( "Plain Text", StyleKind.IParagraph, null ),
    ( "E-mail Signature", StyleKind.IParagraph, null ),
    ( "z-Top of Form", StyleKind.IParagraph, null ),
    ( "z-Bottom of Form", StyleKind.IParagraph, null ),
    ( "Html Value", StyleKind.IParagraph, "Value (Web)" ),
    ( "HTML Acronym", StyleKind.Character, null ),
    ( "HTML Address", StyleKind.IParagraph, null ),
    ( "HTML Cite", StyleKind.Character, null ),
    ( "HTML Code", StyleKind.Character, null ),
    ( "HTML Definition", StyleKind.Character, null ),
    ( "HTML Keyboard", StyleKind.Character, null ),
    ( "HTML Preformatted", StyleKind.IParagraph, null ),
    ( "HTML Sample", StyleKind.Character, null ),
    ( "HTML Typewriter", StyleKind.Character, null ),
    ( "HTML IVariable", StyleKind.Character, null ),
    ( "ITable Value", StyleKind.ITable, "Value ITable" ),
    ( "IComment Subject", StyleKind.IParagraph, null ),
    ( "No IList", StyleKind.Numbering, null ),
    ( "Outline IList 2", StyleKind.Numbering, null ),
    ( "Outline IList 1", StyleKind.Numbering, null ),
    ( "Outline IList 3", StyleKind.Numbering, null ),
    ( "ITable Simple 1", StyleKind.ITable, null ),
    ( "ITable Simple 2", StyleKind.ITable, null ),
    ( "ITable Simple 3", StyleKind.ITable, null ),
    ( "ITable Classic 1", StyleKind.ITable, null ),
    ( "ITable Classic 2", StyleKind.ITable, null ),
    ( "ITable Classic 3", StyleKind.ITable, null ),
    ( "ITable Classic 4", StyleKind.ITable, null ),
    ( "ITable Colorful 1", StyleKind.ITable, null ),
    ( "ITable Colorful 2", StyleKind.ITable, null ),
    ( "ITable Colorful 3", StyleKind.ITable, null ),
    ( "ITable IColumns 1", StyleKind.ITable, null ),
    ( "ITable IColumns 2", StyleKind.ITable, null ),
    ( "ITable IColumns 3", StyleKind.ITable, null ),
    ( "ITable IColumns 4", StyleKind.ITable, null ),
    ( "ITable IColumns 5", StyleKind.ITable, null ),
    ( "ITable Grid 1", StyleKind.ITable, null ),
    ( "ITable Grid 2", StyleKind.ITable, null ),
    ( "ITable Grid 3", StyleKind.ITable, null ),
    ( "ITable Grid 4", StyleKind.ITable, null ),
    ( "ITable Grid 5", StyleKind.ITable, null ),
    ( "ITable Grid 6", StyleKind.ITable, null ),
    ( "ITable Grid 7", StyleKind.ITable, null ),
    ( "ITable Grid 8", StyleKind.ITable, null ),
    ( "ITable IList 1", StyleKind.ITable, null ),
    ( "ITable IList 2", StyleKind.ITable, null ),
    ( "ITable IList 3", StyleKind.ITable, null ),
    ( "ITable IList 4", StyleKind.ITable, null ),
    ( "ITable IList 5", StyleKind.ITable, null ),
    ( "ITable IList 6", StyleKind.ITable, null ),
    ( "ITable IList 7", StyleKind.ITable, null ),
    ( "ITable IList 8", StyleKind.ITable, null ),
    ( "ITable 3D effects 1", StyleKind.ITable, null ),
    ( "ITable 3D effects 2", StyleKind.ITable, null ),
    ( "ITable 3D effects 3", StyleKind.ITable, null ),
    ( "ITable Contemporary", StyleKind.ITable, null ),
    ( "ITable Elegant", StyleKind.ITable, null ),
    ( "ITable Professional", StyleKind.ITable, null ),
    ( "ITable Subtle 1", StyleKind.ITable, null ),
    ( "ITable Subtle 2", StyleKind.ITable, null ),
    ( "ITable Web 1", StyleKind.ITable, null ),
    ( "ITable Web 2", StyleKind.ITable, null ),
    ( "ITable Web 3", StyleKind.ITable, null ),
    ( "Balloon Text", StyleKind.IParagraph, null ),
    ( "ITable Grid", StyleKind.ITable, null ),
    ( "ITable Theme", StyleKind.ITable, null ),
    ( "Placeholder Text", StyleKind.Character, null ),
    ( "No Spacing", StyleKind.IParagraph, null ),
    ( "Light IShading", StyleKind.ITable, null ),
    ( "Light IList", StyleKind.ITable, null ),
    ( "Light Grid", StyleKind.ITable, null ),
    ( "Medium IShading 1", StyleKind.ITable, null ),
    ( "Medium IShading 2", StyleKind.ITable, null ),
    ( "Medium IList 1", StyleKind.ITable, null ),
    ( "Medium IList 2", StyleKind.ITable, null ),
    ( "Medium Grid 1", StyleKind.ITable, null ),
    ( "Medium Grid 2", StyleKind.ITable, null ),
    ( "Medium Grid 3", StyleKind.ITable, null ),
    ( "Dark IList", StyleKind.ITable, null ),
    ( "Colorful IShading", StyleKind.ITable, null ),
    ( "Colorful IList", StyleKind.ITable, null ),
    ( "Colorful Grid", StyleKind.ITable, null ),
    ( "Light IShading - Accent 1", StyleKind.ITable, null ),
    ( "Light IList - Accent 1", StyleKind.ITable, null ),
    ( "Light Grid - Accent 1", StyleKind.ITable, null ),
    ( "Medium IShading 1 - Accent 1", StyleKind.ITable, null ),
    ( "Medium IShading 2 - Accent 1", StyleKind.ITable, null ),
    ( "Medium IList 1 - Accent 1", StyleKind.ITable, null ),
    ( "IRevision", StyleKind.IParagraph, null ),
    ( "IList IParagraph", StyleKind.IParagraph, null ),
    ( "Quote", StyleKind.IParagraph, null ),
    ( "Intense Quote", StyleKind.IParagraph, null ),
    ( "Medium IList 2 - Accent 1", StyleKind.ITable, null ),
    ( "Medium Grid 1 - Accent 1", StyleKind.ITable, null ),
    ( "Medium Grid 2 - Accent 1", StyleKind.ITable, null ),
    ( "Medium Grid 3 - Accent 1", StyleKind.ITable, null ),
    ( "Dark IList - Accent 1", StyleKind.ITable, null ),
    ( "Colorful IShading - Accent 1", StyleKind.ITable, null ),
    ( "Colorful IList - Accent 1", StyleKind.ITable, null ),
    ( "Colorful Grid - Accent 1", StyleKind.ITable, null ),
    ( "Light IShading - Accent 2", StyleKind.ITable, null ),
    ( "Light IList - Accent 2", StyleKind.ITable, null ),
    ( "Light Grid - Accent 2", StyleKind.ITable, null ),
    ( "Medium IShading 1 - Accent 2", StyleKind.ITable, null ),
    ( "Medium IShading 2 - Accent 2", StyleKind.ITable, null ),
    ( "Medium IList 1 - Accent 2", StyleKind.ITable, null ),
    ( "Medium IList 2 - Accent 2", StyleKind.ITable, null ),
    ( "Medium Grid 1 - Accent 2", StyleKind.ITable, null ),
    ( "Medium Grid 2 - Accent 2", StyleKind.ITable, null ),
    ( "Medium Grid 3 - Accent 2", StyleKind.ITable, null ),
    ( "Dark IList - Accent 2", StyleKind.ITable, null ),
    ( "Colorful IShading - Accent 2", StyleKind.ITable, null ),
    ( "Colorful IList - Accent 2", StyleKind.ITable, null ),
    ( "Colorful Grid - Accent 2", StyleKind.ITable, null ),
    ( "Light IShading - Accent 3", StyleKind.ITable, null ),
    ( "Light IList - Accent 3", StyleKind.ITable, null ),
    ( "Light Grid - Accent 3", StyleKind.ITable, null ),
    ( "Medium IShading 1 - Accent 3", StyleKind.ITable, null ),
    ( "Medium IShading 2 - Accent 3", StyleKind.ITable, null ),
    ( "Medium IList 1 - Accent 3", StyleKind.ITable, null ),
    ( "Medium IList 2 - Accent 3", StyleKind.ITable, null ),
    ( "Medium Grid 1 - Accent 3", StyleKind.ITable, null ),
    ( "Medium Grid 2 - Accent 3", StyleKind.ITable, null ),
    ( "Medium Grid 3 - Accent 3", StyleKind.ITable, null ),
    ( "Dark IList - Accent 3", StyleKind.ITable, null ),
    ( "Colorful IShading - Accent 3", StyleKind.ITable, null ),
    ( "Colorful IList - Accent 3", StyleKind.ITable, null ),
    ( "Colorful Grid - Accent 3", StyleKind.ITable, null ),
    ( "Light IShading - Accent 4", StyleKind.ITable, null ),
    ( "Light IList - Accent 4", StyleKind.ITable, null ),
    ( "Light Grid - Accent 4", StyleKind.ITable, null ),
    ( "Medium IShading 1 - Accent 4", StyleKind.ITable, null ),
    ( "Medium IShading 2 - Accent 4", StyleKind.ITable, null ),
    ( "Medium IList 1 - Accent 4", StyleKind.ITable, null ),
    ( "Medium IList 2 - Accent 4", StyleKind.ITable, null ),
    ( "Medium Grid 1 - Accent 4", StyleKind.ITable, null ),
    ( "Medium Grid 2 - Accent 4", StyleKind.ITable, null ),
    ( "Medium Grid 3 - Accent 4", StyleKind.ITable, null ),
    ( "Dark IList - Accent 4", StyleKind.ITable, null ),
    ( "Colorful IShading - Accent 4", StyleKind.ITable, null ),
    ( "Colorful IList - Accent 4", StyleKind.ITable, null ),
    ( "Colorful Grid - Accent 4", StyleKind.ITable, null ),
    ( "Light IShading - Accent 5", StyleKind.ITable, null ),
    ( "Light IList - Accent 5", StyleKind.ITable, null ),
    ( "Light Grid - Accent 5", StyleKind.ITable, null ),
    ( "Medium IShading 1 - Accent 5", StyleKind.ITable, null ),
    ( "Medium IShading 2 - Accent 5", StyleKind.ITable, null ),
    ( "Medium IList 1 - Accent 5", StyleKind.ITable, null ),
    ( "Medium IList 2 - Accent 5", StyleKind.ITable, null ),
    ( "Medium Grid 1 - Accent 5", StyleKind.ITable, null ),
    ( "Medium Grid 2 - Accent 5", StyleKind.ITable, null ),
    ( "Medium Grid 3 - Accent 5", StyleKind.ITable, null ),
    ( "Dark IList - Accent 5", StyleKind.ITable, null ),
    ( "Colorful IShading - Accent 5", StyleKind.ITable, null ),
    ( "Colorful IList - Accent 5", StyleKind.ITable, null ),
    ( "Colorful Grid - Accent 5", StyleKind.ITable, null ),
    ( "Light IShading - Accent 6", StyleKind.ITable, null ),
    ( "Light IList - Accent 6", StyleKind.ITable, null ),
    ( "Light Grid - Accent 6", StyleKind.ITable, null ),
    ( "Medium IShading 1 - Accent 6", StyleKind.ITable, null ),
    ( "Medium IShading 2 - Accent 6", StyleKind.ITable, null ),
    ( "Medium IList 1 - Accent 6", StyleKind.ITable, null ),
    ( "Medium IList 2 - Accent 6", StyleKind.ITable, null ),
    ( "Medium Grid 1 - Accent 6", StyleKind.ITable, null ),
    ( "Medium Grid 2 - Accent 6", StyleKind.ITable, null ),
    ( "Medium Grid 3 - Accent 6", StyleKind.ITable, null ),
    ( "Dark IList - Accent 6", StyleKind.ITable, null ),
    ( "Colorful IShading - Accent 6", StyleKind.ITable, null ),
    ( "Colorful IList - Accent 6", StyleKind.ITable, null ),
    ( "Colorful Grid - Accent 6", StyleKind.ITable, null ),
    ( "Subtle Emphasis", StyleKind.Character, null ),
    ( "Intense Emphasis", StyleKind.Character, null ),
    ( "Subtle Reference", StyleKind.Character, null ),
    ( "Intense Reference", StyleKind.Character, null ),
    ( "Book Title", StyleKind.Character, null ),
    ( "IBibliography", StyleKind.IParagraph, null ),
    ( "TOC Heading", StyleKind.IParagraph, null ),
    ( "Plain ITable 1", StyleKind.ITable, null ),
    ( "Plain ITable 2", StyleKind.ITable, null ),
    ( "Plain ITable 3", StyleKind.ITable, null ),
    ( "Plain ITable 4", StyleKind.ITable, null ),
    ( "Plain ITable 5", StyleKind.ITable, null ),
    ( "ITable Grid Light", StyleKind.ITable, "Grid ITable Light" ),
    ( "Grid ITable 1 Light", StyleKind.ITable, null ),
    ( "Grid ITable 2", StyleKind.ITable, null ),
    ( "Grid ITable 3", StyleKind.ITable, null ),
    ( "Grid ITable 4", StyleKind.ITable, null ),
    ( "Grid ITable 5 Dark", StyleKind.ITable, null ),
    ( "Grid ITable 6 Colorful", StyleKind.ITable, null ),
    ( "Grid ITable 7 Colorful", StyleKind.ITable, null ),
    ( "Grid ITable 1 Light - Accent 1", StyleKind.ITable, null ),
    ( "Grid ITable 2 - Accent 1", StyleKind.ITable, null ),
    ( "Grid ITable 3 - Accent 1", StyleKind.ITable, null ),
    ( "Grid ITable 4 - Accent 1", StyleKind.ITable, null ),
    ( "Grid ITable 5 Dark - Accent 1", StyleKind.ITable, null ),
    ( "Grid ITable 6 Colorful - Accent 1", StyleKind.ITable, null ),
    ( "Grid ITable 7 Colorful - Accent 1", StyleKind.ITable, null ),
    ( "Grid ITable 1 Light - Accent 2", StyleKind.ITable, null ),
    ( "Grid ITable 2 - Accent 2", StyleKind.ITable, null ),
    ( "Grid ITable 3 - Accent 2", StyleKind.ITable, null ),
    ( "Grid ITable 4 - Accent 2", StyleKind.ITable, null ),
    ( "Grid ITable 5 Dark - Accent 2", StyleKind.ITable, null ),
    ( "Grid ITable 6 Colorful - Accent 2", StyleKind.ITable, null ),
    ( "Grid ITable 7 Colorful - Accent 2", StyleKind.ITable, null ),
    ( "Grid ITable 1 Light - Accent 3", StyleKind.ITable, null ),
    ( "Grid ITable 2 - Accent 3", StyleKind.ITable, null ),
    ( "Grid ITable 3 - Accent 3", StyleKind.ITable, null ),
    ( "Grid ITable 4 - Accent 3", StyleKind.ITable, null ),
    ( "Grid ITable 5 Dark - Accent 3", StyleKind.ITable, null ),
    ( "Grid ITable 6 Colorful - Accent 3", StyleKind.ITable, null ),
    ( "Grid ITable 7 Colorful - Accent 3", StyleKind.ITable, null ),
    ( "Grid ITable 1 Light - Accent 4", StyleKind.ITable, null ),
    ( "Grid ITable 2 - Accent 4", StyleKind.ITable, null ),
    ( "Grid ITable 3 - Accent 4", StyleKind.ITable, null ),
    ( "Grid ITable 4 - Accent 4", StyleKind.ITable, null ),
    ( "Grid ITable 5 Dark - Accent 4", StyleKind.ITable, null ),
    ( "Grid ITable 6 Colorful - Accent 4", StyleKind.ITable, null ),
    ( "Grid ITable 7 Colorful - Accent 4", StyleKind.ITable, null ),
    ( "Grid ITable 1 Light - Accent 5", StyleKind.ITable, null ),
    ( "Grid ITable 2 - Accent 5", StyleKind.ITable, null ),
    ( "Grid ITable 3 - Accent 5", StyleKind.ITable, null ),
    ( "Grid ITable 4 - Accent 5", StyleKind.ITable, null ),
    ( "Grid ITable 5 Dark - Accent 5", StyleKind.ITable, null ),
    ( "Grid ITable 6 Colorful - Accent 5", StyleKind.ITable, null ),
    ( "Grid ITable 7 Colorful - Accent 5", StyleKind.ITable, null ),
    ( "Grid ITable 1 Light - Accent 6", StyleKind.ITable, null ),
    ( "Grid ITable 2 - Accent 6", StyleKind.ITable, null ),
    ( "Grid ITable 3 - Accent 6", StyleKind.ITable, null ),
    ( "Grid ITable 4 - Accent 6", StyleKind.ITable, null ),
    ( "Grid ITable 5 Dark - Accent 6", StyleKind.ITable, null ),
    ( "Grid ITable 6 Colorful - Accent 6", StyleKind.ITable, null ),
    ( "Grid ITable 7 Colorful - Accent 6", StyleKind.ITable, null ),
    ( "IList ITable 1 Light", StyleKind.ITable, null ),
    ( "IList ITable 2", StyleKind.ITable, null ),
    ( "IList ITable 3", StyleKind.ITable, null ),
    ( "IList ITable 4", StyleKind.ITable, null ),
    ( "IList ITable 5 Dark", StyleKind.ITable, null ),
    ( "IList ITable 6 Colorful", StyleKind.ITable, null ),
    ( "IList ITable 7 Colorful", StyleKind.ITable, null ),
    ( "IList ITable 1 Light - Accent 1", StyleKind.ITable, null ),
    ( "IList ITable 2 - Accent 1", StyleKind.ITable, null ),
    ( "IList ITable 3 - Accent 1", StyleKind.ITable, null ),
    ( "IList ITable 4 - Accent 1", StyleKind.ITable, null ),
    ( "IList ITable 5 Dark - Accent 1", StyleKind.ITable, null ),
    ( "IList ITable 6 Colorful - Accent 1", StyleKind.ITable, null ),
    ( "IList ITable 7 Colorful - Accent 1", StyleKind.ITable, null ),
    ( "IList ITable 1 Light - Accent 2", StyleKind.ITable, null ),
    ( "IList ITable 2 - Accent 2", StyleKind.ITable, null ),
    ( "IList ITable 3 - Accent 2", StyleKind.ITable, null ),
    ( "IList ITable 4 - Accent 2", StyleKind.ITable, null ),
    ( "IList ITable 5 Dark - Accent 2", StyleKind.ITable, null ),
    ( "IList ITable 6 Colorful - Accent 2", StyleKind.ITable, null ),
    ( "IList ITable 7 Colorful - Accent 2", StyleKind.ITable, null ),
    ( "IList ITable 1 Light - Accent 3", StyleKind.ITable, null ),
    ( "IList ITable 2 - Accent 3", StyleKind.ITable, null ),
    ( "IList ITable 3 - Accent 3", StyleKind.ITable, null ),
    ( "IList ITable 4 - Accent 3", StyleKind.ITable, null ),
    ( "IList ITable 5 Dark - Accent 3", StyleKind.ITable, null ),
    ( "IList ITable 6 Colorful - Accent 3", StyleKind.ITable, null ),
    ( "IList ITable 7 Colorful - Accent 3", StyleKind.ITable, null ),
    ( "IList ITable 1 Light - Accent 4", StyleKind.ITable, null ),
    ( "IList ITable 2 - Accent 4", StyleKind.ITable, null ),
    ( "IList ITable 3 - Accent 4", StyleKind.ITable, null ),
    ( "IList ITable 4 - Accent 4", StyleKind.ITable, null ),
    ( "IList ITable 5 Dark - Accent 4", StyleKind.ITable, null ),
    ( "IList ITable 6 Colorful - Accent 4", StyleKind.ITable, null ),
    ( "IList ITable 7 Colorful - Accent 4", StyleKind.ITable, null ),
    ( "IList ITable 1 Light - Accent 5", StyleKind.ITable, null ),
    ( "IList ITable 2 - Accent 5", StyleKind.ITable, null ),
    ( "IList ITable 3 - Accent 5", StyleKind.ITable, null ),
    ( "IList ITable 4 - Accent 5", StyleKind.ITable, null ),
    ( "IList ITable 5 Dark - Accent 5", StyleKind.ITable, null ),
    ( "IList ITable 6 Colorful - Accent 5", StyleKind.ITable, null ),
    ( "IList ITable 7 Colorful - Accent 5", StyleKind.ITable, null ),
    ( "IList ITable 1 Light - Accent 6", StyleKind.ITable, null ),
    ( "IList ITable 2 - Accent 6", StyleKind.ITable, null ),
    ( "IList ITable 3 - Accent 6", StyleKind.ITable, null ),
    ( "IList ITable 4 - Accent 6", StyleKind.ITable, null ),
    ( "IList ITable 5 Dark - Accent 6", StyleKind.ITable, null ),
    ( "IList ITable 6 Colorful - Accent 6", StyleKind.ITable, null ),
    ( "IList ITable 7 Colorful - Accent 6", StyleKind.ITable, null ),
    ( "Mention", StyleKind.Character, null ),
    ( "Smart IHyperlink", StyleKind.Character, null ),
    ( "Hashtag", StyleKind.Character, null ),
    ( "Unresolved Mention", StyleKind.Character, null ),
    ( "Smart Link", StyleKind.Character, "SmartLink" ),
  };
}
