
namespace DocumentModel.Interop.Core;

public interface _CustomXMLPartEvents_Event
{
  event _CustomXMLPartEvents_NodeAfterInsertEventHandler NodeAfterInsert;
  event _CustomXMLPartEvents_NodeAfterDeleteEventHandler NodeAfterDelete;
  event _CustomXMLPartEvents_NodeAfterReplaceEventHandler NodeAfterReplace;
}