
namespace DocumentModel.Interop.Core;

public delegate void _CustomXMLPartsEvents_PartAfterAddEventHandler(CustomXMLPart NewPart);
public delegate void _CustomXMLPartsEvents_PartBeforeDeleteEventHandler(CustomXMLPart OldPart);
public delegate void _CustomXMLPartsEvents_PartAfterLoadEventHandler(CustomXMLPart Part);

public interface _CustomXMLPartsEvents_Event
{
  public event _CustomXMLPartsEvents_PartAfterAddEventHandler PartAfterAdd;
  public event _CustomXMLPartsEvents_PartBeforeDeleteEventHandler PartBeforeDelete;
  public event _CustomXMLPartsEvents_PartAfterLoadEventHandler PartAfterLoad;
}
