
namespace DocumentModel.Interop.Core;

public interface _CustomTaskPaneEvents_Event
{
  event _CustomTaskPaneEvents_VisibleStateChangeEventHandler VisibleStateChange;
  event _CustomTaskPaneEvents_DockPositionStateChangeEventHandler DockPositionStateChange;
}