using System;

namespace DocumentModel.Interop.Core;

public partial interface ILicAgent
{
  public uint Initialize(uint dwBPC, uint dwMode, string bstrLicSource);
  public string GetFirstName();
  public void SetFirstName(string bstrNewVal);
  public string GetLastName();
  public void SetLastName(string bstrNewVal);
  public string GetOrgName();
  public void SetOrgName(string bstrNewVal);
  public string GetEmail();
  public void SetEmail(string bstrNewVal);
  public string GetPhone();
  public void SetPhone(string bstrNewVal);
  public string GetAddress1();
  public void SetAddress1(string bstrNewVal);
  public string GetCity();
  public void SetCity(string bstrNewVal);
  public string GetState();
  public void SetState(string bstrNewVal);
  public string GetCountryCode();
  public void SetCountryCode(string bstrNewVal);
  public string GetCountryDesc();
  public void SetCountryDesc(string bstrNewVal);
  public string GetZip();
  public void SetZip(string bstrNewVal);
  public uint GetIsoLanguage();
  public void SetIsoLanguage(uint dwNewVal);
  public string GetMSUpdate();
  public void SetMSUpdate(string bstrNewVal);
  public string GetMSOffer();
  public void SetMSOffer(string bstrNewVal);
  public string GetOtherOffer();
  public void SetOtherOffer(string bstrNewVal);
  public string GetAddress2();
  public void SetAddress2(string bstrNewVal);
  public uint CheckSystemClock();
  public DateTime GetExistingExpiryDate();
  public DateTime GetNewExpiryDate();
  public string GetBillingFirstName();
  public void SetBillingFirstName(string bstrNewVal);
  public string GetBillingLastName();
  public void SetBillingLastName(string bstrNewVal);
  public string GetBillingPhone();
  public void SetBillingPhone(string bstrNewVal);
  public string GetBillingAddress1();
  public void SetBillingAddress1(string bstrNewVal);
  public string GetBillingAddress2();
  public void SetBillingAddress2(string bstrNewVal);
  public string GetBillingCity();
  public void SetBillingCity(string bstrNewVal);
  public string GetBillingState();
  public void SetBillingState(string bstrNewVal);
  public string GetBillingCountryCode();
  public void SetBillingCountryCode(string bstrNewVal);
  public string GetBillingZip();
  public void SetBillingZip(string bstrNewVal);
  public uint SaveBillingInfo(int bSave);
  public int IsCCRenewalCountry(string bstrCountryCode);
  public string GetVATLabel(string bstrCountryCode);
  public DateTime GetCCRenewalExpiryDate();
  public void SetVATNumber(string bstrVATNumber);
  public void SetCreditCardType(string bstrCCCode);
  public void SetCreditCardNumber(string bstrCCNumber);
  public void SetCreditCardExpiryYear(uint dwCCYear);
  public void SetCreditCardExpiryMonth(uint dwCCMonth);
  public uint GetCreditCardCount();
  public string GetCreditCardCode(uint dwIndex);
  public string GetCreditCardName(uint dwIndex);
  public string GetVATNumber();
  public string GetCreditCardType();
  public string GetCreditCardNumber();
  public uint GetCreditCardExpiryYear();
  public uint GetCreditCardExpiryMonth();
  public int GetDisconnectOption();
  public void SetDisconnectOption(int bNewVal);
  public void AsyncProcessHandshakeRequest(int bReviseCustInfo);
  public void AsyncProcessNewLicenseRequest();
  public void AsyncProcessReissueLicenseRequest();
  public void AsyncProcessRetailRenewalLicenseRequest();
  public void AsyncProcessReviseCustInfoRequest();
  public void AsyncProcessCCRenewalPriceRequest();
  public void AsyncProcessCCRenewalLicenseRequest();
  public uint GetAsyncProcessReturnCode();
  public int IsUpgradeAvailable();
  public void WantUpgrade(int bWantUpgrade);
  public void AsyncProcessDroppedLicenseRequest();
  public string GenerateInstallationId();
  public uint DepositConfirmationId(string bstrVal);
  public int VerifyCheckDigits(string bstrCIDIID);
  public DateTime GetCurrentExpiryDate();
  public void CancelAsyncProcessRequest(int bIsLicenseRequest);
  public string GetCurrencyDescription(uint dwCurrencyIndex);
  public uint GetPriceItemCount();
  public string GetPriceItemLabel(uint dwIndex);
  public string GetPriceItemValue(uint dwCurrencyIndex, uint dwIndex);
  public string GetInvoiceText();
  public string GetBackendErrorMsg();
  public uint GetCurrencyOption();
  public void SetCurrencyOption(uint dwCurrencyOption);
  public string GetEndOfLifeHtmlText();
  public uint DisplaySSLCert();
}
