using System;

namespace DocumentModel.Interop.Core;

public interface ILicAgent
{
  uint Initialize(uint dwBPC, uint dwMode, string bstrLicSource);
  string GetFirstName();
  void SetFirstName(string bstrNewVal);
  string GetLastName();
  void SetLastName(string bstrNewVal);
  string GetOrgName();
  void SetOrgName(string bstrNewVal);
  string GetEmail();
  void SetEmail(string bstrNewVal);
  string GetPhone();
  void SetPhone(string bstrNewVal);
  string GetAddress1();
  void SetAddress1(string bstrNewVal);
  string GetCity();
  void SetCity(string bstrNewVal);
  string GetState();
  void SetState(string bstrNewVal);
  string GetCountryCode();
  void SetCountryCode(string bstrNewVal);
  string GetCountryDesc();
  void SetCountryDesc(string bstrNewVal);
  string GetZip();
  void SetZip(string bstrNewVal);
  uint GetIsoLanguage();
  void SetIsoLanguage(uint dwNewVal);
  string GetMSUpdate();
  void SetMSUpdate(string bstrNewVal);
  string GetMSOffer();
  void SetMSOffer(string bstrNewVal);
  string GetOtherOffer();
  void SetOtherOffer(string bstrNewVal);
  string GetAddress2();
  void SetAddress2(string bstrNewVal);
  uint CheckSystemClock();
  DateTime GetExistingExpiryDate();
  DateTime GetNewExpiryDate();
  string GetBillingFirstName();
  void SetBillingFirstName(string bstrNewVal);
  string GetBillingLastName();
  void SetBillingLastName(string bstrNewVal);
  string GetBillingPhone();
  void SetBillingPhone(string bstrNewVal);
  string GetBillingAddress1();
  void SetBillingAddress1(string bstrNewVal);
  string GetBillingAddress2();
  void SetBillingAddress2(string bstrNewVal);
  string GetBillingCity();
  void SetBillingCity(string bstrNewVal);
  string GetBillingState();
  void SetBillingState(string bstrNewVal);
  string GetBillingCountryCode();
  void SetBillingCountryCode(string bstrNewVal);
  string GetBillingZip();
  void SetBillingZip(string bstrNewVal);
  uint SaveBillingInfo(int bSave);
  int IsCCRenewalCountry(string bstrCountryCode);
  string GetVATLabel(string bstrCountryCode);
  DateTime GetCCRenewalExpiryDate();
  void SetVATNumber(string bstrVATNumber);
  void SetCreditCardType(string bstrCCCode);
  void SetCreditCardNumber(string bstrCCNumber);
  void SetCreditCardExpiryYear(uint dwCCYear);
  void SetCreditCardExpiryMonth(uint dwCCMonth);
  uint GetCreditCardCount();
  string GetCreditCardCode(uint dwIndex);
  string GetCreditCardName(uint dwIndex);
  string GetVATNumber();
  string GetCreditCardType();
  string GetCreditCardNumber();
  uint GetCreditCardExpiryYear();
  uint GetCreditCardExpiryMonth();
  int GetDisconnectOption();
  void SetDisconnectOption(int bNewVal);
  void AsyncProcessHandshakeRequest(int bReviseCustInfo);
  void AsyncProcessNewLicenseRequest();
  void AsyncProcessReissueLicenseRequest();
  void AsyncProcessRetailRenewalLicenseRequest();
  void AsyncProcessReviseCustInfoRequest();
  void AsyncProcessCCRenewalPriceRequest();
  void AsyncProcessCCRenewalLicenseRequest();
  uint GetAsyncProcessReturnCode();
  int IsUpgradeAvailable();
  void WantUpgrade(int bWantUpgrade);
  void AsyncProcessDroppedLicenseRequest();
  string GenerateInstallationId();
  uint DepositConfirmationId(string bstrVal);
  int VerifyCheckDigits(string bstrCIDIID);
  DateTime GetCurrentExpiryDate();
  void CancelAsyncProcessRequest(int bIsLicenseRequest);
  string GetCurrencyDescription(uint dwCurrencyIndex);
  uint GetPriceItemCount();
  string GetPriceItemLabel(uint dwIndex);
  string GetPriceItemValue(uint dwCurrencyIndex, uint dwIndex);
  string GetInvoiceText();
  string GetBackendErrorMsg();
  uint GetCurrencyOption();
  void SetCurrencyOption(uint dwCurrencyOption);
  string GetEndOfLifeHtmlText();
  uint DisplaySSLCert();
}