<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RootNamespace>DocumentModel</RootNamespace>
    <Description>Definition of document model base types based on OpenXml</Description>
    <Authors>Yarreck Qhta</Authors>
    <Version>1.0</Version>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;8766;0618</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;8766;0618</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="VariantTypes\**" />
    <EmbeddedResource Remove="VariantTypes\**" />
    <None Remove="VariantTypes\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Converters\UriString.XmlSerialization.cs" />
    <Compile Remove="Converters\UriStringJsonConverter.cs" />
    <Compile Remove="UriString.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Qhta.Conversion" Version="2.2.1" />
  </ItemGroup>

</Project>
