<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net4.8;net8.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RootNamespace>DocumentModel</RootNamespace>
    <Description>Definition of document model base types based on OpenXml</Description>
    <Authors>Yarreck Qhta</Authors>
    <Version>1.0</Version>
    <DocumentationFile>docs\BaseTypes.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;8766;0618</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;8766;0618</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Interfaces\**" />
    <Compile Remove="KnownProperties\**" />
    <Compile Remove="VariantTypes\**" />
    <EmbeddedResource Remove="Interfaces\**" />
    <EmbeddedResource Remove="KnownProperties\**" />
    <EmbeddedResource Remove="VariantTypes\**" />
    <None Remove="Interfaces\**" />
    <None Remove="KnownProperties\**" />
    <None Remove="VariantTypes\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Converters\OnOff.XmlSerialization.cs" />
    <Compile Remove="Converters\OnOffJsonConverter.cs" />
    <Compile Remove="Converters\OnOffToggle.XmlSerialization.cs" />
    <Compile Remove="Converters\OnOffToggleJsonConverter.cs" />
    <Compile Remove="Converters\OnOffToggleJsonConvertery.cs" />
    <Compile Remove="OnOff.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Bcl.HashCode" Version="6.0.0" />
    <PackageReference Include="Portable.System.DateTimeOnly" Version="9.0.1" />
    <PackageReference Include="Qhta.Collections" Version="5.4.0" />
    <PackageReference Include="Qhta.Conversion" Version="2.2.1" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.Text.Json" Version="10.0.8" />
  </ItemGroup>

</Project>
