<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RootNamespace>DocumentModel</RootNamespace>
    <Description>Definition of document model base types based on OpenXml</Description>
    <Authors>Yarreck Qhta</Authors>
    <Version>1.0</Version>
    <DocumentationFile>docs\BaseTypes.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;8766;0618</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;8766;0618</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Interfaces\**" />
    <Compile Remove="KnownProperties\**" />
    <Compile Remove="VariantTypes\**" />
    <EmbeddedResource Remove="Interfaces\**" />
    <EmbeddedResource Remove="KnownProperties\**" />
    <EmbeddedResource Remove="VariantTypes\**" />
    <None Remove="Interfaces\**" />
    <None Remove="KnownProperties\**" />
    <None Remove="VariantTypes\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Qhta.Collections" Version="5.3.0" />
    <PackageReference Include="Qhta.Conversion" Version="2.2.1" />
  </ItemGroup>

</Project>
