namespace DocumentModel.Interop.Core;

public partial interface _CommandBars: _IMsoDispObj { }
public partial interface _CustomXMLPart: _IMsoDispObj { }
public partial interface _CustomXMLParts: _IMsoDispObj { }
public partial interface _CustomXMLSchemaCollection: _IMsoDispObj { }
public partial interface Adjustments: _IMsoDispObj { }
public partial interface Balloon: _IMsoDispObj { }
public partial interface CalloutFormat: _IMsoDispObj { }
public partial interface CanvasShapes: _IMsoDispObj { }
public partial interface ColorFormat: _IMsoDispObj { }
public partial interface AnswerWizardFiles: _IMsoDispObj { }
public partial interface Assistant: _IMsoDispObj { }
public partial interface BalloonCheckbox: _IMsoDispObj { }
public partial interface BalloonCheckboxes: _IMsoDispObj { }
public partial interface BalloonLabel: _IMsoDispObj { }
public partial interface BalloonLabels: _IMsoDispObj { }
public partial interface BulletFormat2: _IMsoDispObj { }
public partial interface COMAddIn: _IMsoDispObj { }
public partial interface COMAddIns: _IMsoDispObj { }
public partial interface CommandBarControls: _IMsoDispObj { }
public partial interface CommandBars: _IMsoDispObj { }
public partial interface ConnectorFormat: _IMsoDispObj { }
public partial interface ContactCard: _IMsoDispObj { }
public partial interface Crop: _IMsoDispObj { }
public partial interface CustomXMLNode: _IMsoDispObj { }
public partial interface CustomXMLNodes: _IMsoDispObj { }
public partial interface CustomXMLPart: _IMsoDispObj { }
public partial interface CustomXMLParts: _IMsoDispObj { }
public partial interface CustomXMLPrefixMapping: _IMsoDispObj { }
public partial interface CustomXMLPrefixMappings: _IMsoDispObj { }
public partial interface CustomXMLSchema: _IMsoDispObj { }
public partial interface CustomXMLSchemaCollection: _IMsoDispObj { }
public partial interface CustomXMLValidationError: _IMsoDispObj { }
public partial interface CustomXMLValidationErrors: _IMsoDispObj { }
public partial interface DiagramNode: _IMsoDispObj { }
public partial interface DiagramNodeChildren: _IMsoDispObj { }
public partial interface DiagramNodes: _IMsoDispObj { }
public partial interface DocumentInspector: _IMsoDispObj { }
public partial interface DocumentInspectors: _IMsoDispObj { }
public partial interface DocumentLibraryVersion: _IMsoDispObj { }
public partial interface DocumentLibraryVersions: _IMsoDispObj { }
public partial interface EffectParameter: _IMsoDispObj { }
public partial interface EffectParameters: _IMsoDispObj { }
public partial interface FileDialog: _IMsoDispObj { }
public partial interface FileDialogFilter: _IMsoDispObj { }
public partial interface FileDialogFilters: _IMsoDispObj { }
public partial interface FileDialogSelectedItems: _IMsoDispObj { }
public partial interface FileSearch: _IMsoDispObj { }
public partial interface FileTypes: _IMsoDispObj { }
public partial interface FillFormat: _IMsoDispObj { }
public partial interface Font2: _IMsoDispObj { }
public partial interface FoundFiles: _IMsoDispObj { }
public partial interface FreeformBuilder: _IMsoDispObj { }
public partial interface GlowFormat: _IMsoDispObj { }
public partial interface GradientStop: _IMsoDispObj { }
public partial interface GradientStops: _IMsoDispObj { }
public partial interface GroupShapes: _IMsoDispObj { }
public partial interface HTMLProject: _IMsoDispObj { }
public partial interface HTMLProjectItem: _IMsoDispObj { }
public partial interface HTMLProjectItems: _IMsoDispObj { }
public partial interface IMsoContactCard: _IMsoDispObj { }
public partial interface IMsoDiagram: _IMsoDispObj { }
public partial interface LanguageSettings: _IMsoDispObj { }
public partial interface LineFormat: _IMsoDispObj { }
public partial interface MetaProperties: _IMsoDispObj { }
public partial interface MetaProperty: _IMsoDispObj { }
public partial interface MsoDebugOptions: _IMsoDispObj { }
public partial interface MsoDebugOptions_UT: _IMsoDispObj { }
public partial interface MsoDebugOptions_UTManager: _IMsoDispObj { }
public partial interface MsoDebugOptions_UTRunResult: _IMsoDispObj { }
public partial interface MsoDebugOptions_UTs: _IMsoDispObj { }
public partial interface NewFile: _IMsoDispObj { }
public partial interface ODSOColumn: _IMsoDispObj { }
public partial interface ODSOColumns: _IMsoDispObj { }
public partial interface ODSOFilter: _IMsoDispObj { }
public partial interface ODSOFilters: _IMsoDispObj { }
public partial interface OfficeTheme: _IMsoDispObj { }
public partial interface ParagraphFormat2: _IMsoDispObj { }
public partial interface Permission: _IMsoDispObj { }
public partial interface PickerDialog: _IMsoDispObj { }
public partial interface PickerField: _IMsoDispObj { }
public partial interface PickerFields: _IMsoDispObj { }
public partial interface PickerProperties: _IMsoDispObj { }
public partial interface PickerProperty: _IMsoDispObj { }
public partial interface PickerResult: _IMsoDispObj { }
public partial interface PickerResults: _IMsoDispObj { }
public partial interface PictureEffect: _IMsoDispObj { }
public partial interface PictureEffects: _IMsoDispObj { }
public partial interface PictureFormat: _IMsoDispObj { }
public partial interface PolicyItem: _IMsoDispObj { }
public partial interface PropertyTest: _IMsoDispObj { }
public partial interface PropertyTests: _IMsoDispObj { }
public partial interface ReflectionFormat: _IMsoDispObj { }
public partial interface Ruler2: _IMsoDispObj { }
public partial interface RulerLevel2: _IMsoDispObj { }
public partial interface RulerLevels2: _IMsoDispObj { }
public partial interface ScopeFolder: _IMsoDispObj { }
public partial interface ScopeFolders: _IMsoDispObj { }
public partial interface Script: _IMsoDispObj { }
public partial interface Scripts: _IMsoDispObj { }
public partial interface SearchFolders: _IMsoDispObj { }
public partial interface SearchScope: _IMsoDispObj { }
public partial interface SearchScopes: _IMsoDispObj { }
public partial interface ServerPolicy: _IMsoDispObj { }
public partial interface ShadowFormat: _IMsoDispObj { }
public partial interface Shape: _IMsoDispObj { }
public partial interface ShapeNode: _IMsoDispObj { }
public partial interface ShapeNodes: _IMsoDispObj { }
public partial interface ShapeRange: _IMsoDispObj { }
public partial interface Shapes: _IMsoDispObj { }
public partial interface SharedWorkspace: _IMsoDispObj { }
public partial interface SharedWorkspaceFile: _IMsoDispObj { }
public partial interface SharedWorkspaceFiles: _IMsoDispObj { }
public partial interface SharedWorkspaceFolder: _IMsoDispObj { }
public partial interface SharedWorkspaceFolders: _IMsoDispObj { }
public partial interface SharedWorkspaceLink: _IMsoDispObj { }
public partial interface SharedWorkspaceLinks: _IMsoDispObj { }
public partial interface SharedWorkspaceMember: _IMsoDispObj { }
public partial interface SharedWorkspaceMembers: _IMsoDispObj { }
public partial interface SharedWorkspaceTask: _IMsoDispObj { }
public partial interface SharedWorkspaceTasks: _IMsoDispObj { }
public partial interface Signature: _IMsoDispObj { }
public partial interface SignatureInfo: _IMsoDispObj { }
public partial interface SignatureSet: _IMsoDispObj { }
public partial interface SignatureSetup: _IMsoDispObj { }
public partial interface SmartArt: _IMsoDispObj { }
public partial interface SmartArtColor: _IMsoDispObj { }
public partial interface SmartArtColors: _IMsoDispObj { }
public partial interface SmartArtLayout: _IMsoDispObj { }
public partial interface SmartArtLayouts: _IMsoDispObj { }
public partial interface SmartArtNode: _IMsoDispObj { }
public partial interface SmartArtNodes: _IMsoDispObj { }
public partial interface SmartArtQuickStyle: _IMsoDispObj { }
public partial interface SmartArtQuickStyles: _IMsoDispObj { }
public partial interface SmartDocument: _IMsoDispObj { }
public partial interface SoftEdgeFormat: _IMsoDispObj { }
public partial interface Sync: _IMsoDispObj { }
public partial interface TabStop2: _IMsoDispObj { }
public partial interface TabStops2: _IMsoDispObj { }
public partial interface TextColumn2: _IMsoDispObj { }
public partial interface TextEffectFormat: _IMsoDispObj { }
public partial interface TextFrame: _IMsoDispObj { }
public partial interface TextFrame2: _IMsoDispObj { }
public partial interface TextRange2: _IMsoDispObj { }
public partial interface ThemeColor: _IMsoDispObj { }
public partial interface ThemeColorScheme: _IMsoDispObj { }
public partial interface ThemeEffectScheme: _IMsoDispObj { }
public partial interface ThemeFont: _IMsoDispObj { }
public partial interface ThemeFonts: _IMsoDispObj { }
public partial interface ThemeFontScheme: _IMsoDispObj { }
public partial interface ThreeDFormat: _IMsoDispObj { }
public partial interface UserPermission: _IMsoDispObj { }
public partial interface WebPageFont: _IMsoDispObj { }
public partial interface WebPageFonts: _IMsoDispObj { }
public partial interface WorkflowTask: _IMsoDispObj { }
public partial interface WorkflowTasks: _IMsoDispObj { }
public partial interface WorkflowTemplate: _IMsoDispObj { }
public partial interface WorkflowTemplates: _IMsoDispObj { }
