namespace DocumentModel.BaseConverters.Test;

public static class Namespaces
{
  public static Dictionary<string,string> Map { get; } = new()
  {
    { "DX", "DocumentFormat.OpenXml" },
    { "DXB", "DocumentFormat.OpenXml.Bibliography" },
    { "DXCP", "DocumentFormat.OpenXml.CustomProperties" },
    { "DXCXSR", "DocumentFormat.OpenXml.CustomXmlSchemaReferences" },
    { "DXD", "DocumentFormat.OpenXml.Drawing" },
    { "DXDD", "DocumentFormat.OpenXml.Drawing.Diagrams" },
    { "DXDP", "DocumentFormat.OpenXml.Drawing.Pictures" },
    { "DXDW", "DocumentFormat.OpenXml.Drawing.Wordprocessing" },
    { "DXEP", "DocumentFormat.OpenXml.ExtendedProperties" },
    { "DXM", "DocumentFormat.OpenXml.Math" },
    { "DXO10D", "DocumentFormat.OpenXml.Office2010.Drawing" },
    { "DXO10DP", "DocumentFormat.OpenXml.Office2010.Drawing.Pictures" },
    { "DXO10W", "DocumentFormat.OpenXml.Office2010.Word" },
    { "DXO10WD", "DocumentFormat.OpenXml.Office2010.Word.Drawing" },
    { "DXO10WDC", "DocumentFormat.OpenXml.Office2010.Word.DrawingCanvas" },
    { "DXO10WDG", "DocumentFormat.OpenXml.Office2010.Word.DrawingGroup" },
    { "DXO10WDS", "DocumentFormat.OpenXml.Office2010.Word.DrawingShape" },
    { "DXO13D", "DocumentFormat.OpenXml.Office2013.Drawing" },
    { "DXO13T", "DocumentFormat.OpenXml.Office2013.Theme" },
    { "DXO13W", "DocumentFormat.OpenXml.Office2013.Word" },
    { "DXO13WD", "DocumentFormat.OpenXml.Office2013.Word.Drawing" },
    { "DXO16D", "DocumentFormat.OpenXml.Office2016.Drawing" },
    { "DXO19D", "DocumentFormat.OpenXml.Office2019.Drawing" },
    { "DXO19DS", "DocumentFormat.OpenXml.Office2019.Drawing.SVG" },
    { "DXO19WC", "DocumentFormat.OpenXml.Office2019.Word.Cid" },
    { "DXO21DDC", "DocumentFormat.OpenXml.Office2021.Drawing.DocumentClassification" },
    { "DXO21DL", "DocumentFormat.OpenXml.Office2021.Drawing.Livefeed" },
    { "DXO21DSS", "DocumentFormat.OpenXml.Office2021.Drawing.SketchyShapes" },
    { "DXO21MLMD", "DocumentFormat.OpenXml.Office2021.MipLabelMetaData" },
    { "DXO21WCE", "DocumentFormat.OpenXml.Office2021.Word.CommentsExt" },
    { "DXOD", "DocumentFormat.OpenXml.Office.Drawing" },
    { "DXODY21OE", "DocumentFormat.OpenXml.Office.Drawing.Y2021.OEmbed" },
    { "DXOW", "DocumentFormat.OpenXml.Office.Word" },
    { "DXOWY20OE", "DocumentFormat.OpenXml.Office.Word.Y2020.OEmbed" },
    { "DXOY21SL", "DocumentFormat.OpenXml.Office.Drawing.Y2021.ScriptLink" },
    { "DXPP", "DocumentFormat.OpenXml.Packaging" },
    { "DXV", "DocumentFormat.OpenXml.Vml" },
    { "DXVO", "DocumentFormat.OpenXml.Vml.Office" },
    { "DXVS", "DocumentFormat.OpenXml.Vml.Spreadsheet" },
    { "DXVT", "DocumentFormat.OpenXml.VariantTypes" },
    { "DXVW", "DocumentFormat.OpenXml.Vml.Wordprocessing" },
    { "DXW", "DocumentFormat.OpenXml.Wordprocessing" },
  };
}