<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>DocumentModel</RootNamespace>
    <AppDesignerFolder>Properties and settings</AppDesignerFolder>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Base interfaces\ITypedModelElement.cs" />
    <Compile Remove="Properties and settings\CoreProperties.IDocumentProperties.cs" />
    <Compile Remove="Properties and settings\DocumentSetting.cs" />
    <Compile Remove="Properties and settings\DocumentSettings.cs" />
    <Compile Remove="Wordprocessing\Settings\Settings.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Properties and settings\ContentProperties.ShouldSerialize.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.4.1" />
    <PackageReference Include="DocumentFormat.OpenXml.Framework" Version="3.4.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DocumentModel.BaseConverters\DocumentModel.BaseConverters.csproj" />
    <ProjectReference Include="..\DocumentModel.BaseTypes\DocumentModel.BaseTypes.csproj" />
  </ItemGroup>

</Project>
