<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>DocumentModel</RootNamespace>
    <AppDesignerFolder>Properties and settings</AppDesignerFolder>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;0659;0612;1574</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;0659;0612;1574</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="**\*.Methods.cs" />
    <Compile Remove="**\*.Imp.cs" />
    <Compile Remove="Drawings\Wordprocessing\Colors\**" />
    <Compile Remove="VariantTypes\Enums\**" />
    <EmbeddedResource Remove="Drawings\Wordprocessing\Colors\**" />
    <EmbeddedResource Remove="VariantTypes\Enums\**" />
    <None Remove="Drawings\Wordprocessing\Colors\**" />
    <None Remove="VariantTypes\Enums\**" />

  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Drawings\Colors\DrawingColor.cs" />
    <Compile Remove="Drawings\Colors\IDrawingColor.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Wordprocessing\Table properties\Enums\5k3e00t1.egu~" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\NamespaceMappings\OpenXmlUsings.cs" Link="OpenXmlUsings.cs" />
    <Compile Include="Base classes\ModelElement%28T%29.Imp.cs" />
    <Compile Include="Base classes\ModelElement.Imp.cs" />
    <Compile Include="Common properties\BuiltInProperties.Imp.cs" />
    <Compile Include="Common properties\BuiltInProperty.Imp.cs" />
    <Compile Include="Common properties\CustomProperties.Imp.cs" />
    <Compile Include="Common properties\CustomProperty.Imp.cs" />
    <Compile Include="Drawings\Colors\HslColor.Imp.cs" />
    <Compile Include="Drawings\Colors\SchemeColor.Imp.cs" />
    <Compile Include="Drawings\Colors\PresetColor.Imp.cs" />
    <Compile Include="Drawings\Colors\RgbColorModelPercentage.Imp.cs" />
    <Compile Include="Drawings\Colors\RgbColorModelHex.Imp.cs" />
    <Compile Include="Drawings\Colors\SystemColor.Imp.cs" />
    <Compile Include="Wordprocessing\Common\Color.Imp.cs" />
    <Compile Include="Wordprocessing\Document\Document.Imp.cs" />
    <Compile Include="Wordprocessing\Run properties\BaseRunProperties.TextFormat.Imp.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include=".github\copilot-instructions.md" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
    <PackageReference Include="DocumentFormat.OpenXml.Framework" Version="3.5.1" />
    <PackageReference Include="Microsoft.Office.Interop.Word" Version="15.0.4797.1004" />
    <PackageReference Include="Qhta.Collections" Version="5.4.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\MyLib\Qhta.OpenXMLTools\Qhta.OpenXmlTools.csproj" />
    <ProjectReference Include="..\DocumentModel.BaseConverters\DocumentModel.BaseConverters.csproj" />
    <ProjectReference Include="..\DocumentModel.BaseTypes\DocumentModel.BaseTypes.csproj" />
    <ProjectReference Include="..\DocumentModel.EnumTypes\DocumentModel.EnumTypes.csproj" />
    <ProjectReference Include="..\DocumentModel.Interfaces\DocumentModel.Interfaces.csproj" />
  </ItemGroup>
</Project>
