<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>DocumentModel</RootNamespace>
    <AppDesignerFolder>Properties and settings</AppDesignerFolder>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;0659;0612;1574</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;0659;0612;1574</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="**\*.Methods.cs" />
    <Compile Remove="**\*.Imp.cs" />
    <Compile Remove="VariantTypes\Enums\**" />
    <EmbeddedResource Remove="VariantTypes\Enums\**" />
    <None Remove="VariantTypes\Enums\**" />

  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Base classes\LazyLoadElementCollection%28T,C%29.cs" />
    <Compile Remove="Common properties\BuiltInDocumentProperties.cs" />
    <Compile Remove="Common properties\CoreProperties.DocumentProperties.Impl.cs" />
    <Compile Remove="Drawings\Colors\ColorHolder%28T%29.XmlSerialization.cs" />
    <Compile Remove="Drawings\Colors\ColorHolderJsonConverter.cs" />
    <Compile Remove="Drawings\Colors\ColorType.XmlSerialization.cs" />
    <Compile Remove="Drawings\Colors\ColorTypeJsonConverter.cs" />
    <Compile Remove="Drawings\Colors\DrawingColor.cs" />
    <Compile Remove="Drawings\Colors\DrawingsColorBase.ShouldSerialize.cs" />
    <Compile Remove="Drawings\ColorTransformations\ColorTransformation%28T%29.cs" />
    <Compile Remove="Drawings\Text elements and properties\FontCollectionType.cs" />
    <Compile Remove="Drawings\Text elements and properties\FontCollectionType.ShouldSerialize.cs" />
    <Compile Remove="Math\Argument.cs" />
    <Compile Remove="Math\Argument.ShouldSerialize.cs" />
    <Compile Remove="Vml\Rules.JsonConversion.cs" />
    <Compile Remove="Wordprocessing\Colors\Color.ShouldSerialize.cs" />
    <Compile Remove="Wordprocessing\Colors\RgbColorModelHex.ShouldSerialize.cs" />
    <Compile Remove="Wordprocessing\Colors\SchemeColor.ShouldSerialize.cs" />
    <Compile Remove="Wordprocessing\Common\Color.XmlSerialization.cs" />
    <Compile Remove="Wordprocessing\Common\ColorJsonConverter.cs" />
    <Compile Remove="Wordprocessing\Mail merge\FieldMapDataCollection.cs" />
    <Compile Remove="Wordprocessing\Styles\StyleDef.ext.cs" />
    <Compile Remove="Wordprocessing\Styles\StyleDefinition.ext.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="docs\Colors.docx" />
    <None Remove="Wordprocessing\Table properties\Enums\5k3e00t1.egu~" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\NamespaceMappings\OpenXmlUsings.cs" Link="OpenXmlUsings.cs" />
    <Compile Include="Base classes\ModelElement%28T%29.Imp.cs" />
    <Compile Include="Base classes\ModelElement.Imp.cs" />
    <Compile Include="Common properties\BuiltInProperty.Interface.Imp.cs" />
    <Compile Include="Common properties\CustomProperties.Imp.cs" />
    <Compile Include="Common properties\CustomProperty.Imp.cs" />
    <Compile Include="Drawings\Colors\DrawingsColorBase.Imp.cs" />
    <Compile Include="Drawings\Colors\HslColor.Imp.cs" />
    <Compile Include="Drawings\Colors\PresetColor.Imp.cs" />
    <Compile Include="Drawings\Colors\ColorType.Imp.cs" />
    <Compile Include="Drawings\Colors\RgbColorModelHex.Imp.cs" />
    <Compile Include="Drawings\Colors\RgbColorModelPercentage.Imp.cs" />
    <Compile Include="Drawings\Colors\SchemeColor.Imp.cs" />
    <Compile Include="Drawings\Colors\SystemColor.Imp.cs" />
    <Compile Include="Vml\Color.Imp.cs" />
    <Compile Include="Vml\RgbColor.Imp.cs" />
    <Compile Include="Wordprocessing\Colors\RgbColorHex.Imp.cs" />
    <Compile Include="Wordprocessing\Colors\SchemeColor.Imp.cs" />
    <Compile Include="Wordprocessing\Colors\Color.Imp.cs" />
    <Compile Include="Wordprocessing\Run properties\BaseRunProperties.TextFormat.Imp.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include=".github\copilot-instructions.md" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
    <PackageReference Include="DocumentFormat.OpenXml.Framework" Version="3.5.1" />
    <PackageReference Include="Microsoft.Office.Interop.Word" Version="15.0.4797.1004" />
    <PackageReference Include="Qhta.Collections" Version="5.4.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\MyLib\Qhta.OpenXMLTools\Qhta.OpenXmlTools.csproj" />
    <ProjectReference Include="..\DocumentModel.BaseConverters\DocumentModel.BaseConverters.csproj" />
    <ProjectReference Include="..\DocumentModel.BaseTypes\DocumentModel.BaseTypes.csproj" />
    <ProjectReference Include="..\DocumentModel.EnumTypes\DocumentModel.EnumTypes.csproj" />
    <ProjectReference Include="..\DocumentModel.Interfaces\DocumentModel.Interfaces.csproj" />
  </ItemGroup>
</Project>
