namespace DocumentModel.Packaging;


/// <summary>
///   To help end-users identify parts of a package or the package as a whole, images, called thumbnails, can be stored in that package. Each thumbnail image is generated by the package producer and is stored in the package as a ZIP item. There are no limitations on the size or dimensions of the thumbnail produced, and applications are free to scale the images as desired.
/// </summary>
public partial class ThumbnailPart: ModelElement<DXPack.ThumbnailPart>
{
  public ThumbnailPart(): base(){ }
  
  public ThumbnailPart(DX.OpenXmlElement openXmlElement): base(openXmlElement) { }
  
  public ThumbnailPart(DXPack.ThumbnailPart openXmlElement): base(openXmlElement) { }
  
  [DataMember]
  public String? RelationshipType
  {
    get
    {
      return _Element?.RelationshipType;
    }
    set
    {
      _ExistingElement.RelationshipType = value;
    }
  }
  
}
