<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Wordprocessing\Sections\**" />
    <EmbeddedResource Remove="Wordprocessing\Sections\**" />
    <None Remove="Wordprocessing\Sections\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\NamespaceMappings\OpenXmlUsings.cs" Link="OpenXmlUsings.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DocumentModel.BaseConverters\DocumentModel.BaseConverters.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\Scripts\ListEnumTypesUsage.py" Link="Scripts\ListEnumTypesUsage.py" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Wordprocessing\CustomXml\" />
    <Folder Include="Wordprocessing\Drawings\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Office.Interop.Word" Version="15.0.4797.1004" />
  </ItemGroup>

</Project>
