//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelGenApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
           [DebuggerStepThrough] get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModelGenApp.CommonStrings", typeof(CommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
           [DebuggerStepThrough] get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptance.
        /// </summary>
        public static string Acceptance {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Acceptance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether the item was accepted or rejected at the end of the current phase..
        /// </summary>
        public static string AcceptanceTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("AcceptanceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AcceptedOnly.
        /// </summary>
        public static string AcceptedOnly {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("AcceptedOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted types.
        /// </summary>
        public static string AcceptedTypes {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("AcceptedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add docs.
        /// </summary>
        public static string AddDocs {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("AddDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new application data folder.
        /// </summary>
        public static string AddNewAppDataFolder {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("AddNewAppDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All types.
        /// </summary>
        public static string AllTypes {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("AllTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App data folder.
        /// </summary>
        public static string AppDataFolder {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("AppDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App data folder \&quot;{0}\&quot; already exists.
        /// </summary>
        public static string AppDataFolderAlreadyExists_1 {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("AppDataFolderAlreadyExists_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subfolder of AppData folder containing model configuration.
        /// </summary>
        public static string AppDataFolderTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("AppDataFolderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base type.
        /// </summary>
        public static string BaseType {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("BaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked types.
        /// </summary>
        public static string CheckedTypes {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("CheckedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        public static string Classes {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class types.
        /// </summary>
        public static string ClassTypes {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ClassTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code output path is not defined.
        /// </summary>
        public static string Code_output_path_not_defined {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Code_output_path_not_defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code compilation.
        /// </summary>
        public static string CodeCompilation {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("CodeCompilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code generation.
        /// </summary>
        public static string CodeGen {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("CodeGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code output path.
        /// </summary>
        public static string CodeOutputPath {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("CodeOutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation error list.
        /// </summary>
        public static string CompilationErrorList {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("CompilationErrorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation errors.
        /// </summary>
        public static string CompilationErrors {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("CompilationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Config {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config property name.
        /// </summary>
        public static string ConfigPropertyName {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ConfigPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config property name is declared name of the property. 
        ///Can contain * as a wildcard..
        /// </summary>
        public static string ConfigPropertyNameTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ConfigPropertyNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion target.
        /// </summary>
        public static string ConversionTarget {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ConversionTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion target is a type resulted from conversion phase..
        /// </summary>
        public static string ConversionTargetTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ConversionTargetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted types.
        /// </summary>
        public static string ConvertedTypes {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ConvertedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert types.
        /// </summary>
        public static string ConvertTypes {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ConvertTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy content from.
        /// </summary>
        public static string CopyContentFrom {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("CopyContentFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaring type.
        /// </summary>
        public static string DeclaringType {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("DeclaringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaring type is a type in which the property is declared. 
        ///It can be the current type or one of its base types..
        /// </summary>
        public static string DeclaringTypeTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("DeclaringTypeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derived types.
        /// </summary>
        public static string DerivedTypes {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("DerivedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short description..
        /// </summary>
        public static string DescriptionTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("DescriptionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display options.
        /// </summary>
        public static string DisplayOptions {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("DisplayOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display options:.
        /// </summary>
        public static string DisplayOptions_ {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("DisplayOptions_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Documentation {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated shortcut.
        /// </summary>
        public static string Duplicated_shortcut {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Duplicated shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated types in target namespace.
        /// </summary>
        public static string Duplicated_types_in_target_namespace {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Duplicated_types_in_target_namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enums.
        /// </summary>
        public static string Enums {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Enums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum types.
        /// </summary>
        public static string EnumTypes {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("EnumTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum value name.
        /// </summary>
        public static string EnumValName {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("EnumValName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum value name is an original or target name 
        ///defined in the enum type (depending on processing phase)..
        /// </summary>
        public static string EnumValNameTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("EnumValNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum vals.
        /// </summary>
        public static string EnumVals {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("EnumVals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum value.
        /// </summary>
        public static string EnumValue {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("EnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum values.
        /// </summary>
        public static string EnumValues {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("EnumValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum value is a numeric value of the named value
        ///defined in the enum type..
        /// </summary>
        public static string EnumValueTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("EnumValueTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code.
        /// </summary>
        public static string ErrorCode {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude.
        /// </summary>
        public static string Exclude {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is excluded?.
        /// </summary>
        public static string ExcludedNamespace {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ExcludedNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded namespace is rejected from scanning..
        /// </summary>
        public static string ExcludedNamespaceTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ExcludedNamespaceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excl.prop..
        /// </summary>
        public static string ExcludedProperty {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ExcludedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excl.prop.ns..
        /// </summary>
        public static string ExcludedPropertyNamespace {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ExcludedPropertyNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is property namespace excluded?.
        /// </summary>
        public static string ExcludedPropertyNamespaceTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ExcludedPropertyNamespaceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded property is rejected even if its type is accepted..
        /// </summary>
        public static string ExcludedPropertyTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ExcludedPropertyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excl.prop.type.
        /// </summary>
        public static string ExcludedPropertyType {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ExcludedPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is property type excluded?.
        /// </summary>
        public static string ExcludedPropertyTypeTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ExcludedPropertyTypeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excl.target ns..
        /// </summary>
        public static string ExcludedTargetNamespace {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ExcludedTargetNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target namespace is excluded from code generation..
        /// </summary>
        public static string ExcludedTargetNamespaceTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ExcludedTargetNamespaceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is type excluded?.
        /// </summary>
        public static string ExcludedType {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ExcludedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded type is rejected even if its namespace is included..
        /// </summary>
        public static string ExcludedTypeTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ExcludedTypeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excl.val.type.
        /// </summary>
        public static string ExcludedValueType {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ExcludedValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is value type excluded from processing?.
        /// </summary>
        public static string ExcludedValueTypeTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ExcludedValueTypeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string Filename {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File tree.
        /// </summary>
        public static string FileTree {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("FileTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with docs.
        /// </summary>
        public static string FileWithDocs {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("FileWithDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is XML file with types and properties descriptions. 
        ///It should be prepared by an external tool..
        /// </summary>
        public static string FileWithDocsTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("FileWithDocsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use or omit adding docs from file..
        /// </summary>
        public static string FileWithDocsUseTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("FileWithDocsUseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIlter results.
        /// </summary>
        public static string FilterResults {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("FilterResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final fix.
        /// </summary>
        public static string FinalFix {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("FinalFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed types.
        /// </summary>
        public static string FixedTypes {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("FixedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated files.
        /// </summary>
        public static string GeneratedFiles {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("GeneratedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated types.
        /// </summary>
        public static string GeneratedTypes {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("GeneratedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator type.
        /// </summary>
        public static string GeneratorType {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("GeneratorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator type specifies the way of output generation.
        /// </summary>
        public static string GeneratorTypeTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("GeneratorTypeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include.
        /// </summary>
        public static string Include {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is type included?.
        /// </summary>
        public static string IncludedType {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("IncludedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included type is accepted even if its namespaces is excluded..
        /// </summary>
        public static string IncludedTypeTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("IncludedTypeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming relationships.
        /// </summary>
        public static string IncomingRelationships {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("IncomingRelationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input assembly.
        /// </summary>
        public static string InputAssembly {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("InputAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input assembly to parse.
        /// </summary>
        public static string InputAssemblyTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("InputAssemblyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interfaces.
        /// </summary>
        public static string Interfaces {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Interfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InterfaceTypes.
        /// </summary>
        public static string InterfaceTypes {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("InterfaceTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid generic argument type.
        /// </summary>
        public static string InvalidGenericArgType {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("InvalidGenericArgType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid properties.
        /// </summary>
        public static string InvalidProperties {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("InvalidProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid types.
        /// </summary>
        public static string InvalidTypes {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("InvalidTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind.
        /// </summary>
        public static string Kind {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document model generator.
        /// </summary>
        public static string MainWindowTitle {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meaningless description.
        /// </summary>
        public static string MeaninglessDescription {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("MeaninglessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string Members {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing description.
        /// </summary>
        public static string MissingDescription {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("MissingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing generic argument type.
        /// </summary>
        public static string MissingGenericArgType {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("MissingGenericArgType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing included types relationships.
        /// </summary>
        public static string MissingIncludedTypeRels {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("MissingIncludedTypeRels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing included types in schema.
        /// </summary>
        public static string MissingIncludedTypeSchema {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("MissingIncludedTypeSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing properties.
        /// </summary>
        public static string MissingProperties {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("MissingProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing property target type.
        /// </summary>
        public static string MissingPropertyTargetType {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("MissingPropertyTargetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing schema.
        /// </summary>
        public static string MissingSchema {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("MissingSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing some included types relationships:.
        /// </summary>
        public static string MissingSomeIncludedTypeRels {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("MissingSomeIncludedTypeRels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing some included types in schema:.
        /// </summary>
        public static string MissingSomeIncludedTypeSchema {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("MissingSomeIncludedTypeSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing target namespace.
        /// </summary>
        public static string MissingTargetNamespace {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("MissingTargetNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model configuration is invalid. See marks in the table..
        /// </summary>
        public static string Model_configuration_is_invalid {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Model_configuration_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model configuration is not defined..
        /// </summary>
        public static string Model_configuration_not_defined {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Model_configuration_not_defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model configuration saved in {0}.
        /// </summary>
        public static string Model_configuration_saved_in_0 {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Model_configuration_saved_in_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model configuration.
        /// </summary>
        public static string ModelConfiguration {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ModelConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target namespace has multiple types with the same name..
        /// </summary>
        public static string MultiplicatedName {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("MultiplicatedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace.
        /// </summary>
        public static string Namespace {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespaces.
        /// </summary>
        public static string Namespaces {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New folder name.
        /// </summary>
        public static string NewFolderName {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("NewFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No error.
        /// </summary>
        public static string NoError {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("NoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main options.
        /// </summary>
        public static string OptionsExpanderHeader {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("OptionsExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original declaration type.
        /// </summary>
        public static string OriginalDeclarationType {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("OriginalDeclarationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original declaration type is a type where a property is declared. 
        ///If not defined then a property can be declared in any type..
        /// </summary>
        public static string OriginalDeclarationTypeTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("OriginalDeclarationTypeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original name.
        /// </summary>
        public static string OriginalName {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("OriginalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original namespace.
        /// </summary>
        public static string OriginalNamespace {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("OriginalNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original namespace is a namespace read from source..
        /// </summary>
        public static string OriginalNamespaceTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("OriginalNamespaceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original name is a name read from source..
        /// </summary>
        public static string OriginalNameTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("OriginalNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original property name.
        /// </summary>
        public static string OriginalPropertyName {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("OriginalPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original property namespace.
        /// </summary>
        public static string OriginalPropertyNamespace {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("OriginalPropertyNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a namespace of the type that declares the property..
        /// </summary>
        public static string OriginalPropertyNamespaceTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("OriginalPropertyNamespaceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an original property name read from source..
        /// </summary>
        public static string OriginalPropertyNameTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("OriginalPropertyNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original property type.
        /// </summary>
        public static string OriginalPropertyType {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("OriginalPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an original type that declares the property..
        /// </summary>
        public static string OriginalPropertyTypeTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("OriginalPropertyTypeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original value namespace.
        /// </summary>
        public static string OriginalPropValueNamespace {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("OriginalPropValueNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a namespace of original type of property value..
        /// </summary>
        public static string OriginalPropValueNamespaceTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("OriginalPropValueNamespaceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original value type.
        /// </summary>
        public static string OriginalPropValueType {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("OriginalPropValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an original type of property value..
        /// </summary>
        public static string OriginalPropValueTypeTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("OriginalPropValueTypeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original type name.
        /// </summary>
        public static string OriginalTypeName {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("OriginalTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other types.
        /// </summary>
        public static string OtherTypes {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("OtherTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing relationships.
        /// </summary>
        public static string OutgoingRelationships {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("OutgoingRelationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem.
        /// </summary>
        public static string Problem {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problematic types.
        /// </summary>
        public static string ProblematicTypes {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ProblematicTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process phases:.
        /// </summary>
        public static string Process_phases_ {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Process phases_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name not defined.
        /// </summary>
        public static string Project_name_not_defined {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Project_name_not_defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        public static string ProjectName {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of generated C# project.
        /// </summary>
        public static string ProjectNameTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ProjectNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Properties {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties define values assigned to the object of the class..
        /// </summary>
        public static string PropertiesTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("PropertiesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property name.
        /// </summary>
        public static string PropertyName {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("PropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property name is an original or target name of the property
        ///(depending on processing phase)..
        /// </summary>
        public static string PropertyNameTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("PropertyNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string RecordNumber {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("RecordNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of the record in the collection.
        /// </summary>
        public static string RecordNumberTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("RecordNumberTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh results.
        /// </summary>
        public static string RefreshResults {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("RefreshResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered namespaces.
        /// </summary>
        public static string RegisteredNamespaces {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("RegisteredNamespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered types.
        /// </summary>
        public static string RegisteredTypes {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("RegisteredTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected types.
        /// </summary>
        public static string RejectedTypes {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("RejectedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related type.
        /// </summary>
        public static string RelatedType {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("RelatedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationships.
        /// </summary>
        public static string Relationships {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Relationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed properties.
        /// </summary>
        public static string RemovedProperties {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("RemovedProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renamed types.
        /// </summary>
        public static string RenamedTypes {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("RenamedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result kind.
        /// </summary>
        public static string ResultKind {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ResultKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results of phase.
        /// </summary>
        public static string ResultsOfPhase {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ResultsOfPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root namespace.
        /// </summary>
        public static string RootNamespace {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("RootNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output code types will be generated into this namespace and its sub-namespace..
        /// </summary>
        public static string RootNamespaceTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("RootNamespaceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save configuration anyway?.
        /// </summary>
        public static string SaveConfigurationAnyway {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("SaveConfigurationAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save results.
        /// </summary>
        public static string SaveResults {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("SaveResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan source.
        /// </summary>
        public static string ScanSource {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ScanSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema.
        /// </summary>
        public static string Schema {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semantics.
        /// </summary>
        public static string Semantics {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Semantics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut.
        /// </summary>
        public static string Shortcut {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut error.
        /// </summary>
        public static string ShortcutError {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ShortcutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut replaces its name (if shortcuts are enabled)..
        /// </summary>
        public static string ShortcutTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ShortcutTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show accepted only.
        /// </summary>
        public static string ShowAcceptedOnly {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ShowAcceptedOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show declaring type.
        /// </summary>
        public static string ShowDeclaringType {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ShowDeclaringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show full type name.
        /// </summary>
        public static string ShowFullTypeName {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ShowFullTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show results.
        /// </summary>
        public static string ShowResults {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ShowResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show target namespaces.
        /// </summary>
        public static string ShowTargetNamespaces {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ShowTargetNamespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution name.
        /// </summary>
        public static string SolutionName {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("SolutionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of generated C# solution.
        /// </summary>
        public static string SolutionNameTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("SolutionNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structs.
        /// </summary>
        public static string Structs {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Structs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Struct types.
        /// </summary>
        public static string StructTypes {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("StructTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target shortcuts must be different in different target names..
        /// </summary>
        public static string Target_shortcut_error {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Target_shortcut_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target name.
        /// </summary>
        public static string TargetName {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("TargetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target namespace.
        /// </summary>
        public static string TargetNamespace {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("TargetNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target namespace error.
        /// </summary>
        public static string TargetNamespaceError {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("TargetNamespaceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to target namespaces only.
        /// </summary>
        public static string TargetNamespacesOnly {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("TargetNamespacesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target namespace is a namespace written to output..
        /// </summary>
        public static string TargetNamespaceTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("TargetNamespaceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target name is a name written to output..
        /// </summary>
        public static string TargetNameTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("TargetNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target property name.
        /// </summary>
        public static string TargetPropertyName {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("TargetPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target property name is a new property name written to output..
        /// </summary>
        public static string TargetPropertyNameTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("TargetPropertyNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target property type.
        /// </summary>
        public static string TargetPropertyType {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("TargetPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target property type is a type of property value written to output..
        /// </summary>
        public static string TargetPropertyTypeTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("TargetPropertyTypeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target shortcut.
        /// </summary>
        public static string TargetShortcut {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("TargetShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target shortcut error.
        /// </summary>
        public static string TargetShortcutError {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("TargetShortcutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target shortcut replaces target name (if shortcuts are enabled)..
        /// </summary>
        public static string TargetShortcutTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("TargetShortcutTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to targets only.
        /// </summary>
        public static string TargetsOnly {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("TargetsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target type.
        /// </summary>
        public static string TargetType {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("TargetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target type results from conversion phase..
        /// </summary>
        public static string TargetTypeTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("TargetTypeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type full name.
        /// </summary>
        public static string TypeFullName {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("TypeFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name preceded with namespace..
        /// </summary>
        public static string TypeFullNameTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("TypeFullNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name.
        /// </summary>
        public static string TypeName {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name pattern.
        /// </summary>
        public static string TypeNamePattern {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("TypeNamePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With type name pattern you can exclude/include many types. 
        ///Use &apos;*&apos; wildcard character to match many characters..
        /// </summary>
        public static string TypeNamePatternTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("TypeNamePatternTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name is an original or target name of the type
        ///(depending on processing phase)..
        /// </summary>
        public static string TypeNameTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("TypeNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        public static string Types {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types with added description.
        /// </summary>
        public static string TypesWithAddedDescription {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("TypesWithAddedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types with description.
        /// </summary>
        public static string TypesWithDescription {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("TypesWithDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types with meaningless description.
        /// </summary>
        public static string TypesWithMeaninglessDescription {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("TypesWithMeaninglessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types with non-unique name.
        /// </summary>
        public static string TypesWithNonUniqueName {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("TypesWithNonUniqueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types without description.
        /// </summary>
        public static string TypesWithoutDescription {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("TypesWithoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types with same name.
        /// </summary>
        public static string TypesWithSameName {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("TypesWithSameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type to scan.
        /// </summary>
        public static string TypeToScan {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("TypeToScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the main type where scan begins. Its property types and item types are scanned next..
        /// </summary>
        public static string TypeToScanTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("TypeToScanTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregistered namespace {0}.
        /// </summary>
        public static string UnregisteredNamespace {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("UnregisteredNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate conversion.
        /// </summary>
        public static string ValidateConversion {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ValidateConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate docs.
        /// </summary>
        public static string ValidateDocs {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ValidateDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validated types.
        /// </summary>
        public static string ValidatedTypes {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ValidatedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate fix.
        /// </summary>
        public static string ValidateFix {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ValidateFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate generation.
        /// </summary>
        public static string ValidateGeneration {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ValidateGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate names.
        /// </summary>
        public static string ValidateNames {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ValidateNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate scan.
        /// </summary>
        public static string ValidateScan {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ValidateScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation error.
        /// </summary>
        public static string ValidationError {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid types.
        /// </summary>
        public static string ValidTypes {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ValidTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value type.
        /// </summary>
        public static string ValueType {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value type is declared type of property value..
        /// </summary>
        public static string ValueTypeTooltip {
           [DebuggerStepThrough] get {
                return ResourceManager.GetString("ValueTypeTooltip", resourceCulture);
            }
        }
    }
}
