//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelGenApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModelGenApp.CommonStrings", typeof(CommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted types.
        /// </summary>
        public static string AcceptedTypes {
            get {
                return ResourceManager.GetString("AcceptedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add docs.
        /// </summary>
        public static string AddDocs {
            get {
                return ResourceManager.GetString("AddDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All types.
        /// </summary>
        public static string AllTypes {
            get {
                return ResourceManager.GetString("AllTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        public static string Classes {
            get {
                return ResourceManager.GetString("Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config property name.
        /// </summary>
        public static string Config_property_name {
            get {
                return ResourceManager.GetString("Config_property_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config property name is declared name of the property. 
        ///Can contain * as a wildcard..
        /// </summary>
        public static string Config_property_name_tooltip {
            get {
                return ResourceManager.GetString("Config_property_name_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated shortcut.
        /// </summary>
        public static string Duplicated_shortcut {
            get {
                return ResourceManager.GetString("Duplicated shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum types.
        /// </summary>
        public static string EnumTypes {
            get {
                return ResourceManager.GetString("EnumTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded.
        /// </summary>
        public static string Excluded_namespace {
            get {
                return ResourceManager.GetString("Excluded_namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded namespace is rejected from scanning..
        /// </summary>
        public static string Excluded_namespace_tooltip {
            get {
                return ResourceManager.GetString("Excluded_namespace_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded property.
        /// </summary>
        public static string Excluded_property {
            get {
                return ResourceManager.GetString("Excluded_property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded property is rejected even if its type is accepted..
        /// </summary>
        public static string Excluded_property_tooltip {
            get {
                return ResourceManager.GetString("Excluded_property_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded type.
        /// </summary>
        public static string Excluded_type {
            get {
                return ResourceManager.GetString("Excluded_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded type is rejected even if its namespace is included..
        /// </summary>
        public static string Excluded_type_tooltip {
            get {
                return ResourceManager.GetString("Excluded_type_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with docs.
        /// </summary>
        public static string FileWithDocs {
            get {
                return ResourceManager.GetString("FileWithDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is XML file with types and properties descriptions. 
        ///It should be prepared by an external tool..
        /// </summary>
        public static string FileWithDocsTooltip {
            get {
                return ResourceManager.GetString("FileWithDocsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use or omit adding docs from file..
        /// </summary>
        public static string FileWithDocsUseTooltip {
            get {
                return ResourceManager.GetString("FileWithDocsUseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIlter results.
        /// </summary>
        public static string Filter_results {
            get {
                return ResourceManager.GetString("Filter_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included type.
        /// </summary>
        public static string Included_type {
            get {
                return ResourceManager.GetString("Included_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included type is accepted even if its namespaces is excluded..
        /// </summary>
        public static string Included_type_tooltip {
            get {
                return ResourceManager.GetString("Included_type_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interfaces.
        /// </summary>
        public static string Interfaces {
            get {
                return ResourceManager.GetString("Interfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document model generator.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meaningless description.
        /// </summary>
        public static string MeaninglessDescription {
            get {
                return ResourceManager.GetString("MeaninglessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing description.
        /// </summary>
        public static string MissingDescription {
            get {
                return ResourceManager.GetString("MissingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model configuration.
        /// </summary>
        public static string Model_configuration {
            get {
                return ResourceManager.GetString("Model_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model configuration is invalid. See marks in the table..
        /// </summary>
        public static string Model_configuration_is_invalid {
            get {
                return ResourceManager.GetString("Model_configuration_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model configuration reloaded from {0}.
        /// </summary>
        public static string Model_configuration_reloaded_from_0 {
            get {
                return ResourceManager.GetString("Model_configuration_reloaded_from_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model configuration saved in {0}.
        /// </summary>
        public static string Model_configuration_saved_in_0 {
            get {
                return ResourceManager.GetString("Model configuration saved in 0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner namespace hase multiple types with the same name..
        /// </summary>
        public static string MultiplicatedName {
            get {
                return ResourceManager.GetString("MultiplicatedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace.
        /// </summary>
        public static string Namespace {
            get {
                return ResourceManager.GetString("Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespaces.
        /// </summary>
        public static string Namespaces {
            get {
                return ResourceManager.GetString("Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No error.
        /// </summary>
        public static string NoError {
            get {
                return ResourceManager.GetString("NoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original declaration type.
        /// </summary>
        public static string Original_declaration_type {
            get {
                return ResourceManager.GetString("Original_declaration_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original declaration type is a type where a property is declared. 
        ///If not defined then a property can be declared in any type..
        /// </summary>
        public static string Original_declaration_type_tooltip {
            get {
                return ResourceManager.GetString("Original_declaration_type_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original name.
        /// </summary>
        public static string Original_name {
            get {
                return ResourceManager.GetString("Original_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original name is a name read from source..
        /// </summary>
        public static string Original_name_tooltip {
            get {
                return ResourceManager.GetString("Original_name_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original namespace.
        /// </summary>
        public static string Original_namespace {
            get {
                return ResourceManager.GetString("Original_namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original namespace is a namespace read from source..
        /// </summary>
        public static string Original_namespace_tooltip {
            get {
                return ResourceManager.GetString("Original_namespace_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other types.
        /// </summary>
        public static string OtherTypes {
            get {
                return ResourceManager.GetString("OtherTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process phases:.
        /// </summary>
        public static string Process_phases_ {
            get {
                return ResourceManager.GetString("Process phases_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered types.
        /// </summary>
        public static string RegisteredTypes {
            get {
                return ResourceManager.GetString("RegisteredTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected types.
        /// </summary>
        public static string RejectedTypes {
            get {
                return ResourceManager.GetString("RejectedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result kind.
        /// </summary>
        public static string Result_kind {
            get {
                return ResourceManager.GetString("Result_kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save results.
        /// </summary>
        public static string SaveResults {
            get {
                return ResourceManager.GetString("SaveResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan source.
        /// </summary>
        public static string ScanSource {
            get {
                return ResourceManager.GetString("ScanSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut.
        /// </summary>
        public static string Shortcut {
            get {
                return ResourceManager.GetString("Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut replaces its name (if shortcuts are enabled)..
        /// </summary>
        public static string Shortcut_tooltip {
            get {
                return ResourceManager.GetString("Shortcut_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show results.
        /// </summary>
        public static string ShowResults {
            get {
                return ResourceManager.GetString("ShowResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Struct types.
        /// </summary>
        public static string StructTypes {
            get {
                return ResourceManager.GetString("StructTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target name.
        /// </summary>
        public static string Target_name {
            get {
                return ResourceManager.GetString("Target_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target name is a name written to output..
        /// </summary>
        public static string Target_name_tooltip {
            get {
                return ResourceManager.GetString("Target_name_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target namespace.
        /// </summary>
        public static string Target_namespace {
            get {
                return ResourceManager.GetString("Target_namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target namespace is a namespace written to output..
        /// </summary>
        public static string Target_namespace_tooltip {
            get {
                return ResourceManager.GetString("Target_namespace_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target property type.
        /// </summary>
        public static string Target_property_type {
            get {
                return ResourceManager.GetString("Target_property_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target property type is a type of property value written to output..
        /// </summary>
        public static string Target_property_type_tooltip {
            get {
                return ResourceManager.GetString("Target_property_type_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target shortcut.
        /// </summary>
        public static string Target_shortcut {
            get {
                return ResourceManager.GetString("Target_shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target shortcuts must be different in different target names..
        /// </summary>
        public static string Target_shortcut_error {
            get {
                return ResourceManager.GetString("Target_shortcut_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target shortcut replaces target name (if shortcuts are enabled)..
        /// </summary>
        public static string Target_shortcut_tooltip {
            get {
                return ResourceManager.GetString("Target_shortcut_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type to scan.
        /// </summary>
        public static string Type_to_scan {
            get {
                return ResourceManager.GetString("Type_to_scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the main type where scan begins. Its property types and item types are scanned next..
        /// </summary>
        public static string Type_to_scan_tooltip {
            get {
                return ResourceManager.GetString("Type to scan tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        public static string Types {
            get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
    }
}
