//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelGenApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModelGenApp.CommonStrings", typeof(CommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add docs.
        /// </summary>
        public static string AddDocs {
            get {
                return ResourceManager.GetString("AddDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config property name.
        /// </summary>
        public static string ConfigPropertyName {
            get {
                return ResourceManager.GetString("ConfigPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config property name is declared name of the property. 
        ///Can contain * as a wildcard..
        /// </summary>
        public static string ConfigPropertyNameTooltip {
            get {
                return ResourceManager.GetString("ConfigPropertyNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded.
        /// </summary>
        public static string ExcludedNamespace {
            get {
                return ResourceManager.GetString("ExcludedNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded namespace is rejected from scanning..
        /// </summary>
        public static string ExcludedNamespaceTooltip {
            get {
                return ResourceManager.GetString("ExcludedNamespaceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded property.
        /// </summary>
        public static string ExcludedProperty {
            get {
                return ResourceManager.GetString("ExcludedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded property is rejected even if its type is accepted..
        /// </summary>
        public static string ExcludedPropertyTooltip {
            get {
                return ResourceManager.GetString("ExcludedPropertyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded type.
        /// </summary>
        public static string ExcludedType {
            get {
                return ResourceManager.GetString("ExcludedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded type is rejected even if its namespace is included..
        /// </summary>
        public static string ExcludedTypeTooltip {
            get {
                return ResourceManager.GetString("ExcludedTypeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with docs.
        /// </summary>
        public static string FileWithDocs {
            get {
                return ResourceManager.GetString("FileWithDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is XML file with types and properties descriptions. 
        ///It should be prepared by an external tool..
        /// </summary>
        public static string FileWithDocsTooltip {
            get {
                return ResourceManager.GetString("FileWithDocsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use or omit adding docs from file..
        /// </summary>
        public static string FileWithDocsUseTooltip {
            get {
                return ResourceManager.GetString("FileWithDocsUseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included type.
        /// </summary>
        public static string IncludedType {
            get {
                return ResourceManager.GetString("IncludedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included type is accepted even if its namespaces is excluded..
        /// </summary>
        public static string IncludedTypeTooltip {
            get {
                return ResourceManager.GetString("IncludedTypeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document model generator.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meaningless description.
        /// </summary>
        public static string MeaninglessDescription {
            get {
                return ResourceManager.GetString("MeaninglessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing description.
        /// </summary>
        public static string MissingDescription {
            get {
                return ResourceManager.GetString("MissingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model configuration.
        /// </summary>
        public static string ModelConfiguration {
            get {
                return ResourceManager.GetString("ModelConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model configuration is invalid. See marks in the table..
        /// </summary>
        public static string ModelConfigurationIsInvalid {
            get {
                return ResourceManager.GetString("ModelConfigurationIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model configuration reloaded from {0}.
        /// </summary>
        public static string ModelConfigurationReloadedFrom_1 {
            get {
                return ResourceManager.GetString("ModelConfigurationReloadedFrom_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model configuration saved in {0}.
        /// </summary>
        public static string ModelConfigurationSaved_1 {
            get {
                return ResourceManager.GetString("ModelConfigurationSaved_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner namespace hase multiple types with the same name..
        /// </summary>
        public static string MultiplicatedName {
            get {
                return ResourceManager.GetString("MultiplicatedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespaces.
        /// </summary>
        public static string Namespaces {
            get {
                return ResourceManager.GetString("Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No error.
        /// </summary>
        public static string NoError {
            get {
                return ResourceManager.GetString("NoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original declaration type.
        /// </summary>
        public static string OriginalDeclarationType {
            get {
                return ResourceManager.GetString("OriginalDeclarationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original declaration type is a type where a property is declared. 
        ///If not defined then a property can be declared in any type..
        /// </summary>
        public static string OriginalDeclarationTypeTooltip {
            get {
                return ResourceManager.GetString("OriginalDeclarationTypeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original name.
        /// </summary>
        public static string OriginalName {
            get {
                return ResourceManager.GetString("OriginalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original namespace.
        /// </summary>
        public static string OriginalNamespace {
            get {
                return ResourceManager.GetString("OriginalNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original namespace is a namespace read from source..
        /// </summary>
        public static string OriginalNamespaceTooltip {
            get {
                return ResourceManager.GetString("OriginalNamespaceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original name is a name read from source..
        /// </summary>
        public static string OriginalNameTooltip {
            get {
                return ResourceManager.GetString("OriginalNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process phases:.
        /// </summary>
        public static string ProcessPhases_ {
            get {
                return ResourceManager.GetString("ProcessPhases_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save results.
        /// </summary>
        public static string SaveResults {
            get {
                return ResourceManager.GetString("SaveResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan source.
        /// </summary>
        public static string ScanSource {
            get {
                return ResourceManager.GetString("ScanSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut.
        /// </summary>
        public static string Shortcut {
            get {
                return ResourceManager.GetString("Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated shortcut.
        /// </summary>
        public static string ShortcutErrorMsg {
            get {
                return ResourceManager.GetString("ShortcutErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut replaces its name (if shortcuts are enabled)..
        /// </summary>
        public static string ShortcutTooltip {
            get {
                return ResourceManager.GetString("ShortcutTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show results.
        /// </summary>
        public static string ShowResults {
            get {
                return ResourceManager.GetString("ShowResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target name.
        /// </summary>
        public static string TargetName {
            get {
                return ResourceManager.GetString("TargetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target namespace.
        /// </summary>
        public static string TargetNamespace {
            get {
                return ResourceManager.GetString("TargetNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target namespace is a namespace written to output..
        /// </summary>
        public static string TargetNamespaceTooltip {
            get {
                return ResourceManager.GetString("TargetNamespaceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target name is a name written to output..
        /// </summary>
        public static string TargetNameTooltip {
            get {
                return ResourceManager.GetString("TargetNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target property type.
        /// </summary>
        public static string TargetPropertyType {
            get {
                return ResourceManager.GetString("TargetPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target property type is a type of property value written to output..
        /// </summary>
        public static string TargetPropertyTypeTooltip {
            get {
                return ResourceManager.GetString("TargetPropertyTypeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target shortcut.
        /// </summary>
        public static string TargetShortcut {
            get {
                return ResourceManager.GetString("TargetShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target shortcuts must be different in different target names..
        /// </summary>
        public static string TargetShortcutErrorMsg {
            get {
                return ResourceManager.GetString("TargetShortcutErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target shortcut replaces target name (if shortcuts are enabled)..
        /// </summary>
        public static string TargetShortcutTooltip {
            get {
                return ResourceManager.GetString("TargetShortcutTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        public static string Types {
            get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type to scan.
        /// </summary>
        public static string TypeToScan {
            get {
                return ResourceManager.GetString("TypeToScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the main type where scan begins. Its property types and item types are scanned next..
        /// </summary>
        public static string TypeToScanTooltip {
            get {
                return ResourceManager.GetString("TypeToScanTooltip", resourceCulture);
            }
        }
    }
}
