global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.Collections.Specialized;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Text;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Input;
global using System.Windows.Threading;
global using System.CodeDom.Compiler;
global using System.Xml;

global using Qhta.Collections;
global using Qhta.MVVM;
global using Qhta.DispatchedObjects;
global using Qhta.TextUtils;
global using Qhta.TypeUtils;
global using Qhta.Xml.Serialization;

global using ModelGenDataConfig;
global using ModelGen;
global using ModelGenApp.Commands;
global using ModelGenApp.Helpers;
global using ModelGenApp.ViewModels;
global using ModelGenApp.Views;
global using TypeInfo = ModelGen.TypeInfo;
