//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelGen {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModelGen.CommonStrings", typeof(CommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted types.
        /// </summary>
        internal static string AcceptedTypes {
            get {
                return ResourceManager.GetString("AcceptedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add docs.
        /// </summary>
        internal static string AddDocs {
            get {
                return ResourceManager.GetString("AddDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adding docs to {0} of {1} types, added to {2} types.
        /// </summary>
        internal static string adding_docs_0_of_1_types_added_to_2_types {
            get {
                return ResourceManager.GetString("adding_docs_0_of_1_types_added_to_2_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All types.
        /// </summary>
        internal static string AllTypes {
            get {
                return ResourceManager.GetString("AllTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked types.
        /// </summary>
        internal static string CheckedTypes {
            get {
                return ResourceManager.GetString("CheckedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted types.
        /// </summary>
        internal static string ConvertedTypes {
            get {
                return ResourceManager.GetString("ConvertedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to converting {0} of {1} types, converted {2} types.
        /// </summary>
        internal static string converting_0_of_1_types_converted_2_types {
            get {
                return ResourceManager.GetString("converting_0_of_1_types_converted_2_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert types.
        /// </summary>
        internal static string ConvertTypes {
            get {
                return ResourceManager.GetString("ConvertTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of phase {0}.
        /// </summary>
        internal static string End_of_phase_0 {
            get {
                return ResourceManager.GetString("End_of_phase_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in {0} namespaces.
        /// </summary>
        internal static string in_0_namespaces {
            get {
                return ResourceManager.GetString("in_0_namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidTypes.
        /// </summary>
        internal static string InvalidTypes {
            get {
                return ResourceManager.GetString("InvalidTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registered {0} of {1} types in {2} namespaces.
        /// </summary>
        internal static string registered_0_of_1_types_in_2_namespaces {
            get {
                return ResourceManager.GetString("registered_0_of_1_types_in_2_namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registed types.
        /// </summary>
        internal static string RegisteredTypes {
            get {
                return ResourceManager.GetString("RegisteredTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected types.
        /// </summary>
        internal static string RejectedTypes {
            get {
                return ResourceManager.GetString("RejectedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renamed types.
        /// </summary>
        internal static string RenamedTypes {
            get {
                return ResourceManager.GetString("RenamedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename types.
        /// </summary>
        internal static string RenameTypes {
            get {
                return ResourceManager.GetString("RenameTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to renaming {0} of {1} types, renamed {2} types.
        /// </summary>
        internal static string renaming_0_of_1_types_renamed_2_types {
            get {
                return ResourceManager.GetString("renaming_0_of_1_types_renamed_2_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned {0} namespaces.
        /// </summary>
        internal static string Scanned_0_Namespaces {
            get {
                return ResourceManager.GetString("Scanned_0_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan source.
        /// </summary>
        internal static string ScanSource {
            get {
                return ResourceManager.GetString("ScanSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of phase {0}.
        /// </summary>
        internal static string Start_of_phase_0 {
            get {
                return ResourceManager.GetString("Start_of_phase_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start processing:\n{0}.
        /// </summary>
        internal static string StartProcessing_0 {
            get {
                return ResourceManager.GetString("StartProcessing_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time:.
        /// </summary>
        internal static string time_ {
            get {
                return ResourceManager.GetString("time_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types with added description.
        /// </summary>
        internal static string TypesWithAddedDescription {
            get {
                return ResourceManager.GetString("TypesWithAddedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types with description.
        /// </summary>
        internal static string TypesWithDescription {
            get {
                return ResourceManager.GetString("TypesWithDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types with meaningless description.
        /// </summary>
        internal static string TypesWithMeaninglessDescription {
            get {
                return ResourceManager.GetString("TypesWithMeaninglessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types without description.
        /// </summary>
        internal static string TypesWithoutDescription {
            get {
                return ResourceManager.GetString("TypesWithoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types with same name.
        /// </summary>
        internal static string TypesWithSameName {
            get {
                return ResourceManager.GetString("TypesWithSameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid types.
        /// </summary>
        internal static string ValidTypes {
            get {
                return ResourceManager.GetString("ValidTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verifying {0} of {1} types, invalid {2} types.
        /// </summary>
        internal static string verifying_0_of_1_types_invalid_2_types {
            get {
                return ResourceManager.GetString("verifying_0_of_1_types_invalid_2_types", resourceCulture);
            }
        }
    }
}
