using System.Diagnostics;

using DocumentFormat.OpenXml.Drawing.Diagrams;

using DocumentModel;

using Qhta.Collections;

namespace ModelGen;

public static class ModelData
{

  #region Namespaces

  public static SortedStrings IncludedNamespaces { get; } = new SortedStrings
  {
    "DocumentFormat.OpenXml.Wordprocesing"
  };

  public static SortedStrings ExcludedNamespaces { get; } = new SortedStrings
  {
    "DocumentFormat.OpenXml",
    "*Metadata", "*Features", "*Framework", "*Framework.Schema", "*Validation", "*Validation.Schema", 
    "*Presentation*",
    "*Spreadsheet*",
    "*Excel*",
    "*PowerPoint*",
    "*.Office.Word",
    "*.VariantTypes",
    "DocumentFormat.OpenXml.Vml.Presentation",
    "DocumentFormat.OpenXml.Vml.Spreadsheet",
  };

  public static BiDiDictionary<string, string> Namespaces { get; } = new BiDiDictionary<string, string>()
  {
    { "oo", "DocumentFormat.OpenXml" },
    { "ac", "DocumentFormat.OpenXml.AdditionalCharacteristics" },
    { "bib", "DocumentFormat.OpenXml.Bibliography" },
    { "cp", "DocumentFormat.OpenXml.CustomProperties" },
    { "cxdatpr", "DocumentFormat.OpenXml.CustomXmlDataProperties" },
    { "cxschpr", "DocumentFormat.OpenXml.CustomXmlSchemaReferences" },
    { "dr", "DocumentFormat.OpenXml.Drawings" },
    { "chrtdr", "DocumentFormat.OpenXml.Drawing.ChartDrawing" },
    { "chrt", "DocumentFormat.OpenXml.Drawing.Charts" },
    { "dgk", "DocumentFormat.OpenXml.Drawing.Diagrams" },
    { "drlc", "DocumentFormat.OpenXml.Drawing.LegacyCompatibility" },
    { "drc", "DocumentFormat.OpenXml.Drawing.LockedCanvas" },
    { "pic", "DocumentFormat.OpenXml.Drawing.Pictures" },
    { "drs", "DocumentFormat.OpenXml.Drawing.Spreadsheet" },
    { "drw", "DocumentFormat.OpenXml.Drawing.Wordprocessing" },
    { "em", "DocumentFormat.OpenXml.EMMA" },
    { "xp", "DocumentFormat.OpenXml.ExtendedProperties" },
    { "feat", "DocumentFormat.OpenXml.Features" },
    { "fw", "DocumentFormat.OpenXml.Framework" },
    { "fwm", "DocumentFormat.OpenXml.Framework.Metadata" },
    { "fws", "DocumentFormat.OpenXml.Framework.Schema" },
    { "ink", "DocumentFormat.OpenXml.InkML" },
    { "m", "DocumentFormat.OpenXml.Math" },
    { "oax", "DocumentFormat.OpenXml.Office.ActiveX" },
    { "oct", "DocumentFormat.OpenXml.Office.ContentType" },
    { "ocpp", "DocumentFormat.OpenXml.Office.CoverPageProps" },
    { "ocdip", "DocumentFormat.OpenXml.Office.CustomDocumentInformationPanel" },
    { "oui", "DocumentFormat.OpenXml.Office.CustomUI" },
    { "ocxsn", "DocumentFormat.OpenXml.Office.CustomXsn" },
    { "odr", "DocumentFormat.OpenXml.Office.Drawings" },
    { "odr21e", "DocumentFormat.OpenXml.Office.Drawing.Y2021.OEmbed" },
    { "odr21s", "DocumentFormat.OpenXml.Office.Drawing.Y2021.ScriptLink" },
    { "ox", "DocumentFormat.OpenXml.Office.Excel" },
    { "olp", "DocumentFormat.OpenXml.Office.LongProperties" },
    { "oma", "DocumentFormat.OpenXml.Office.MetaAttributes" },
    { "op21", "DocumentFormat.OpenXml.Office.PowerPoint.Y2021.M06.Main" },
    { "os21", "DocumentFormat.OpenXml.Office.SpreadSheetML.Y2021.ExtLinks2021" },
    { "os22", "DocumentFormat.OpenXml.Office.SpreadSheetML.Y2022.PivotVersionInfo" },
    { "ow", "DocumentFormat.OpenXml.Office.Word" },
    { "ow20e", "DocumentFormat.OpenXml.Office.Word.Y2020.OEmbed" },
    { "o10ui", "DocumentFormat.OpenXml.Office2010.CustomUI" },
    { "o10dr", "DocumentFormat.OpenXml.Office2010.Drawings" },
    { "o10chrtdr", "DocumentFormat.OpenXml.Office2010.Drawing.ChartDrawing" },
    { "o10chrt", "DocumentFormat.OpenXml.Office2010.Drawing.Charts" },
    { "o10dgm", "DocumentFormat.OpenXml.Office2010.Drawing.Diagram" },
    { "o10drlc", "DocumentFormat.OpenXml.Office2010.Drawing.LegacyCompatibility" },
    { "o10pic", "DocumentFormat.OpenXml.Office2010.Drawing.Pictures" },
    { "o10slc", "DocumentFormat.OpenXml.Office2010.Drawing.Slicer" },
    { "o10x", "DocumentFormat.OpenXml.Office2010.Excel" },
    { "o10xdr", "DocumentFormat.OpenXml.Office2010.Excel.Drawings" },
    { "o10xac", "DocumentFormat.OpenXml.Office2010.ExcelAc" },
    { "o10ink", "DocumentFormat.OpenXml.Office2010.Ink" },
    { "o10p", "DocumentFormat.OpenXml.Office2010.PowerPoint" },
    { "o10w", "DocumentFormat.OpenXml.Office2010.Word" },
    { "o10wdr", "DocumentFormat.OpenXml.Office2010.Word.Drawings" },
    { "o10wdc", "DocumentFormat.OpenXml.Office2010.Word.DrawingCanvas" },
    { "o10drg", "DocumentFormat.OpenXml.Office2010.Word.DrawingGroup" },
    { "o10drs", "DocumentFormat.OpenXml.Office2010.Word.DrawingShape" },
    { "o13dr", "DocumentFormat.OpenXml.Office2013.Drawings" },
    { "o13drchrt", "DocumentFormat.OpenXml.Office2013.Drawing.Chart" },
    { "o13drchrts", "DocumentFormat.OpenXml.Office2013.Drawing.ChartStyle" },
    { "o13tslc", "DocumentFormat.OpenXml.Office2013.Drawing.TimeSlicer" },
    { "o13x", "DocumentFormat.OpenXml.Office2013.Excel" },
    { "o13xac", "DocumentFormat.OpenXml.Office2013.ExcelAc" },
    { "o13p", "DocumentFormat.OpenXml.Office2013.PowerPoint" },
    { "o13pr", "DocumentFormat.OpenXml.Office2013.PowerPoint.Roaming" },
    { "o13th", "DocumentFormat.OpenXml.Office2013.Theme" },
    { "o13wx", "DocumentFormat.OpenXml.Office2013.WebExtension" },
    { "o13wxp", "DocumentFormat.OpenXml.Office2013.WebExtentionPane" },
    { "o13w", "DocumentFormat.OpenXml.Office2013.Word" },
    { "o13wdr", "DocumentFormat.OpenXml.Office2013.Word.Drawings" },
    { "o16dr", "DocumentFormat.OpenXml.Office2016.Drawings" },
    { "o16chrtdr", "DocumentFormat.OpenXml.Office2016.Drawing.ChartDrawing" },
    { "o16chrt", "DocumentFormat.OpenXml.Office2016.Drawing.Charts" },
    { "o16chrtac", "DocumentFormat.OpenXml.Office2016.Drawing.ChartsAc" },
    { "o16drcmd", "DocumentFormat.OpenXml.Office2016.Drawing.Command" },
    { "o16x", "DocumentFormat.OpenXml.Office2016.Excel" },
    { "o16xac", "DocumentFormat.OpenXml.Office2016.ExcelAc" },
    { "o16p", "DocumentFormat.OpenXml.Office2016.Presentation" },
    { "o16pcmd", "DocumentFormat.OpenXml.Office2016.Presentation.Command" },
    { "o16", "DocumentFormat.OpenXml.Office2016.Word.Symex" },
    { "o19dr", "DocumentFormat.OpenXml.Office2019.Drawings" },
    { "o19dran", "DocumentFormat.OpenXml.Office2019.Drawing.Animation" },
    { "o19dran3d", "DocumentFormat.OpenXml.Office2019.Drawing.Animation.Model3D" },
    { "o19drchrt", "DocumentFormat.OpenXml.Office2019.Drawing.Chart" },
    { "o19dgm1", "DocumentFormat.OpenXml.Office2019.Drawing.Diagram11" },
    { "O19dgm2", "DocumentFormat.OpenXml.Office2019.Drawing.Diagram12" },
    { "o19hlc", "DocumentFormat.OpenXml.Office2019.Drawing.HyperLinkColor" },
    { "o19ink", "DocumentFormat.OpenXml.Office2019.Drawing.Ink" },
    { "o19dr3d", "DocumentFormat.OpenXml.Office2019.Drawing.Model3D" },
    { "o19svg", "DocumentFormat.OpenXml.Office2019.Drawing.SVG" },
    { "o19xcf", "DocumentFormat.OpenXml.Office2019.Excel.CalcFeatures" },
    { "o10xda", "DocumentFormat.OpenXml.Office2019.Excel.DynamicArray" },
    { "o19xpdl", "DocumentFormat.OpenXml.Office2019.Excel.PivotDefaultLayout" },
    { "o19xrd", "DocumentFormat.OpenXml.Office2019.Excel.RichData" },
    { "o19xrd2", "DocumentFormat.OpenXml.Office2019.Excel.RichData2" },
    { "o19xtc", "DocumentFormat.OpenXml.Office2019.Excel.ThreadedComments" },
    { "o19p", "DocumentFormat.OpenXml.Office2019.Presentation" },
    { "o19wcid", "DocumentFormat.OpenXml.Office2019.Word.Cid" },
    { "o21dt", "DocumentFormat.OpenXml.Office2021.DocumentTasks" },
    { "o23dc", "DocumentFormat.OpenXml.Office2021.Drawing.DocumentClassification" },
    { "o32lf", "DocumentFormat.OpenXml.Office2021.Drawing.Livefeed" },
    { "o23ss", "DocumentFormat.OpenXml.Office2021.Drawing.SketchyShapes" },
    { "o21xl", "DocumentFormat.OpenXml.Office2021.Excel.ExternalLinks" },
    { "o32nsv", "DocumentFormat.OpenXml.Office2021.Excel.NamedSheetViews" },
    { "o21xpvt", "DocumentFormat.OpenXml.Office2021.Excel.Pivot" },
    { "o21xrdwimg", "DocumentFormat.OpenXml.Office2021.Excel.RichDataWebImage" },
    { "o21rvrint", "DocumentFormat.OpenXml.Office2021.Excel.RichValueRefreshIntervals" },
    { "o21xtc2", "DocumentFormat.OpenXml.Office2021.Excel.ThreadedComments2" },
    { "o21mlmd", "DocumentFormat.OpenXml.Office2021.MipLabelMetaData" },
    { "o21oxl", "DocumentFormat.OpenXml.Office2021.OfficeExtLst" },
    { "o21pc", "DocumentFormat.OpenXml.Office2021.PowerPoint.Comment" },
    { "o21pd", "DocumentFormat.OpenXml.Office2021.PowerPoint.Designer" },
    { "o21pt", "DocumentFormat.OpenXml.Office2021.PowerPoint.Tasks" },
    { "o21wcx", "DocumentFormat.OpenXml.Office2021.Word.CommentsExt" },
    { "o21wxl", "DocumentFormat.OpenXml.Office2021.Word.ExtensionList" },
    { "pck", "DocumentFormat.OpenXml.Packaging" },
    { "p", "DocumentFormat.OpenXml.Presentation" },
    { "s", "DocumentFormat.OpenXml.Spreadsheet" },
    { "val", "DocumentFormat.OpenXml.Validation" },
    { "valsch", "DocumentFormat.OpenXml.Validation.Schema" },
    { "valrest", "DocumentFormat.OpenXml.Validation.Schema.Restrictions" },
    { "valsem", "DocumentFormat.OpenXml.Validation.Semantic" },
    { "vt", "DocumentFormat.OpenXml.VariantTypes" },
    { "vml", "DocumentFormat.OpenXml.Vml" },
    { "vmlo", "DocumentFormat.OpenXml.Vml.Office" },
    { "vmlp", "DocumentFormat.OpenXml.Vml.Presentation" },
    { "vmls", "DocumentFormat.OpenXml.Vml.Spreadsheet" },
    { "vmlw", "DocumentFormat.OpenXml.Vml.Wordprocessing" },
    { "w", "DocumentFormat.OpenXml.Wordprocessing" },
  };

  public static BiDiDictionary<string, string> NamespaceTranslationTable { get; } = new BiDiDictionary<string, string>()
  {
    {"DocumentFormat.OpenXml", "DocumentModel" },
    {"DocumentFormat.OpenXml.AdditionalCharacteristics", "DocumentModel" },
    {"DocumentFormat.OpenXml.Bibliography", "DocumentModel.Bibliography" },
    {"DocumentFormat.OpenXml.CustomProperties", "DocumentModel.Properties" },
    {"DocumentFormat.OpenXml.CustomXmlDataProperties", "DocumentModel.CustomXml" },
    {"DocumentFormat.OpenXml.CustomXmlSchemaReferences", "DocumentModel.CustomXml" },
    {"DocumentFormat.OpenXml.Drawing", "DocumentModel.Drawings" },
    {"DocumentFormat.OpenXml.Drawing.ChartDrawing", "DocumentModel.Drawings.ChartDrawing" },
    {"DocumentFormat.OpenXml.Drawing.Charts", "DocumentModel.Drawings.Charts" },
    {"DocumentFormat.OpenXml.Drawing.Diagrams", "DocumentModel.Drawings.Diagrams" },
    {"DocumentFormat.OpenXml.Drawing.LegacyCompatibility", "DocumentModel.Drawings.Legacy" },
    {"DocumentFormat.OpenXml.Drawing.LockedCanvas", "DocumentModel.Drawings.LockedCanvas" },
    {"DocumentFormat.OpenXml.Drawing.Pictures", "DocumentModel.Drawings.Pictures" },
    {"DocumentFormat.OpenXml.Drawing.Spreadsheet", "DocumentModel.Drawings.Spreadsheet" },
    {"DocumentFormat.OpenXml.Drawing.Wordprocessing", "DocumentModel.Drawings.Wordprocessing" },
    {"DocumentFormat.OpenXml.EMMA", "DocumentModel.EMMA" },
    {"DocumentFormat.OpenXml.ExtendedProperties", "DocumentModel.Properties" },
    {"DocumentFormat.OpenXml.Features", "DocumentModel.Framework" },
    {"DocumentFormat.OpenXml.Framework", "DocumentModel.Framework" },
    {"DocumentFormat.OpenXml.Framework.Metadata", "DocumentModel.Framework" },
    {"DocumentFormat.OpenXml.Framework.Schema", "DocumentModel.Framework" },
    {"DocumentFormat.OpenXml.InkML", "DocumentModel.Painting" },
    {"DocumentFormat.OpenXml.Math", "DocumentModel.Math" },
    {"DocumentFormat.OpenXml.Office.ActiveX", "DocumentModel.UI" },
    {"DocumentFormat.OpenXml.Office.ContentType", "DocumentModel.UI" },
    {"DocumentFormat.OpenXml.Office.CoverPageProps", "DocumentModel.UI" },
    {"DocumentFormat.OpenXml.Office.CustomDocumentInformationPanel", "DocumentModel.UI" },
    {"DocumentFormat.OpenXml.Office.CustomUI", "DocumentModel.UI" },
    {"DocumentFormat.OpenXml.Office.CustomXsn", "DocumentModel.UI" },
    {"DocumentFormat.OpenXml.Office.Drawing", "DocumentModel.Drawings.Office" },
    {"DocumentFormat.OpenXml.Office.Drawing.Y2021.OEmbed", "DocumentModel.Drawings.Office.OEmbed" },
    {"DocumentFormat.OpenXml.Office.Drawing.Y2021.ScriptLink", "DocumentModel.Drawings.Office.ScriptLink" },
    {"DocumentFormat.OpenXml.Office.Excel", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office.LongProperties", "DocumentModel" },
    {"DocumentFormat.OpenXml.Office.MetaAttributes", "DocumentModel" },
    {"DocumentFormat.OpenXml.Office.PowerPoint.Y2021.M06.Main", "DocumentModel.Presentation" },
    {"DocumentFormat.OpenXml.Office.SpreadSheetML.Y2021.ExtLinks2021", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office.SpreadSheetML.Y2022.PivotVersionInfo", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office.Word", "DocumentModel.Wordprocessing" },
    {"DocumentFormat.OpenXml.Office.Word.Y2020.OEmbed", "DocumentModel.Wordprocessing.OEmbed" },
    {"DocumentFormat.OpenXml.Office2010.CustomUI", "DocumentModel" },
    {"DocumentFormat.OpenXml.Office2010.Drawing", "DocumentModel.Drawings" },
    {"DocumentFormat.OpenXml.Office2010.Drawing.ChartDrawing", "DocumentModel.Drawings.ChartDrawings" },
    {"DocumentFormat.OpenXml.Office2010.Drawing.Charts", "DocumentModel.Drawings.Charts" },
    {"DocumentFormat.OpenXml.Office2010.Drawing.Diagram", "DocumentModel.Drawings.Diagrams" },
    {"DocumentFormat.OpenXml.Office2010.Drawing.LegacyCompatibility", "DocumentModel.Drawings.Legacy" },
    {"DocumentFormat.OpenXml.Office2010.Drawing.Pictures", "DocumentModel.Drawings.Pictures" },
    {"DocumentFormat.OpenXml.Office2010.Drawing.Slicer", "DocumentModel.Drawings.Slicer" },
    {"DocumentFormat.OpenXml.Office2010.Excel", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2010.Excel.Drawing", "DocumentModel.Drawings.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2010.ExcelAc", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2010.Ink", "DocumentModel" },
    {"DocumentFormat.OpenXml.Office2010.PowerPoint", "DocumentModel.Presentation" },
    {"DocumentFormat.OpenXml.Office2010.Word", "DocumentModel.Wordprocessing" },
    {"DocumentFormat.OpenXml.Office2010.Word.Drawing", "DocumentModel.Wordprocessing.Drawings" },
    {"DocumentFormat.OpenXml.Office2010.Word.DrawingCanvas", "DocumentModel.Wordprocessing.DrawingCanvas" },
    {"DocumentFormat.OpenXml.Office2010.Word.DrawingGroup", "DocumentModel.Wordprocessing.DrawingGroup" },
    {"DocumentFormat.OpenXml.Office2010.Word.DrawingShape", "DocumentModel.Wordprocessing.DrawingShape" },
    {"DocumentFormat.OpenXml.Office2013.Drawing", "DocumentModel.Drawings" },
    {"DocumentFormat.OpenXml.Office2013.Drawing.Chart", "DocumentModel.Drawings.Charts" },
    {"DocumentFormat.OpenXml.Office2013.Drawing.ChartStyle", "DocumentModel.Drawings.ChartsStyle" },
    {"DocumentFormat.OpenXml.Office2013.Drawing.TimeSlicer", "DocumentModel.Drawings" },
    {"DocumentFormat.OpenXml.Office2013.Excel", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2013.ExcelAc", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2013.PowerPoint", "DocumentModel.Presentation" },
    {"DocumentFormat.OpenXml.Office2013.PowerPoint.Roaming", "DocumentModel.Presentation" },
    {"DocumentFormat.OpenXml.Office2013.Theme", "DocumentModel" },
    {"DocumentFormat.OpenXml.Office2013.WebExtension", "DocumentModel.WebExtensions" },
    {"DocumentFormat.OpenXml.Office2013.WebExtentionPane", "DocumentModel.WebExtensions.UI" },
    {"DocumentFormat.OpenXml.Office2013.Word", "DocumentModel.Wordprocessing" },
    {"DocumentFormat.OpenXml.Office2013.Word.Drawing", "DocumentModel.Drawings.Wordprocessing" },
    {"DocumentFormat.OpenXml.Office2016.Drawing", "DocumentModel.Drawings" },
    {"DocumentFormat.OpenXml.Office2016.Drawing.ChartDrawing", "DocumentModel.Drawings.ChartDrawings" },
    {"DocumentFormat.OpenXml.Office2016.Drawing.Charts", "DocumentModel.Drawings.Charts" },
    {"DocumentFormat.OpenXml.Office2016.Drawing.ChartsAc", "DocumentModel.Drawings.Charts" },
    {"DocumentFormat.OpenXml.Office2016.Drawing.Command", "DocumentModel.Drawings" },
    {"DocumentFormat.OpenXml.Office2016.Excel", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2016.ExcelAc", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2016.Presentation", "DocumentModel.Presentation" },
    {"DocumentFormat.OpenXml.Office2016.Presentation.Command", "DocumentModel.Presentation" },
    {"DocumentFormat.OpenXml.Office2016.Word.Symex", "DocumentModel.Wordprocessing" },
    {"DocumentFormat.OpenXml.Office2019.Drawing", "DocumentModel.Drawings" },
    {"DocumentFormat.OpenXml.Office2019.Drawing.Animation", "DocumentModel.Drawings.Animation" },
    {"DocumentFormat.OpenXml.Office2019.Drawing.Animation.Model3D", "DocumentModel.Drawings.Animation.Model3D" },
    {"DocumentFormat.OpenXml.Office2019.Drawing.Chart", "DocumentModel.Drawings.Charts" },
    {"DocumentFormat.OpenXml.Office2019.Drawing.Diagram11", "DocumentModel.Drawings.Diagram1" },
    {"DocumentFormat.OpenXml.Office2019.Drawing.Diagram12", "DocumentModel.Drawings.Diagram2" },
    {"DocumentFormat.OpenXml.Office2019.Drawing.HyperLinkColor", "DocumentModel.Drawings" },
    {"DocumentFormat.OpenXml.Office2019.Drawing.Ink", "DocumentModel.Drawings" },
    {"DocumentFormat.OpenXml.Office2019.Drawing.Model3D", "DocumentModel.Drawings.Model3D" },
    {"DocumentFormat.OpenXml.Office2019.Drawing.SVG", "DocumentModel.Drawings.SVG" },
    {"DocumentFormat.OpenXml.Office2019.Excel.CalcFeatures", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2019.Excel.DynamicArray", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2019.Excel.PivotDefaultLayout", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2019.Excel.RichData", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2019.Excel.RichData2", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2019.Excel.ThreadedComments", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2019.Presentation", "DocumentModel.Presentation" },
    {"DocumentFormat.OpenXml.Office2019.Word.Cid", "DocumentModel.Wordprocessing" },
    {"DocumentFormat.OpenXml.Office2021.DocumentTasks", "DocumentModel" },
    {"DocumentFormat.OpenXml.Office2021.Drawing.DocumentClassification", "DocumentModel.Drawings" },
    {"DocumentFormat.OpenXml.Office2021.Drawing.Livefeed", "DocumentModel.Drawings" },
    {"DocumentFormat.OpenXml.Office2021.Drawing.SketchyShapes", "DocumentModel.Drawings" },
    {"DocumentFormat.OpenXml.Office2021.Excel.ExternalLinks", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2021.Excel.NamedSheetViews", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2021.Excel.Pivot", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2021.Excel.RichDataWebImage", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2021.Excel.RichValueRefreshIntervals", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2021.Excel.ThreadedComments2", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2021.MipLabelMetaData", "DocumentModel" },
    {"DocumentFormat.OpenXml.Office2021.OfficeExtLst", "DocumentModel" },
    {"DocumentFormat.OpenXml.Office2021.PowerPoint.Comment", "DocumentModel.Presentation" },
    {"DocumentFormat.OpenXml.Office2021.PowerPoint.Designer", "DocumentModel.Presentation" },
    {"DocumentFormat.OpenXml.Office2021.PowerPoint.Tasks", "DocumentModel.Presentation" },
    {"DocumentFormat.OpenXml.Office2021.Word.CommentsExt", "DocumentModel.Wordprocessing" },
    {"DocumentFormat.OpenXml.Office2021.Word.ExtensionList", "DocumentModel.Wordprocessing" },
    {"DocumentFormat.OpenXml.Packaging", "DocumentModel.Packaging" },
    {"DocumentFormat.OpenXml.Presentation", "DocumentModel.Presentation" },
    {"DocumentFormat.OpenXml.Spreadsheet", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Validation", "DocumentModel.Validation" },
    {"DocumentFormat.OpenXml.Validation.Schema", "DocumentModel.Validation" },
    {"DocumentFormat.OpenXml.Validation.Schema.Restrictions", "DocumentModel.Validation" },
    {"DocumentFormat.OpenXml.Validation.Semantic", "DocumentModel.Validation" },
    {"DocumentFormat.OpenXml.VariantTypes", "DocumentModel.VariantTypes" },
    {"DocumentFormat.OpenXml.Vml", "DocumentModel.Vml" },
    {"DocumentFormat.OpenXml.Vml.Office", "DocumentModel.Vml" },
    {"DocumentFormat.OpenXml.Vml.Presentation", "DocumentModel.Presentation.Vml" },
    {"DocumentFormat.OpenXml.Vml.Spreadsheet", "DocumentModel.Spreadsheet.Vml" },
    {"DocumentFormat.OpenXml.Vml.Wordprocessing", "DocumentModel.Wordprocessing.Vml" },
    {"DocumentFormat.OpenXml.Wordprocessing", "DocumentModel.Wordprocessing" },
  };

  public static BiDiDictionary<string, string> NamespaceShortcutTable { get; } = new BiDiDictionary<string, string>()
  {
    { "System", "" },
    { "System.Collections", "" },
    { "System.Collections.ObjectModel", "" },
    { "System.Collections.Generic", "" },
    { "System.Collections.Specialized", "" },
    { "System.Globalization", "" },
    { "System.IO", "" },
    { "System.IO.Packaging", "" },
  { "DocumentFormat.OpenXml", "DX" },
  { "DocumentFormat.OpenXml.AdditionalCharacteristics", "DXAddCht" },
  { "DocumentFormat.OpenXml.Bibliography", "DXBib" },
  { "DocumentFormat.OpenXml.CustomProperties", "DXCustProps" },
  { "DocumentFormat.OpenXml.CustomXmlDataProperties", "DXCustXmlDataProps" },
  { "DocumentFormat.OpenXml.CustomXmlSchemaReferences", "DXCustXmlSchRefs" },
  { "DocumentFormat.OpenXml.Drawing", "DXDraw" },
  { "DocumentFormat.OpenXml.Drawing.ChartDrawing", "DXDrawChartDraw" },
  { "DocumentFormat.OpenXml.Drawing.Charts", "DXDrawCharts" },
  { "DocumentFormat.OpenXml.Drawing.Diagrams", "DXDrawDgms" },
  { "DocumentFormat.OpenXml.Drawing.LegacyCompatibility", "DXDrawLegComp" },
  { "DocumentFormat.OpenXml.Drawing.LockedCanvas", "DXDrawLockCanv" },
  { "DocumentFormat.OpenXml.Drawing.Pictures", "DXDrawPict" },
  { "DocumentFormat.OpenXml.Drawing.Spreadsheet", "DXDrawS" },
  { "DocumentFormat.OpenXml.Drawing.Wordprocessing", "DXDrawW" },
  { "DocumentFormat.OpenXml.EMMA", "DXEMMA" },
  { "DocumentFormat.OpenXml.ExtendedProperties", "DXExtProps" },
  { "DocumentFormat.OpenXml.Features", "DXFeat" },
  { "DocumentFormat.OpenXml.Framework", "DXFwork" },
  { "DocumentFormat.OpenXml.Framework.Metadata", "DXFworkMeta" },
  { "DocumentFormat.OpenXml.Framework.Schema", "DXFworkSch" },
  { "DocumentFormat.OpenXml.InkML", "DXInkML" },
  { "DocumentFormat.OpenXml.Math", "DXMath" },
  { "DocumentFormat.OpenXml.Office.ActiveX", "DXOActiveX" },
  { "DocumentFormat.OpenXml.Office.ContentType", "DXOContentType" },
  { "DocumentFormat.OpenXml.Office.CoverPageProps", "DXOCoverPageProps" },
  { "DocumentFormat.OpenXml.Office.CustomDocumentInformationPanel", "DXOCustDocInfPnl" },
  { "DocumentFormat.OpenXml.Office.CustomUI", "DXOCustUI" },
  { "DocumentFormat.OpenXml.Office.CustomXsn", "DXOCustXsn" },
  { "DocumentFormat.OpenXml.Office.Drawing", "DXODraw" },
  { "DocumentFormat.OpenXml.Office.Drawing.Y2021.OEmbed", "DXODrawY2021OEmb" },
  { "DocumentFormat.OpenXml.Office.Drawing.Y2021.ScriptLink", "DXODrawY2021ScptLnk" },
  { "DocumentFormat.OpenXml.Office.Excel", "DXOS" },
  { "DocumentFormat.OpenXml.Office.LongProperties", "DXOLongProps" },
  { "DocumentFormat.OpenXml.Office.MetaAttributes", "DXOMetaAttr" },
  { "DocumentFormat.OpenXml.Office.PowerPoint.Y2021.M06.Main", "DXOPY2021M06Main" },
  { "DocumentFormat.OpenXml.Office.SpreadSheetML.Y2021.ExtLinks2021", "DXOSMLY2021ExtLnks2021" },
  { "DocumentFormat.OpenXml.Office.SpreadSheetML.Y2022.PivotVersionInfo", "DXOSMLY2022PivotVerInf" },
  { "DocumentFormat.OpenXml.Office.Word", "DXOW" },
  { "DocumentFormat.OpenXml.Office.Word.Y2020.OEmbed", "DXOWY2020OEmb" },
  { "DocumentFormat.OpenXml.Office2010.CustomUI", "DXO2010CustUI" },
  { "DocumentFormat.OpenXml.Office2010.Drawing", "DXO2010Draw" },
  { "DocumentFormat.OpenXml.Office2010.Drawing.ChartDrawing", "DXO2010DrawChartDraw" },
  { "DocumentFormat.OpenXml.Office2010.Drawing.Charts", "DXO2010DrawCharts" },
  { "DocumentFormat.OpenXml.Office2010.Drawing.Diagram", "DXO2010DrawDgm" },
  { "DocumentFormat.OpenXml.Office2010.Drawing.LegacyCompatibility", "DXO2010DrawLegComp" },
  { "DocumentFormat.OpenXml.Office2010.Drawing.Pictures", "DXO2010DrawPict" },
  { "DocumentFormat.OpenXml.Office2010.Drawing.Slicer", "DXO2010DrawSlicer" },
  { "DocumentFormat.OpenXml.Office2010.Excel", "DXO2010S" },
  { "DocumentFormat.OpenXml.Office2010.Excel.Drawing", "DXO2010SDraw" },
  { "DocumentFormat.OpenXml.Office2010.ExcelAc", "DXO2010SAc" },
  { "DocumentFormat.OpenXml.Office2010.Ink", "DXO2010Ink" },
  { "DocumentFormat.OpenXml.Office2010.PowerPoint", "DXO2010P" },
  { "DocumentFormat.OpenXml.Office2010.Word", "DXO2010W" },
  { "DocumentFormat.OpenXml.Office2010.Word.Drawing", "DXO2010WDraw" },
  { "DocumentFormat.OpenXml.Office2010.Word.DrawingCanvas", "DXO2010WDrawCnv" },
  { "DocumentFormat.OpenXml.Office2010.Word.DrawingGroup", "DXO2010WDrawGroup" },
  { "DocumentFormat.OpenXml.Office2010.Word.DrawingShape", "DXO2010WDrawShp" },
  { "DocumentFormat.OpenXml.Office2013.Drawing", "DXO2013Draw" },
  { "DocumentFormat.OpenXml.Office2013.Drawing.Chart", "DXO2013DrawChart" },
  { "DocumentFormat.OpenXml.Office2013.Drawing.ChartStyle", "DXO2013DrawChartStyle" },
  { "DocumentFormat.OpenXml.Office2013.Drawing.TimeSlicer", "DXO2013DrawTimeSlicer" },
  { "DocumentFormat.OpenXml.Office2013.Excel", "DXO2013S" },
  { "DocumentFormat.OpenXml.Office2013.ExcelAc", "DXO2013SAc" },
  { "DocumentFormat.OpenXml.Office2013.PowerPoint", "DXO2013P" },
  { "DocumentFormat.OpenXml.Office2013.PowerPoint.Roaming", "DXO2013PRoaming" },
  { "DocumentFormat.OpenXml.Office2013.Theme", "DXO2013Theme" },
  { "DocumentFormat.OpenXml.Office2013.WebExtension", "DXO2013WebExt" },
  { "DocumentFormat.OpenXml.Office2013.WebExtentionPane", "DXO2013WebExtPane" },
  { "DocumentFormat.OpenXml.Office2013.Word", "DXO2013W" },
  { "DocumentFormat.OpenXml.Office2013.Word.Drawing", "DXO2013WDraw" },
  { "DocumentFormat.OpenXml.Office2016.Drawing", "DXO2016Draw" },
  { "DocumentFormat.OpenXml.Office2016.Drawing.ChartDrawing", "DXO2016DrawChartDraw" },
  { "DocumentFormat.OpenXml.Office2016.Drawing.Charts", "DXO2016DrawCharts" },
  { "DocumentFormat.OpenXml.Office2016.Drawing.ChartsAc", "DXO2016DrawChartsAc" },
  { "DocumentFormat.OpenXml.Office2016.Drawing.Command", "DXO2016DrawCmd" },
  { "DocumentFormat.OpenXml.Office2016.Excel", "DXO2016S" },
  { "DocumentFormat.OpenXml.Office2016.ExcelAc", "DXO2016SAc" },
  { "DocumentFormat.OpenXml.Office2016.Presentation", "DXO2016P" },
  { "DocumentFormat.OpenXml.Office2016.Presentation.Command", "DXO2016PCmd" },
  { "DocumentFormat.OpenXml.Office2016.Word.Symex", "DXO2016WSymex" },
  { "DocumentFormat.OpenXml.Office2019.Drawing", "DXO2019Draw" },
  { "DocumentFormat.OpenXml.Office2019.Drawing.Animation", "DXO2019DrawAnim" },
  { "DocumentFormat.OpenXml.Office2019.Drawing.Animation.Model3D", "DXO2019DrawAnim3D" },
  { "DocumentFormat.OpenXml.Office2019.Drawing.Chart", "DXO2019DrawChart" },
  { "DocumentFormat.OpenXml.Office2019.Drawing.Diagram11", "DXO2019DrawDgm11" },
  { "DocumentFormat.OpenXml.Office2019.Drawing.Diagram12", "DXO2019DrawDgm12" },
  { "DocumentFormat.OpenXml.Office2019.Drawing.HyperLinkColor", "DXO2019DrawHLnkClr" },
  { "DocumentFormat.OpenXml.Office2019.Drawing.Ink", "DXO2019DrawInk" },
  { "DocumentFormat.OpenXml.Office2019.Drawing.Model3D", "DXO2019Draw3D" },
  { "DocumentFormat.OpenXml.Office2019.Drawing.SVG", "DXO2019DrawSVG" },
  { "DocumentFormat.OpenXml.Office2019.Excel.CalcFeatures", "DXO2019SCalcFeat" },
  { "DocumentFormat.OpenXml.Office2019.Excel.DynamicArray", "DXO2019SDynArray" },
  { "DocumentFormat.OpenXml.Office2019.Excel.PivotDefaultLayout", "DXO2019SPivotDefLayt" },
  { "DocumentFormat.OpenXml.Office2019.Excel.RichData", "DXO2019SRichData" },
  { "DocumentFormat.OpenXml.Office2019.Excel.RichData2", "DXO2019SRichData2" },
  { "DocumentFormat.OpenXml.Office2019.Excel.ThreadedComments", "DXO2019SThrComt" },
  { "DocumentFormat.OpenXml.Office2019.Presentation", "DXO2019P" },
  { "DocumentFormat.OpenXml.Office2019.Word.Cid", "DXO2019WCid" },
  { "DocumentFormat.OpenXml.Office2021.DocumentTasks", "DXO2021DocTasks" },
  { "DocumentFormat.OpenXml.Office2021.Drawing.DocumentClassification", "DXO2021DrawDocCls" },
  { "DocumentFormat.OpenXml.Office2021.Drawing.Livefeed", "DXO2021DrawLivefeed" },
  { "DocumentFormat.OpenXml.Office2021.Drawing.SketchyShapes", "DXO2021DrawSketchyShps" },
  { "DocumentFormat.OpenXml.Office2021.Excel.ExternalLinks", "DXO2021SExtLnks" },
  { "DocumentFormat.OpenXml.Office2021.Excel.NamedSheetViews", "DXO2021SNamedSheetVws" },
  { "DocumentFormat.OpenXml.Office2021.Excel.Pivot", "DXO2021SPivot" },
  { "DocumentFormat.OpenXml.Office2021.Excel.RichDataWebImage", "DXO2021SRichDataWebImg" },
  { "DocumentFormat.OpenXml.Office2021.Excel.RichValueRefreshIntervals", "DXO2021SRichValRefshImtv" },
  { "DocumentFormat.OpenXml.Office2021.Excel.ThreadedComments2", "DXO2021SThrComt2" },
  { "DocumentFormat.OpenXml.Office2021.MipLabelMetaData", "DXO2021MipLabelMeta" },
  { "DocumentFormat.OpenXml.Office2021.OfficeExtLst", "DXO2021OExtLst" },
  { "DocumentFormat.OpenXml.Office2021.PowerPoint.Comment", "DXO2021PComt" },
  { "DocumentFormat.OpenXml.Office2021.PowerPoint.Designer", "DXO2021PDsg" },
  { "DocumentFormat.OpenXml.Office2021.PowerPoint.Tasks", "DXO2021PTasks" },
  { "DocumentFormat.OpenXml.Office2021.Word.CommentsExt", "DXO2021WComtExt" },
  { "DocumentFormat.OpenXml.Office2021.Word.ExtensionList", "DXO2021WExtList" },
  { "DocumentFormat.OpenXml.Packaging", "DXPack" },
  { "DocumentFormat.OpenXml.Presentation", "DXP" },
  { "DocumentFormat.OpenXml.Spreadsheet", "DXS" },
  { "DocumentFormat.OpenXml.Validation", "DXValid" },
  { "DocumentFormat.OpenXml.Validation.Schema", "DXValidSch" },
  { "DocumentFormat.OpenXml.Validation.Schema.Restrictions", "DXValidSchRest" },
  { "DocumentFormat.OpenXml.Validation.Semantic", "DXValidSmt" },
  { "DocumentFormat.OpenXml.VariantTypes", "DXVT" },
  { "DocumentFormat.OpenXml.Vml", "DXVml" },
  { "DocumentFormat.OpenXml.Vml.Office", "DXVmlO" },
  { "DocumentFormat.OpenXml.Vml.Presentation", "DXVmlP" },
  { "DocumentFormat.OpenXml.Vml.Spreadsheet", "DXVmlS" },
  { "DocumentFormat.OpenXml.Vml.Wordprocessing", "DXVmlW" },
  { "DocumentFormat.OpenXml.Wordprocessing", "DXW" },
  { "DocumentModel", "DM" },
  { "DocumentModel.Bibliography", "DMBib" },
  { "DocumentModel.CustomXml", "DMCustXml" },
  { "DocumentModel.Drawings", "DMDraws" },
  { "DocumentModel.Drawings.Animation", "DMDrawsAnim" },
  { "DocumentModel.Drawings.Animation.Model3D", "DMDrawsAnim3D" },
  { "DocumentModel.Drawings.ChartDrawing", "DMDrawsChartDraw" },
  { "DocumentModel.Drawings.ChartDrawings", "DMDrawsChartDraws" },
  { "DocumentModel.Drawings.Charts", "DMDrawsCharts" },
  { "DocumentModel.Drawings.ChartsStyle", "DMDrawsChartsStyle" },
  { "DocumentModel.Drawings.Diagram1", "DMDrawsDgm1" },
  { "DocumentModel.Drawings.Diagram2", "DMDrawsDgm2" },
  { "DocumentModel.Drawings.Diagrams", "DMDrawsDgms" },
  { "DocumentModel.Drawings.Legacy", "DMDrawsLegacy" },
  { "DocumentModel.Drawings.LockedCanvas", "DMDrawsLockCanv" },
  { "DocumentModel.Drawings.Model3D", "DMDraws3D" },
  { "DocumentModel.Drawings.Office", "DMDrawsO" },
  { "DocumentModel.Drawings.Office.OEmbed", "DMDrawsOOEmb" },
  { "DocumentModel.Drawings.Office.ScriptLink", "DMDrawsOScptLnk" },
  { "DocumentModel.Drawings.Pictures", "DMDrawsPict" },
  { "DocumentModel.Drawings.Slicer", "DMDrawsSlicer" },
  { "DocumentModel.Drawings.Spreadsheet", "DMDrawsS" },
  { "DocumentModel.Drawings.SVG", "DMDrawsSVG" },
  { "DocumentModel.Drawings.Wordprocessing", "DMDrawsW" },
  { "DocumentModel.EMMA", "DMEMMA" },
  { "DocumentModel.Framework", "DMFwork" },
  { "DocumentModel.Math", "DMMath" },
  { "DocumentModel.Packaging", "DMPack" },
  { "DocumentModel.Painting", "DMPainting" },
  { "DocumentModel.Presentation", "DMP" },
  { "DocumentModel.Presentation.Vml", "DMPVml" },
  { "DocumentModel.Properties", "DMProps" },
  { "DocumentModel.Properties", "DMProps" },
  { "DocumentModel.Spreadsheet", "DMS" },
  { "DocumentModel.Spreadsheet.Vml", "DMSVml" },
  { "DocumentModel.UI", "DMUI" },
  { "DocumentModel.Validation", "DMValid" },
  { "DocumentModel.VariantTypes", "DMVT" },
  { "DocumentModel.Vml", "DMVml" },
  { "DocumentModel.WebExtensions", "DMWebExt" },
  { "DocumentModel.WebExtensions.UI", "DMWebExtUI" },
  { "DocumentModel.Wordprocessing", "DMW" },
  { "DocumentModel.Wordprocessing.DrawingCanvas", "DMWDrawCnv" },
  { "DocumentModel.Wordprocessing.Drawings", "DMWDraws" },
  { "DocumentModel.Wordprocessing.DrawingShape", "DMWDrawShp" },
  { "DocumentModel.Wordprocessing.OEmbed", "DMWOEmb" },
  { "DocumentModel.Wordprocessing.Vml", "DMWVml" },

  { "DocumentModel.OpenXml", "DMX" },
  { "DocumentModel.OpenXml.Bibliography", "DMXBib" },
  { "DocumentModel.OpenXml.CustomXml", "DMXCustXml" },
  { "DocumentModel.OpenXml.Drawings", "DMXDraws" },
  { "DocumentModel.OpenXml.Drawings.Animation", "DMXDrawsAnim" },
  { "DocumentModel.OpenXml.Drawings.Animation.Model3D", "DMXDrawsAnim3D" },
  { "DocumentModel.OpenXml.Drawings.ChartDrawing", "DMXDrawsChartDraw" },
  { "DocumentModel.OpenXml.Drawings.ChartDrawings", "DMXDrawsChartDraws" },
  { "DocumentModel.OpenXml.Drawings.Charts", "DMXDrawsCharts" },
  { "DocumentModel.OpenXml.Drawings.ChartsStyle", "DMXDrawsChartsStyle" },
  { "DocumentModel.OpenXml.Drawings.Diagram1", "DMXDrawsDgm1" },
  { "DocumentModel.OpenXml.Drawings.Diagram2", "DMXDrawsDgm2" },
  { "DocumentModel.OpenXml.Drawings.Diagrams", "DMXDrawsDgms" },
  { "DocumentModel.OpenXml.Drawings.Legacy", "DMXDrawsLegacy" },
  { "DocumentModel.OpenXml.Drawings.LockedCanvas", "DMXDrawsLockCanv" },
  { "DocumentModel.OpenXml.Drawings.Model3D", "DMXDraws3D" },
  { "DocumentModel.OpenXml.Drawings.Office", "DMXDrawsO" },
  { "DocumentModel.OpenXml.Drawings.Office.OEmbed", "DMXDrawsOOEmb" },
  { "DocumentModel.OpenXml.Drawings.Office.ScriptLink", "DMXDrawsOScptLnk" },
  { "DocumentModel.OpenXml.Drawings.Pictures", "DMXDrawsPict" },
  { "DocumentModel.OpenXml.Drawings.Slicer", "DMXDrawsSlicer" },
  { "DocumentModel.OpenXml.Drawings.Spreadsheet", "DMXDrawsS" },
  { "DocumentModel.OpenXml.Drawings.SVG", "DMXDrawsSVG" },
  { "DocumentModel.OpenXml.Drawings.Wordprocessing", "DMXDrawsW" },
  { "DocumentModel.OpenXml.EMMA", "DMXEMMA" },
  { "DocumentModel.OpenXml.Framework", "DMXFwork" },
  { "DocumentModel.OpenXml.Math", "DMXMath" },
  { "DocumentModel.OpenXml.Packaging", "DMXPack" },
  { "DocumentModel.OpenXml.Painting", "DMXPainting" },
  { "DocumentModel.OpenXml.Presentation", "DMXP" },
  { "DocumentModel.OpenXml.Presentation.Vml", "DMXPVml" },
  { "DocumentModel.OpenXml.Properties", "DMXProps" },
  { "DocumentModel.OpenXml.Properties", "DMXProps" },
  { "DocumentModel.OpenXml.Spreadsheet", "DMXS" },
  { "DocumentModel.OpenXml.Spreadsheet.Vml", "DMXSVml" },
  { "DocumentModel.OpenXml.UI", "DMXUI" },
  { "DocumentModel.OpenXml.Validation", "DMXValid" },
  { "DocumentModel.OpenXml.VariantTypes", "DMXVT" },
  { "DocumentModel.OpenXml.Vml", "DMXVml" },
  { "DocumentModel.OpenXml.WebExtensions", "DMXWebExt" },
  { "DocumentModel.OpenXml.WebExtensions.UI", "DMXWebExtUI" },
  { "DocumentModel.OpenXml.Wordprocessing", "DMXW" },
  { "DocumentModel.OpenXml.Wordprocessing.DrawingCanvas", "DMXWDrawCnv" },
  { "DocumentModel.OpenXml.Wordprocessing.Drawings", "DMXWDraws" },
  { "DocumentModel.OpenXml.Wordprocessing.DrawingShape", "DMXWDrawShp" },
  { "DocumentModel.OpenXml.Wordprocessing.OEmbed", "DMXWOEmb" },
  { "DocumentModel.OpenXml.Wordprocessing.Vml", "DMXWVml" },
  };
  #endregion

  #region Properties

  public static SortedStrings ExcludedProperties { get; } = new SortedStrings
  {
    "FirstChild", "LastChild", "HasChildren", "InnerText", "InnerXml", "Features",
    "OpenXmlElementContext", "HasAttributes", "ExtendedAttributes", "ChildElements",
    "Parent", "NamespaceUri", "LocalName", "Prefix", "NamespaceDeclarations",
    "XmlQualifiedName", "XName", "OuterXml", "MCAttributes",
    //"RootElement", 
    "IsRootElementLoaded",
    "RelationshipErrorHandlerFactory",
    "AddError",
    "*Part",
    "HasValue",
    "OpenXmlPackage",
    "Container",
    "RootElementContext",
    "WebExtensions"

  };

  public static Dictionary<string, string> PropertyTranslateTable = new()
  {
    { "DXW.LatentStyles.Count", "TotalCount" },
    { "DXW.LatentStyles.LatentStyleExceptionInfos", "Items" },
    //{ "DXW.LatentStyle.Default", "IsDefault" },
    { "DXW.Style.Default", "IsDefault" },
    { "DXW.Style.CustomStyle", "IsCustom" },
    { "DXW.Style.AutoRedefine", "IsAutoRedefined" },
    { "DXW.Style.StyleHidden", "IsHidden" },
    { "DXW.Style.SemiHidden", "IsSemiHidden" },
    { "DXW.Style.UnhideWhenUsed", "IsUnhiddenWhenUsed" },
    { "DXW.Style.PrimaryStyle", "IsPrimary" },
    { "DXW.Style.Locked", "IsLocked" },
    { "DXW.Style.Personal", "IsPersonal" },
    { "DXW.Style.PersonalCompose", "IsPersonalCompose" },
    { "DXW.Style.PersonalReply", "IsPersonalReply" },
    { "DXW.Font.Panose1Number", "Panose"},
    };

  public static Dictionary<string, Type> PropertyTypes { get; } = new()
  {
    { "DocumentModel.DocumentSettings.DocumentId", typeof(HexInt) },
    { "DocumentModel.DocumentSettings.PersistentDocumentId", typeof(Guid) },
    { "DocumentModel.Wordprocessing.CheckBoxSymbolType.Val", typeof(HexChar) },
    { "DocumentModel.Wordprocessing.Mcd.BEncrypt", typeof(HexChar) },
    { "DocumentModel.Wordprocessing.Mcd.Cmg", typeof(HexChar) },
    { "*.Rsid", typeof(HexInt) },
    { "DocumentModel.Wordprocessing.Rsids.RsidRoot", typeof(HexInt) },
    { "DocumentModel.Wordprocessing.Rsids.Items", typeof(Collection<HexInt>) },
  };

  public static bool TryGetPropertyType(string propertyName, [MaybeNullWhen(false)][NotNullWhen(true)] out Type propertyType)
  {
    if (PropertyTypes.TryGetValue(propertyName, out propertyType))
      return true;
    var k = propertyName.IndexOf('.');
    while (k>0)
    {
      var wildcardName = '*'+propertyName.Substring(k);
      if (PropertyTypes.TryGetValue(wildcardName, out propertyType))
        return true;
      k = propertyName.IndexOf(".",k+1);
    }
    propertyType = null;
    return false;
  }

  #endregion

  #region Types
  public static bool IsExcluded(Type type)
  {
    if (IncludedTypes.Contains(type.Name))
      return false;
    if (ExcludedNamespaces.Contains(type.Namespace ?? ""))
      return true;
    if (ExcludedTypes.Contains(type.Name))
      return true;
    return false;
  }

  public static SortedStrings ExcludedTypes { get; } = new SortedStrings
  {
    "SR", "*Reader", "*Attribute", "*Attributes", "*Extensions", "*Helper", "*Provider", "*Methods",
    "XmlConvertingReader*", "*.Part", "EnumInfoLookup`1", "MiscAttrContainer", "ModelElement", /*"HexWord",*/
    "OpenXmlElementContext",
    "OpenXmlElementList",
    "OpenXmlSimpleType",
    "OpenXmlPackage",
    "OpenXmlPart",
    "TypedOpenXmlPart",
    "OpenXmlPartContainer",
    "IFixedContentTypePart",
    "WordAttachedToolbarsPart",
    "Worksheet*Part",
    "NamedsheetPart",
    "PivotTable*Part",
    "TableDefinitionPart",
    "QueryTablePart",
    "SingleCellTablePart",
    "SpreadsheetPrinterSettingsPart",
    "Slide*Part",
    "Notes*Part",
    "PowerPointCommentPart",
    "DocumentTasksPart",
    "Vba*Part",
    "Ribbon*Part",
    "QuickAccessToolbarCustomizationsPart",
    "WebEx*Part",
    "CustomUIPart",
    "TypedOpenXmlPackage",
    "OnOffType",
  };

  public static SortedStrings IncludedTypes { get; } = new SortedStrings
  {
    "CustomXmlAttribute",
    "DocPart",
    "Wordprocessing*",
    "WordprocessingDocumentType",
    //"OpenXmlSolidColorFillPropertiesElement",
    //"OpenXmlValueColorEndPositionElement", "OpenXmlTaskAssignUnassignUserElement", "OpenXmlTaskUserElement",
    //"OpenXmlPartRootElement",
    //"OpenXmlFormulaElement",
  };

  public static SortedStrings ExcludedAttributes { get; } = new SortedStrings
  {
    "OfficeAvailability", "NullableContext", "SchemaAttr", "Nullable", "Serializable", 
    "DebuggerDisplay", "DebuggerNonUserCode", "CLSCompliant", "EditorBrowsable",
  };

  public static Dictionary<string, string> TypeNameConversion { get; } = new()
  {
    { "DocumentFormat.OpenXml.Wordprocessing.Settings", "DocumentModel.DocumentSettings"},
    { "DocumentFormat.OpenXml.Wordprocessing.WebSettings", "DocumentModel.WebSettings"},
    { "DocumentFormat.OpenXml.Wordprocessing.Fonts", "DocumentModel.Wordprocessing.Fonts"},
  //  //{ "DocumentFormat.OpenXml.ExtendedProperties.Properties", "DocumentModel.ExtendedProperties"},
  //  //{ "DocumentFormat.OpenXml.CustomProperties.Properties", "DocumentModel.CustomProperties"},
  //  //{ "DocumentFormat.OpenXml.Drawing.ChartDrawingNonVisualDrawingProperties", "DocumentModel.Drawings.DrawingNonVisualDrawingProperties" },
  //  //{ "DocumentFormat.OpenXml.Presentation.NonVisualDrawingProperties", "DocumentModel.Presentation.PresentationNonVisualDrawingProperties" },
  //  //{ "DocumentFormat.OpenXml.Drawing.ShapeProperties", "DocumentModel.Drawings.ShapeProperties"},
  //  //{ "DocumentFormat.OpenXml.Office2010.Word.RunTrackChangeType", "DocumentModel.Wordprocessing.RunTrackChangeType2"},
  //  //{ "DocumentFormat.OpenXml.Office2013.Drawing.Chart.AxisDataSourceType", "DocumentModel.Drawings.AxisDataSourceType2"},
  //  //{ "DocumentFormat.OpenXml.Office2016.Drawing.ChartDrawing.TextBodyType", "DocumentModel.Drawings.TextBodyType2"},
  //  //{ "DocumentFormat.OpenXml.Office2013.Drawing.Chart.StringDataType", "DocumentModel.Drawings.StringDataType2"},
  };

  public static Dictionary<string, Type> ModelTypes { get; } = new();


  public static void LoadModelTypes(Assembly assembly)
  {
    foreach (var type in assembly.GetTypes())
      ModelTypes.Add(type.FullName ?? "", type);
  }

  public record TypeConversionTarget
  {
    public Type Type {get; set; }= null!;
    public bool Rename {get; set;}

    public TypeConversionTarget(Type type)
    {
      Type = type;
    }
    public TypeConversionTarget(Type type, bool rename)
    {
      Type = type;
      Rename = rename;
    }

    public static implicit operator TypeConversionTarget (Type type) => new TypeConversionTarget(type);
    public static implicit operator TypeConversionTarget (TypeInfo typeInfo) => new TypeConversionTarget(typeInfo.Type);
  }
  public static Dictionary<Type, TypeConversionTarget> TypeConversionTable { get; } = new ()
  {
    { typeof(DocumentFormat.OpenXml.StringValue), typeof(System.String)},
    { typeof(DocumentFormat.OpenXml.BooleanValue), typeof(System.Boolean)},
    { typeof(DocumentFormat.OpenXml.OnOffValue), typeof(System.Boolean)},
    { typeof(DocumentFormat.OpenXml.Wordprocessing.OnOffOnlyValues), typeof(System.Boolean)},
    { typeof(DocumentFormat.OpenXml.Office2019.Drawing.Chart.BooleanFalse), typeof(System.Boolean) },
    { typeof(DocumentFormat.OpenXml.Office2010.ExcelAc.List), typeof(System.String) },
    { typeof(DocumentFormat.OpenXml.IntegerValue), typeof(System.Int64)},
    { typeof(DocumentFormat.OpenXml.Int32Value), typeof(System.Int32)},
    { typeof(DocumentFormat.OpenXml.UInt32Value), typeof(System.UInt32)},
    { typeof(DocumentFormat.OpenXml.Int16Value), typeof(System.Int16)},
    { typeof(DocumentFormat.OpenXml.UInt16Value), typeof(System.UInt16)},
    { typeof(DocumentFormat.OpenXml.Int64Value), typeof(System.Int64)},
    { typeof(DocumentFormat.OpenXml.UInt64Value), typeof(System.UInt16)},
    { typeof(DocumentFormat.OpenXml.ByteValue), typeof(System.Byte)},
    { typeof(DocumentFormat.OpenXml.SByteValue), typeof(System.SByte)},
    { typeof(DocumentFormat.OpenXml.SingleValue), typeof(System.Single)},
    { typeof(DocumentFormat.OpenXml.DoubleValue), typeof(System.Double)},
    { typeof(DocumentFormat.OpenXml.DecimalValue), typeof(System.Decimal)},
    { typeof(DocumentFormat.OpenXml.DateTimeValue), typeof(System.DateTime)},
    { typeof(DocumentFormat.OpenXml.OpenXmlElement), typeof(DocumentModel.ModelElement)},
    { typeof(DocumentFormat.OpenXml.OpenXmlLeafElement), typeof(System.Boolean)},
    { typeof(DocumentFormat.OpenXml.OpenXmlLeafTextElement), typeof(System.String)},
    { typeof(DocumentFormat.OpenXml.Wordprocessing.LongHexNumberType), typeof(UInt32)},
    { typeof(DocumentFormat.OpenXml.EnumStringAttribute), typeof(System.Xml.Serialization.XmlEnumAttribute) },
    { typeof(DocumentFormat.OpenXml.OfficeAvailabilityAttribute), typeof(DocumentModel.Attributes.OfficeAvailabilityAttribute) },
    { typeof(DocumentFormat.OpenXml.ChildElementInfoAttribute), typeof(DocumentModel.Attributes.ChildElementInfoAttribute) },
    { typeof(DocumentFormat.OpenXml.SchemaAttrAttribute), typeof(DocumentModel.Attributes.SchemaAttrAttribute) },
    { typeof(DocumentFormat.OpenXml.VariantTypes.Variant), typeof(DocumentModel.Variant)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTArray), typeof(DocumentModel.ArrayVariant)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTVector), typeof(DocumentModel.VectorVariant)},
    { typeof(DocumentFormat.OpenXml.Base64BinaryValue), typeof(DocumentModel.Base64Binary)},
    { typeof(DocumentFormat.OpenXml.HexBinaryValue), typeof(DocumentModel.HexBinary)},
//    { typeof(Collection<UInt32>), typeof(Collection<HexInt>)},
  };

  public static Dictionary<Type, string> BuiltInTypeNames { get; } = new Dictionary<Type, string>
  {
    { typeof(System.Object), "object" },
    { typeof(System.String), "string" },
    { typeof(System.Boolean), "bool" },
    { typeof(System.Int32), "int"},
    { typeof(System.UInt32), "uint"},
    { typeof(System.Int16), "short" },
    { typeof(System.UInt16), "ushort" },
    { typeof(System.Int64), "long" },
    { typeof(System.UInt64), "ulong" },
    { typeof(System.Byte), "byte" },
    { typeof(System.SByte), "sbyte" },
    { typeof(System.Single), "float" },
    { typeof(System.Double), "double" },
    { typeof(System.Decimal), "decimal" },
  };

  public static string[] SimpleTypeNames { get; } = new string[]
  {
    nameof(System.String),
    nameof(System.Boolean),
    nameof(System.Int32),
    nameof(System.UInt32),
    nameof(System.Int16),
    nameof(System.UInt16),
    nameof(System.Int64),
    nameof(System.UInt64),
    nameof(System.Byte),
    nameof(System.SByte),
    nameof(System.Single),
    nameof(System.Double),
    nameof(System.Decimal),
  };

  #endregion
}