using System.Diagnostics;


using Qhta.Collections;

namespace ModelGen;

public static class ModelData
{

  #region Namespaces

  public static SortedStrings IncludedNamespaces { get; } = new SortedStrings
  {
    //"DocumentFormat.OpenXml.VariantTypes"
    "DocumentFormat.OpenXml.Wordprocessing"
  };

  public static SortedStrings ExcludedNamespaces { get; } = new SortedStrings
  {
    "*Metadata", "*Features", "*Framework", "*Framework.Schema", "*Validation", "*Validation.Schema", 
    "*Presentation*",
    "*Spreadsheet*",
    "*SpreadSheet*",
    "*Excel*",
    "*PowerPoint*",
  };

  public static BiDiDictionary<string, string> Namespaces { get; } = new BiDiDictionary<string, string>()
  {
    { "oo", "DocumentFormat.OpenXml" },
    { "ac", "DocumentFormat.OpenXml.AdditionalCharacteristics" },
    { "bib", "DocumentFormat.OpenXml.Bibliography" },
    { "cp", "DocumentFormat.OpenXml.CustomProperties" },
    { "cxdatpr", "DocumentFormat.OpenXml.CustomXmlDataProperties" },
    { "cxschpr", "DocumentFormat.OpenXml.CustomXmlSchemaReferences" },
    { "dr", "DocumentFormat.OpenXml.Drawings" },
    { "chrtdr", "DocumentFormat.OpenXml.Drawing.ChartDrawing" },
    { "chrt", "DocumentFormat.OpenXml.Drawing.Charts" },
    { "dgk", "DocumentFormat.OpenXml.Drawing.Diagrams" },
    { "drlc", "DocumentFormat.OpenXml.Drawing.LegacyCompatibility" },
    { "drc", "DocumentFormat.OpenXml.Drawing.LockedCanvas" },
    { "pic", "DocumentFormat.OpenXml.Drawing.Pictures" },
    { "drs", "DocumentFormat.OpenXml.Drawing.Spreadsheet" },
    { "drw", "DocumentFormat.OpenXml.Drawing.Wordprocessing" },
    { "em", "DocumentFormat.OpenXml.EMMA" },
    { "xp", "DocumentFormat.OpenXml.ExtendedProperties" },
    { "feat", "DocumentFormat.OpenXml.Features" },
    { "fw", "DocumentFormat.OpenXml.Framework" },
    { "fwm", "DocumentFormat.OpenXml.Framework.Metadata" },
    { "fws", "DocumentFormat.OpenXml.Framework.Schema" },
    { "ink", "DocumentFormat.OpenXml.InkML" },
    { "m", "DocumentFormat.OpenXml.Math" },
    { "oax", "DocumentFormat.OpenXml.Office.ActiveX" },
    { "oct", "DocumentFormat.OpenXml.Office.ContentType" },
    { "ocpp", "DocumentFormat.OpenXml.Office.CoverPageProps" },
    { "ocdip", "DocumentFormat.OpenXml.Office.CustomDocumentInformationPanel" },
    { "oui", "DocumentFormat.OpenXml.Office.CustomUI" },
    { "ocxsn", "DocumentFormat.OpenXml.Office.CustomXsn" },
    { "odr", "DocumentFormat.OpenXml.Office.Drawings" },
    { "odr21e", "DocumentFormat.OpenXml.Office.Drawing.Y2021.OEmbed" },
    { "odr21s", "DocumentFormat.OpenXml.Office.Drawing.Y2021.ScriptLink" },
    { "ox", "DocumentFormat.OpenXml.Office.Excel" },
    { "olp", "DocumentFormat.OpenXml.Office.LongProperties" },
    { "oma", "DocumentFormat.OpenXml.Office.MetaAttributes" },
    { "op21", "DocumentFormat.OpenXml.Office.PowerPoint.Y2021.M06.Main" },
    { "os21", "DocumentFormat.OpenXml.Office.SpreadSheetML.Y2021.ExtLinks2021" },
    { "os22", "DocumentFormat.OpenXml.Office.SpreadSheetML.Y2022.PivotVersionInfo" },
    { "ow", "DocumentFormat.OpenXml.Office.Word" },
    { "ow20e", "DocumentFormat.OpenXml.Office.Word.Y2020.OEmbed" },
    { "o10ui", "DocumentFormat.OpenXml.Office2010.CustomUI" },
    { "o10dr", "DocumentFormat.OpenXml.Office2010.Drawings" },
    { "o10chrtdr", "DocumentFormat.OpenXml.Office2010.Drawing.ChartDrawing" },
    { "o10chrt", "DocumentFormat.OpenXml.Office2010.Drawing.Charts" },
    { "o10dgm", "DocumentFormat.OpenXml.Office2010.Drawing.Diagram" },
    { "o10drlc", "DocumentFormat.OpenXml.Office2010.Drawing.LegacyCompatibility" },
    { "o10pic", "DocumentFormat.OpenXml.Office2010.Drawing.Pictures" },
    { "o10slc", "DocumentFormat.OpenXml.Office2010.Drawing.Slicer" },
    { "o10x", "DocumentFormat.OpenXml.Office2010.Excel" },
    { "o10xdr", "DocumentFormat.OpenXml.Office2010.Excel.Drawings" },
    { "o10xac", "DocumentFormat.OpenXml.Office2010.ExcelAc" },
    { "o10ink", "DocumentFormat.OpenXml.Office2010.Ink" },
    { "o10p", "DocumentFormat.OpenXml.Office2010.PowerPoint" },
    { "o10w", "DocumentFormat.OpenXml.Office2010.Word" },
    { "o10wdr", "DocumentFormat.OpenXml.Office2010.Word.Drawings" },
    { "o10wdc", "DocumentFormat.OpenXml.Office2010.Word.DrawingCanvas" },
    { "o10drg", "DocumentFormat.OpenXml.Office2010.Word.DrawingGroup" },
    { "o10drs", "DocumentFormat.OpenXml.Office2010.Word.DrawingShape" },
    { "o13dr", "DocumentFormat.OpenXml.Office2013.Drawings" },
    { "o13drchrt", "DocumentFormat.OpenXml.Office2013.Drawing.Chart" },
    { "o13drchrts", "DocumentFormat.OpenXml.Office2013.Drawing.ChartStyle" },
    { "o13tslc", "DocumentFormat.OpenXml.Office2013.Drawing.TimeSlicer" },
    { "o13x", "DocumentFormat.OpenXml.Office2013.Excel" },
    { "o13xac", "DocumentFormat.OpenXml.Office2013.ExcelAc" },
    { "o13p", "DocumentFormat.OpenXml.Office2013.PowerPoint" },
    { "o13pr", "DocumentFormat.OpenXml.Office2013.PowerPoint.Roaming" },
    { "o13th", "DocumentFormat.OpenXml.Office2013.Theme" },
    { "o13wx", "DocumentFormat.OpenXml.Office2013.WebExtension" },
    { "o13wxp", "DocumentFormat.OpenXml.Office2013.WebExtentionPane" },
    { "o13w", "DocumentFormat.OpenXml.Office2013.Word" },
    { "o13wdr", "DocumentFormat.OpenXml.Office2013.Word.Drawings" },
    { "o16dr", "DocumentFormat.OpenXml.Office2016.Drawings" },
    { "o16chrtdr", "DocumentFormat.OpenXml.Office2016.Drawing.ChartDrawing" },
    { "o16chrt", "DocumentFormat.OpenXml.Office2016.Drawing.Charts" },
    { "o16chrtac", "DocumentFormat.OpenXml.Office2016.Drawing.ChartsAc" },
    { "o16drcmd", "DocumentFormat.OpenXml.Office2016.Drawing.Command" },
    { "o16x", "DocumentFormat.OpenXml.Office2016.Excel" },
    { "o16xac", "DocumentFormat.OpenXml.Office2016.ExcelAc" },
    { "o16p", "DocumentFormat.OpenXml.Office2016.Presentation" },
    { "o16pcmd", "DocumentFormat.OpenXml.Office2016.Presentation.Command" },
    { "o16", "DocumentFormat.OpenXml.Office2016.Word.Symex" },
    { "o19dr", "DocumentFormat.OpenXml.Office2019.Drawings" },
    { "o19dran", "DocumentFormat.OpenXml.Office2019.Drawing.Animation" },
    { "o19dran3d", "DocumentFormat.OpenXml.Office2019.Drawing.Animation.Model3D" },
    { "o19drchrt", "DocumentFormat.OpenXml.Office2019.Drawing.Chart" },
    { "o19dgm1", "DocumentFormat.OpenXml.Office2019.Drawing.Diagram11" },
    { "O19dgm2", "DocumentFormat.OpenXml.Office2019.Drawing.Diagram12" },
    { "o19hlc", "DocumentFormat.OpenXml.Office2019.Drawing.HyperLinkColor" },
    { "o19ink", "DocumentFormat.OpenXml.Office2019.Drawing.Ink" },
    { "o19dr3d", "DocumentFormat.OpenXml.Office2019.Drawing.Model3D" },
    { "o19svg", "DocumentFormat.OpenXml.Office2019.Drawing.SVG" },
    { "o19xcf", "DocumentFormat.OpenXml.Office2019.Excel.CalcFeatures" },
    { "o10xda", "DocumentFormat.OpenXml.Office2019.Excel.DynamicArray" },
    { "o19xpdl", "DocumentFormat.OpenXml.Office2019.Excel.PivotDefaultLayout" },
    { "o19xrd", "DocumentFormat.OpenXml.Office2019.Excel.RichData" },
    { "o19xrd2", "DocumentFormat.OpenXml.Office2019.Excel.RichData2" },
    { "o19xtc", "DocumentFormat.OpenXml.Office2019.Excel.ThreadedComments" },
    { "o19p", "DocumentFormat.OpenXml.Office2019.Presentation" },
    { "o19wcid", "DocumentFormat.OpenXml.Office2019.Word.Cid" },
    { "o21dt", "DocumentFormat.OpenXml.Office2021.DocumentTasks" },
    { "o23dc", "DocumentFormat.OpenXml.Office2021.Drawing.DocumentClassification" },
    { "o32lf", "DocumentFormat.OpenXml.Office2021.Drawing.Livefeed" },
    { "o23ss", "DocumentFormat.OpenXml.Office2021.Drawing.SketchyShapes" },
    { "o21xl", "DocumentFormat.OpenXml.Office2021.Excel.ExternalLinks" },
    { "o32nsv", "DocumentFormat.OpenXml.Office2021.Excel.NamedSheetViews" },
    { "o21xpvt", "DocumentFormat.OpenXml.Office2021.Excel.Pivot" },
    { "o21xrdwimg", "DocumentFormat.OpenXml.Office2021.Excel.RichDataWebImage" },
    { "o21rvrint", "DocumentFormat.OpenXml.Office2021.Excel.RichValueRefreshIntervals" },
    { "o21xtc2", "DocumentFormat.OpenXml.Office2021.Excel.ThreadedComments2" },
    { "o21mlmd", "DocumentFormat.OpenXml.Office2021.MipLabelMetaData" },
    { "o21oxl", "DocumentFormat.OpenXml.Office2021.OfficeExtLst" },
    { "o21pc", "DocumentFormat.OpenXml.Office2021.PowerPoint.Comment" },
    { "o21pd", "DocumentFormat.OpenXml.Office2021.PowerPoint.Designer" },
    { "o21pt", "DocumentFormat.OpenXml.Office2021.PowerPoint.Tasks" },
    { "o21wcx", "DocumentFormat.OpenXml.Office2021.Word.CommentsExt" },
    { "o21wxl", "DocumentFormat.OpenXml.Office2021.Word.ExtensionList" },
    { "pck", "DocumentFormat.OpenXml.Packaging" },
    { "p", "DocumentFormat.OpenXml.Presentation" },
    { "s", "DocumentFormat.OpenXml.Spreadsheet" },
    { "val", "DocumentFormat.OpenXml.Validation" },
    { "valsch", "DocumentFormat.OpenXml.Validation.Schema" },
    { "valrest", "DocumentFormat.OpenXml.Validation.Schema.Restrictions" },
    { "valsem", "DocumentFormat.OpenXml.Validation.Semantic" },
    { "vt", "DocumentFormat.OpenXml.VariantTypes" },
    { "vml", "DocumentFormat.OpenXml.Vml" },
    { "vmlo", "DocumentFormat.OpenXml.Vml.Office" },
    { "vmlp", "DocumentFormat.OpenXml.Vml.Presentation" },
    { "vmls", "DocumentFormat.OpenXml.Vml.Spreadsheet" },
    { "vmlw", "DocumentFormat.OpenXml.Vml.Wordprocessing" },
    { "w", "DocumentFormat.OpenXml.Wordprocessing" },
  };

  public static BiDiDictionary<string, string> NamespaceTranslationTable { get; } = new BiDiDictionary<string, string>()
  {
    {"DocumentFormat.OpenXml", "DocumentModel" },
    {"DocumentFormat.OpenXml.AdditionalCharacteristics", "DocumentModel" },
    {"DocumentFormat.OpenXml.Bibliography", "DocumentModel.Bibliography" },
    {"DocumentFormat.OpenXml.CustomProperties", "DocumentModel" },
    {"DocumentFormat.OpenXml.CustomXmlDataProperties", "DocumentModel.CustomXml" },
    {"DocumentFormat.OpenXml.CustomXmlSchemaReferences", "DocumentModel.CustomXml" },
    {"DocumentFormat.OpenXml.Drawing", "DocumentModel.Drawings" },
    {"DocumentFormat.OpenXml.Drawing.ChartDrawing", "DocumentModel.Drawings.ChartDrawing" },
    {"DocumentFormat.OpenXml.Drawing.Charts", "DocumentModel.Drawings.Charts" },
    {"DocumentFormat.OpenXml.Drawing.Diagrams", "DocumentModel.Drawings.Diagrams" },
    {"DocumentFormat.OpenXml.Drawing.LegacyCompatibility", "DocumentModel.Drawings.Legacy" },
    {"DocumentFormat.OpenXml.Drawing.LockedCanvas", "DocumentModel.Drawings.LockedCanvas" },
    {"DocumentFormat.OpenXml.Drawing.Pictures", "DocumentModel.Drawings.Pictures" },
    {"DocumentFormat.OpenXml.Drawing.Spreadsheet", "DocumentModel.Drawings.Spreadsheet" },
    {"DocumentFormat.OpenXml.Drawing.Wordprocessing", "DocumentModel.Drawings.Wordprocessing" },
    {"DocumentFormat.OpenXml.EMMA", "DocumentModel.EMMA" },
    {"DocumentFormat.OpenXml.ExtendedProperties", "DocumentModel" },
    {"DocumentFormat.OpenXml.Features", "DocumentModel.Framework" },
    {"DocumentFormat.OpenXml.Framework", "DocumentModel.Framework" },
    {"DocumentFormat.OpenXml.Framework.Metadata", "DocumentModel.Framework" },
    {"DocumentFormat.OpenXml.Framework.Schema", "DocumentModel.Framework" },
    {"DocumentFormat.OpenXml.InkML", "DocumentModel.Painting" },
    {"DocumentFormat.OpenXml.Math", "DocumentModel.Math" },
    {"DocumentFormat.OpenXml.Office.ActiveX", "DocumentModel.UI" },
    {"DocumentFormat.OpenXml.Office.ContentType", "DocumentModel.UI" },
    {"DocumentFormat.OpenXml.Office.CoverPageProps", "DocumentModel.UI" },
    {"DocumentFormat.OpenXml.Office.CustomDocumentInformationPanel", "DocumentModel.UI" },
    {"DocumentFormat.OpenXml.Office.CustomUI", "DocumentModel.UI" },
    {"DocumentFormat.OpenXml.Office.CustomXsn", "DocumentModel.UI" },
    {"DocumentFormat.OpenXml.Office.Drawing", "DocumentModel.Drawings.Office" },
    {"DocumentFormat.OpenXml.Office.Drawing.Y2021.OEmbed", "DocumentModel.Drawings.Office.OEmbed" },
    {"DocumentFormat.OpenXml.Office.Drawing.Y2021.ScriptLink", "DocumentModel.Drawings.Office.ScriptLink" },
    {"DocumentFormat.OpenXml.Office.Excel", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office.LongProperties", "DocumentModel" },
    {"DocumentFormat.OpenXml.Office.MetaAttributes", "DocumentModel" },
    {"DocumentFormat.OpenXml.Office.PowerPoint.Y2021.M06.Main", "DocumentModel.Presentation" },
    {"DocumentFormat.OpenXml.Office.SpreadSheetML.Y2021.ExtLinks2021", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office.SpreadSheetML.Y2022.PivotVersionInfo", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office.Word", "DocumentModel.Wordprocessing" },
    {"DocumentFormat.OpenXml.Office.Word.Y2020.OEmbed", "DocumentModel.Wordprocessing.OEmbed" },
    {"DocumentFormat.OpenXml.Office2010.CustomUI", "DocumentModel" },
    {"DocumentFormat.OpenXml.Office2010.Drawing", "DocumentModel.Drawings" },
    {"DocumentFormat.OpenXml.Office2010.Drawing.ChartDrawing", "DocumentModel.Drawings.ChartDrawings" },
    {"DocumentFormat.OpenXml.Office2010.Drawing.Charts", "DocumentModel.Drawings.Charts" },
    {"DocumentFormat.OpenXml.Office2010.Drawing.Diagram", "DocumentModel.Drawings.Diagrams" },
    {"DocumentFormat.OpenXml.Office2010.Drawing.LegacyCompatibility", "DocumentModel.Drawings.Legacy" },
    {"DocumentFormat.OpenXml.Office2010.Drawing.Pictures", "DocumentModel.Drawings.Pictures" },
    {"DocumentFormat.OpenXml.Office2010.Drawing.Slicer", "DocumentModel.Drawings.Slicer" },
    {"DocumentFormat.OpenXml.Office2010.Excel", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2010.Excel.Drawing", "DocumentModel.Drawings.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2010.ExcelAc", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2010.Ink", "DocumentModel" },
    {"DocumentFormat.OpenXml.Office2010.PowerPoint", "DocumentModel.Presentation" },
    {"DocumentFormat.OpenXml.Office2010.Word", "DocumentModel.Wordprocessing" },
    {"DocumentFormat.OpenXml.Office2010.Word.Drawing", "DocumentModel.Drawings.Wordprocessing" },
    {"DocumentFormat.OpenXml.Office2010.Word.DrawingCanvas", "DocumentModel.Drawings.Wordprocessing" },
    {"DocumentFormat.OpenXml.Office2010.Word.DrawingGroup", "DocumentModel.Drawings.Wordprocessing" },
    {"DocumentFormat.OpenXml.Office2010.Word.DrawingShape", "DocumentModel.Drawings.Wordprocessing" },
    {"DocumentFormat.OpenXml.Office2013.Drawing", "DocumentModel.Drawings" },
    {"DocumentFormat.OpenXml.Office2013.Drawing.Chart", "DocumentModel.Drawings.Charts" },
    {"DocumentFormat.OpenXml.Office2013.Drawing.ChartStyle", "DocumentModel.Drawings.ChartsStyle" },
    {"DocumentFormat.OpenXml.Office2013.Drawing.TimeSlicer", "DocumentModel.Drawings" },
    {"DocumentFormat.OpenXml.Office2013.Excel", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2013.ExcelAc", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2013.PowerPoint", "DocumentModel.Presentation" },
    {"DocumentFormat.OpenXml.Office2013.PowerPoint.Roaming", "DocumentModel.Presentation" },
    {"DocumentFormat.OpenXml.Office2013.Theme", "DocumentModel" },
    {"DocumentFormat.OpenXml.Office2013.WebExtension", "DocumentModel.WebExtensions" },
    {"DocumentFormat.OpenXml.Office2013.WebExtentionPane", "DocumentModel.WebExtensions.UI" },
    {"DocumentFormat.OpenXml.Office2013.Word", "DocumentModel.Wordprocessing" },
    {"DocumentFormat.OpenXml.Office2013.Word.Drawing", "DocumentModel.Drawings.Wordprocessing" },
    {"DocumentFormat.OpenXml.Office2016.Drawing", "DocumentModel.Drawings" },
    {"DocumentFormat.OpenXml.Office2016.Drawing.ChartDrawing", "DocumentModel.Drawings.ChartDrawings" },
    {"DocumentFormat.OpenXml.Office2016.Drawing.Charts", "DocumentModel.Drawings.Charts" },
    {"DocumentFormat.OpenXml.Office2016.Drawing.ChartsAc", "DocumentModel.Drawings.Charts" },
    {"DocumentFormat.OpenXml.Office2016.Drawing.Command", "DocumentModel.Drawings" },
    {"DocumentFormat.OpenXml.Office2016.Excel", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2016.ExcelAc", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2016.Presentation", "DocumentModel.Presentation" },
    {"DocumentFormat.OpenXml.Office2016.Presentation.Command", "DocumentModel.Presentation" },
    {"DocumentFormat.OpenXml.Office2016.Word.Symex", "DocumentModel.Wordprocessing" },
    {"DocumentFormat.OpenXml.Office2019.Drawing", "DocumentModel.Drawings" },
    {"DocumentFormat.OpenXml.Office2019.Drawing.Animation", "DocumentModel.Drawings.Animation" },
    {"DocumentFormat.OpenXml.Office2019.Drawing.Animation.Model3D", "DocumentModel.Drawings.Animation.Model3D" },
    {"DocumentFormat.OpenXml.Office2019.Drawing.Chart", "DocumentModel.Drawings.Charts" },
    {"DocumentFormat.OpenXml.Office2019.Drawing.Diagram11", "DocumentModel.Drawings.Diagram1" },
    {"DocumentFormat.OpenXml.Office2019.Drawing.Diagram12", "DocumentModel.Drawings.Diagram2" },
    {"DocumentFormat.OpenXml.Office2019.Drawing.HyperLinkColor", "DocumentModel.Drawings" },
    {"DocumentFormat.OpenXml.Office2019.Drawing.Ink", "DocumentModel.Drawings" },
    {"DocumentFormat.OpenXml.Office2019.Drawing.Model3D", "DocumentModel.Drawings.Model3D" },
    {"DocumentFormat.OpenXml.Office2019.Drawing.SVG", "DocumentModel.Drawings.SVG" },
    {"DocumentFormat.OpenXml.Office2019.Excel.CalcFeatures", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2019.Excel.DynamicArray", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2019.Excel.PivotDefaultLayout", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2019.Excel.RichData", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2019.Excel.RichData2", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2019.Excel.ThreadedComments", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2019.Presentation", "DocumentModel.Presentation" },
    {"DocumentFormat.OpenXml.Office2019.Word.Cid", "DocumentModel.Wordprocessing" },
    {"DocumentFormat.OpenXml.Office2021.DocumentTasks", "DocumentModel" },
    {"DocumentFormat.OpenXml.Office2021.Drawing.DocumentClassification", "DocumentModel.Drawings" },
    {"DocumentFormat.OpenXml.Office2021.Drawing.Livefeed", "DocumentModel.Drawings" },
    {"DocumentFormat.OpenXml.Office2021.Drawing.SketchyShapes", "DocumentModel.Drawings" },
    {"DocumentFormat.OpenXml.Office2021.Excel.ExternalLinks", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2021.Excel.NamedSheetViews", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2021.Excel.Pivot", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2021.Excel.RichDataWebImage", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2021.Excel.RichValueRefreshIntervals", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2021.Excel.ThreadedComments2", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Office2021.MipLabelMetaData", "DocumentModel" },
    {"DocumentFormat.OpenXml.Office2021.OfficeExtLst", "DocumentModel" },
    {"DocumentFormat.OpenXml.Office2021.PowerPoint.Comment", "DocumentModel.Presentation" },
    {"DocumentFormat.OpenXml.Office2021.PowerPoint.Designer", "DocumentModel.Presentation" },
    {"DocumentFormat.OpenXml.Office2021.PowerPoint.Tasks", "DocumentModel.Presentation" },
    {"DocumentFormat.OpenXml.Office2021.Word.CommentsExt", "DocumentModel.Wordprocessing" },
    {"DocumentFormat.OpenXml.Office2021.Word.ExtensionList", "DocumentModel.Wordprocessing" },
    {"DocumentFormat.OpenXml.Packaging", "DocumentModel.Packaging" },
    {"DocumentFormat.OpenXml.Presentation", "DocumentModel.Presentation" },
    {"DocumentFormat.OpenXml.Spreadsheet", "DocumentModel.Spreadsheet" },
    {"DocumentFormat.OpenXml.Validation", "DocumentModel.Validation" },
    {"DocumentFormat.OpenXml.Validation.Schema", "DocumentModel.Validation" },
    {"DocumentFormat.OpenXml.Validation.Schema.Restrictions", "DocumentModel.Validation" },
    {"DocumentFormat.OpenXml.Validation.Semantic", "DocumentModel.Validation" },
    {"DocumentFormat.OpenXml.VariantTypes", "DocumentModel.VariantTypes" },
    {"DocumentFormat.OpenXml.Vml", "DocumentModel.Vml" },
    {"DocumentFormat.OpenXml.Vml.Office", "DocumentModel.Vml" },
    {"DocumentFormat.OpenXml.Vml.Presentation", "DocumentModel.Presentation.Vml" },
    {"DocumentFormat.OpenXml.Vml.Spreadsheet", "DocumentModel.Spreadsheet.Vml" },
    {"DocumentFormat.OpenXml.Vml.Wordprocessing", "DocumentModel.Wordprocessing.Vml" },
    {"DocumentFormat.OpenXml.Wordprocessing", "DocumentModel.Wordprocessing" },
  };
  #endregion

  #region Properties

  public static SortedStrings ExcludedProperties { get; } = new SortedStrings
  {
    "FirstChild", "LastChild", "HasChildren", "InnerText", "InnerXml", "Features",
    "OpenXmlElementContext", "HasAttributes", "ExtendedAttributes", "ChildElements",
    "Parent", "NamespaceUri", "LocalName", "Prefix", "NamespaceDeclarations",
    "XmlQualifiedName", "XName", "OuterXml", "MCAttributes",
    "RootElement", "IsRootElementLoaded",
    "RelationshipErrorHandlerFactory",
    "AddError",
    "*Part",
    "HasValue",
    "OpenXmlPackage",
    "Container",
    "RootElementContext",
    "WebExtensions"
  };
  #endregion

  #region Types
  public static bool IsExcluded(Type type)
  {
    if (ExcludedNamespaces.Contains(type.Namespace ?? ""))
      return true;
    if (IncludedTypes.Contains(type.Name))
      return false;
    if (ExcludedTypes.Contains(type.Name))
      return true;
    return false;
  }

  public static SortedStrings ExcludedTypes { get; } = new SortedStrings
  {
    "SR", "*Reader", "*Attribute", "*Attributes", "*Extensions", "*Helper", "*Provider", "*Methods",
    "XmlConvertingReader*", "*.Part", "EnumInfoLookup`1", "MiscAttrContainer", "ModelElement", /*"HexWord",*/
    "OpenXmlElementContext",
    "OpenXmlElementList",
    "OpenXmlSimpleType",
    "OpenXmlPackage",
    //"OpenXml*",
  };

  public static SortedStrings IncludedTypes { get; } = new SortedStrings
  {
    "CustomXmlAttribute",
    "DocPart",
    //"Wordprocessing*",
    //"OpenXmlSolidColorFillPropertiesElement",
    //"OpenXmlValueColorEndPositionElement", "OpenXmlTaskAssignUnassignUserElement", "OpenXmlTaskUserElement",
    //"OpenXmlPartRootElement",
    //"OpenXmlFormulaElement",
  };

  public static SortedStrings ExcludedAttributes { get; } = new SortedStrings
  {
    "OfficeAvailability", "NullableContext", "SchemaAttr", "Nullable", "Serializable", 
    "DebuggerDisplay", "DebuggerNonUserCode", "CLSCompliant", "EditorBrowsable",
  };

  public static Dictionary<string, string> TypeNameConversion { get; } = new Dictionary<string, string>
  {
    //{ "DocumentFormat.OpenXml.Drawing.ShapeProperties", "DocumentModel.Drawings.ShapeProperties"},

    //{ "DocumentFormat.OpenXml.Office2010.Word.RunTrackChangeType", "DocumentModel.Wordprocessing.RunTrackChangeType2"},
    //{ "DocumentFormat.OpenXml.Office2013.Drawing.Chart.AxisDataSourceType", "DocumentModel.Drawings.AxisDataSourceType2"},
    //{ "DocumentFormat.OpenXml.Office2016.Drawing.ChartDrawing.TextBodyType", "DocumentModel.Drawings.TextBodyType2"},
    //{ "DocumentFormat.OpenXml.Office2013.Drawing.Chart.StringDataType", "DocumentModel.Drawings.StringDataType2"},
  };
  public static Dictionary<Type, Type> TypeConversionTable { get; } = new Dictionary<Type, Type>
  {
    { typeof(DocumentFormat.OpenXml.StringValue), typeof(System.String)},
    { typeof(DocumentFormat.OpenXml.BooleanValue), typeof(System.Boolean)},
    { typeof(DocumentFormat.OpenXml.OnOffValue), typeof(System.Boolean)},
    { typeof(DocumentFormat.OpenXml.Office2019.Drawing.Chart.BooleanFalse), typeof(System.Boolean) },
    { typeof(DocumentFormat.OpenXml.Office2010.ExcelAc.List), typeof(System.String) },
    { typeof(DocumentFormat.OpenXml.IntegerValue), typeof(System.Int32)},
    { typeof(DocumentFormat.OpenXml.Int32Value), typeof(System.Int32)},
    { typeof(DocumentFormat.OpenXml.UInt32Value), typeof(System.UInt32)},
    { typeof(DocumentFormat.OpenXml.Int16Value), typeof(System.Int16)},
    { typeof(DocumentFormat.OpenXml.UInt16Value), typeof(System.UInt16)},
    { typeof(DocumentFormat.OpenXml.Int64Value), typeof(System.Int64)},
    { typeof(DocumentFormat.OpenXml.UInt64Value), typeof(System.UInt16)},
    { typeof(DocumentFormat.OpenXml.ByteValue), typeof(System.Byte)},
    { typeof(DocumentFormat.OpenXml.SByteValue), typeof(System.SByte)},
    { typeof(DocumentFormat.OpenXml.SingleValue), typeof(System.Single)},
    { typeof(DocumentFormat.OpenXml.DoubleValue), typeof(System.Double)},
    { typeof(DocumentFormat.OpenXml.DecimalValue), typeof(System.Decimal)},
    { typeof(DocumentFormat.OpenXml.DateTimeValue), typeof(System.DateTime)},
    { typeof(DocumentFormat.OpenXml.OpenXmlElement), typeof(DocumentModel.ModelElement)},
    { typeof(DocumentFormat.OpenXml.OpenXmlLeafElement), typeof(System.Boolean)},
    { typeof(DocumentFormat.OpenXml.OpenXmlLeafTextElement), typeof(System.String)},
    { typeof(DocumentFormat.OpenXml.Wordprocessing.LongHexNumberType), typeof(DocumentModel.HexWord)},
    { typeof(DocumentFormat.OpenXml.EnumStringAttribute), typeof(System.Xml.Serialization.XmlEnumAttribute) },
    { typeof(DocumentFormat.OpenXml.ThreadSafeAttribute), typeof(DocumentModel.Attributes.ThreadSafeAttribute) },
    { typeof(DocumentFormat.OpenXml.OfficeAvailabilityAttribute), typeof(DocumentModel.Attributes.OfficeAvailabilityAttribute) },
    { typeof(DocumentFormat.OpenXml.KnownFeatureAttribute), typeof(DocumentModel.Attributes.KnownFeatureAttribute) },
    { typeof(DocumentFormat.OpenXml.DelegatedFeatureAttribute), typeof(DocumentModel.Attributes.DelegatedFeatureAttribute) },
    { typeof(DocumentFormat.OpenXml.ChildElementInfoAttribute), typeof(DocumentModel.Attributes.ChildElementInfoAttribute) },
    { typeof(DocumentFormat.OpenXml.SchemaAttrAttribute), typeof(DocumentModel.Attributes.SchemaAttrAttribute) },
    { typeof(DocumentFormat.OpenXml.Framework.ContentTypeAttribute), typeof(DocumentModel.Attributes.ContentMimeAttribute) },
    { typeof(DocumentFormat.OpenXml.Framework.RelationshipTypeAttribute), typeof(DocumentModel.Attributes.RelationshipUriAttribute) },
    { typeof(DocumentFormat.OpenXml.Framework.PartConstraintAttribute), typeof(DocumentModel.Attributes.PartConstraintAttribute) },
    { typeof(DocumentFormat.OpenXml.Framework.DataPartConstraintAttribute), typeof(DocumentModel.Attributes.DataPartConstraintAttribute) },
    { typeof(DocumentFormat.OpenXml.VariantTypes.ArrayBaseValues), typeof(DocumentModel.VariantTypes.ArrayBaseType)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VectorBaseValues), typeof(DocumentModel.VariantTypes.VectorBaseType)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.Variant), typeof(DocumentModel.VariantTypes.Variant)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTArray), typeof(DocumentModel.VariantTypes.VTArray)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTBlob), typeof(DocumentModel.VariantTypes.VTBlob)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTBString), typeof(DocumentModel.VariantTypes.VTString)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTByte), typeof(DocumentModel.VariantTypes.VTSignedByte)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTClassId), typeof(DocumentModel.VariantTypes.VTClassId)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTClipboardData), typeof(DocumentModel.VariantTypes.VTClipboardData)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTCurrency), typeof(DocumentModel.VariantTypes.VTCurrency)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTDate), typeof(DocumentModel.VariantTypes.VTDate)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTDecimal), typeof(DocumentModel.VariantTypes.VTDecimal)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTDouble), typeof(DocumentModel.VariantTypes.VTDouble)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTEmpty), typeof(DocumentModel.VariantTypes.VTEmpty)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTError), typeof(DocumentModel.VariantTypes.VTError)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTFileTime), typeof(DocumentModel.VariantTypes.VTDateTime)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTFloat), typeof(DocumentModel.VariantTypes.VTFloat)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTInt32), typeof(DocumentModel.VariantTypes.VTInt32)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTInt64), typeof(DocumentModel.VariantTypes.VTInt64)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTInteger), typeof(DocumentModel.VariantTypes.VTInt64)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTLPSTR), typeof(DocumentModel.VariantTypes.VTString)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTLPWSTR), typeof(DocumentModel.VariantTypes.VTString)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTNull), typeof(DocumentModel.VariantTypes.VTNull)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTOBlob), typeof(DocumentModel.VariantTypes.VTBlob)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTOStorage), typeof(DocumentModel.VariantTypes.VTStorage)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTOStreamData), typeof(DocumentModel.VariantTypes.VTStream)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTShort), typeof(DocumentModel.VariantTypes.VTShort)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTStorage), typeof(DocumentModel.VariantTypes.VTStorage)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTStreamData), typeof(DocumentModel.VariantTypes.VTStream)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTUnsignedByte), typeof(DocumentModel.VariantTypes.VTByte)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTUnsignedInt32), typeof(DocumentModel.VariantTypes.VTUnsignedInt32)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTUnsignedInt64), typeof(DocumentModel.VariantTypes.VTUnsignedInt64)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTUnsignedInteger), typeof(DocumentModel.VariantTypes.VTUnsignedInt64)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTUnsignedShort), typeof(DocumentModel.VariantTypes.VTUnsignedShort)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTVector), typeof(DocumentModel.VariantTypes.VTVector)},
    { typeof(DocumentFormat.OpenXml.VariantTypes.VTVStreamData), typeof(DocumentModel.VariantTypes.VTVStream)},
    { typeof(DocumentFormat.OpenXml.Base64BinaryValue), typeof(DocumentModel.Base64Binary)},
    { typeof(DocumentFormat.OpenXml.HexBinaryValue), typeof(DocumentModel.HexBinary)},
  };

  public static Dictionary<Type, string> BuiltInTypeNames { get; } = new Dictionary<Type, string>
  {
    { typeof(System.Object), "object" },
    { typeof(System.String), "string" },
    { typeof(System.Boolean), "bool" },
    { typeof(System.Int32), "int"},
    { typeof(System.UInt32), "uint"},
    { typeof(System.Int16), "short" },
    { typeof(System.UInt16), "ushort" },
    { typeof(System.Int64), "long" },
    { typeof(System.UInt64), "ulong" },
    { typeof(System.Byte), "byte" },
    { typeof(System.SByte), "sbyte" },
    { typeof(System.Single), "float" },
    { typeof(System.Double), "double" },
    { typeof(System.Decimal), "decimal" },
  };

  public static string[] SimpleTypeNames { get; } = new string[]
  {
    nameof(System.String),
    nameof(System.Boolean),
    nameof(System.Int32),
    nameof(System.UInt32),
    nameof(System.Int16),
    nameof(System.UInt16),
    nameof(System.Int64),
    nameof(System.UInt64),
    nameof(System.Byte),
    nameof(System.SByte),
    nameof(System.Single),
    nameof(System.Double),
    nameof(System.Decimal),
  };

  #endregion
}