namespace DocumentModel.Vml.Spreadsheet;

/// <summary>
/// Attached Object Data.
/// </summary>
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.ICommentRowTarget))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.ICommentColumnTarget))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IInputValidationType))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IMinDropDownWidth))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.ISelectionEntry))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IDropLines))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IChecked))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IScrollBarPosition))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IScrollBarMin))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IScrollBarMax))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IScrollBarIncrement))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IScrollBarPageIncrement))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IScrollBarWidth))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IScriptLanguage))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IScriptLocation))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IAnchor))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IHorizontalTextAlignment))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IVerticalTextAlignment))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IFormulaRange))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.ISelectionType))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IMultiSelections))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IListBoxCallbackType))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IListItem))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IDropStyle))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IFormulaLink))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IFormulaPicture))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IFormulaGroup))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IScriptText))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IScriptExtended))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IFormulaTextBox))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IAcceleratorPrimary))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IAcceleratorSecondary))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IClipboardFormat))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IFormulaMacro))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IMoveWithCells))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IResizeWithCells))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.ILocked))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IDefaultSize))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IPrintObject))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IDisabled))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IAutoFill))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IAutoLine))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IAutoSizePicture))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.ILockText))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IJustifyLastLine))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.ISecretEdit))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IDefaultButton))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IHelpButton))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.ICancelButton))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IDismissButton))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IVisible))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IRowHidden))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IColumnHidden))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IMultiLine))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IVerticalScrollBar))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IValidIds))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IDisable3DForListBoxAndDropDown))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IColored))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IDisable3D))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IFirstButton))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IHorizontalScrollBar))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IMapOcxControl))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.ICameraObject))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IRecalculateAlways))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IAutoScaleFont))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IDdeObject))]
[ChildElementInfo(typeof(DocumentModel.Vml.Spreadsheet.IUIObject))]
public interface IClientData // : DocumentFormat.OpenXml.TypedOpenXmlCompositeElement
{
  /// <summary>
  /// Object type
  /// </summary>
  public ObjectValues? ObjectType { get ; set; }
  
}
