global using System;
global using System.Collections;
global using System.Collections.ObjectModel;
global using System.Collections.Generic;
global using System.Collections.Specialized;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.IO;
global using System.IO.Packaging;
global using System.Linq;
global using System.Reflection;
global using System.Text;
global using System.Xml.Serialization;
global using Qhta.Conversion;
global using Qhta.TextUtils;
global using Qhta.TypeUtils;
global using Qhta.Xml;
global using Qhta.Xml.Serialization;
global using Newtonsoft.Json;
global using Newtonsoft.Json.Converters;

global using DM = DocumentModel;
//global using DMB = DocumentModel.Bibliography;
global using DMCX = DocumentModel.CustomXml;
global using DMD = DocumentModel.Drawings;
//global using DMDA = DocumentModel.Drawings.Animation;
//global using DMDA3D = DocumentModel.Drawings.Animation.Model3D;
global using DMDCD = DocumentModel.Drawings.ChartDrawing;
global using DMDCDs = DocumentModel.Drawings.ChartDrawings;
global using DMDC = DocumentModel.Drawings.Charts;
global using DMDCS = DocumentModel.Drawings.ChartsStyle;
global using DMDD1 = DocumentModel.Drawings.Diagram1;
//global using DMDD2 = DocumentModel.Drawings.Diagram2;
global using DMDD = DocumentModel.Drawings.Diagrams;
//global using DMDL = DocumentModel.Drawings.Legacy;
//global using DMDLCv = DocumentModel.Drawings.LockedCanvas;
//global using DMD3D = DocumentModel.Drawings.Model3D;
global using DMDO = DocumentModel.Drawings.Office;
global using DMDOOE = DocumentModel.Drawings.Office.OEmbed;
global using DMDOSL = DocumentModel.Drawings.Office.ScriptLink;
//global using DMDPc = DocumentModel.Drawings.Pictures;
//global using DMDSl = DocumentModel.Drawings.Slicer;
//global using DMDS = DocumentModel.Drawings.Spreadsheet;
global using DMDSVG = DocumentModel.Drawings.SVG;
global using DMDW = DocumentModel.Drawings.Wordprocessing;
//global using DME = DocumentModel.EMMA;
//global using DMF = DocumentModel.Framework;
global using DMM = DocumentModel.Math;
global using DMPack = DocumentModel.Packaging;
//global using DMPt = DocumentModel.Painting;
//global using DMP = DocumentModel.Presentation;
//global using DMPV = DocumentModel.Presentation.Vml;
global using DMPr = DocumentModel.Properties;
//global using DMP = DocumentModel;
//global using DMS = DocumentModel.Spreadsheet;
//global using DMSV = DocumentModel.Spreadsheet.Vml;
global using DMUI = DocumentModel.UI;
//global using DMVl = DocumentModel.Validation;
global using DMVT = DocumentModel.VariantTypes;
global using DMV = DocumentModel.Vml;
global using DMWE = DocumentModel.WebExtensions;
global using DMWEUI = DocumentModel.WebExtensions.UI;
global using DMW = DocumentModel.Wordprocessing;
//global using DMWDC = DocumentModel.Wordprocessing.DrawingCanvas;
global using DMWD = DocumentModel.Wordprocessing.Drawings;
//global using DMWDS = DocumentModel.Wordprocessing.DrawingShape;
global using DMWOE = DocumentModel.Wordprocessing.OEmbed;
global using DMWV = DocumentModel.Wordprocessing.Vml;
