global using System;
global using System.Collections;
global using System.Collections.ObjectModel;
global using System.Collections.Generic;
global using System.Collections.Specialized;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.Globalization;
global using System.IO;
global using System.IO.Packaging;
global using System.Linq;
global using System.Reflection;
global using System.Text;
global using System.Xml.Serialization;
global using Qhta.Conversion;
global using Qhta.TextUtils;
global using Qhta.TypeUtils;
global using Qhta.Xml;
global using Qhta.Xml.Serialization;
global using Newtonsoft.Json;
global using Newtonsoft.Json.Converters;

global using DM = DocumentModel;
//global using DMBib = DocumentModel.Bibliography;
global using DMCustXml = DocumentModel.CustomXml;
global using DMDraws = DocumentModel.Drawings;
//global using DMDrawsAnim = DocumentModel.Drawings.Animation;
//global using DMDrawsAnim3D = DocumentModel.Drawings.Animation.Model3D;
global using DMDrawsChartDraw = DocumentModel.Drawings.ChartDrawing;
global using DMDrawsChartDraws = DocumentModel.Drawings.ChartDrawings;
global using DMDrawsCharts = DocumentModel.Drawings.Charts;
global using DMDrawsChartsStyle = DocumentModel.Drawings.ChartsStyle;
global using DMDrawsDgm1 = DocumentModel.Drawings.Diagram1;
global using DMDrawsDgm2 = DocumentModel.Drawings.Diagram2;
global using DMDrawsDgms = DocumentModel.Drawings.Diagrams;
//global using DMDrawsLegacy = DocumentModel.Drawings.Legacy;
//global using DMDrawsLockCanv = DocumentModel.Drawings.LockedCanvas;
//global using DMDraws3D = DocumentModel.Drawings.Model3D;
global using DMDrawsO = DocumentModel.Drawings.Office;
global using DMDrawsOOEmb = DocumentModel.Drawings.Office.OEmbed;
global using DMDrawsOScptLnk = DocumentModel.Drawings.Office.ScriptLink;
//global using DMDrawsPict = DocumentModel.Drawings.Pictures;
//global using DMDrawsSlicer = DocumentModel.Drawings.Slicer;
//global using DMDrawsS = DocumentModel.Drawings.Spreadsheet;
global using DMDrawsSVG = DocumentModel.Drawings.SVG;
global using DMDrawsW = DocumentModel.Drawings.Wordprocessing;
//global using DMEMMA = DocumentModel.EMMA;
//global using DMFwork = DocumentModel.Framework;
global using DMM = DocumentModel.Math;
global using DMPack = DocumentModel.Packaging;
//global using DMPainting = DocumentModel.Painting;
//global using DMP = DocumentModel.Presentation;
//global using DMPVml = DocumentModel.Presentation.Vml;
global using DMProps = DocumentModel;
//global using DMProps = DocumentModel;
//global using DMS = DocumentModel.Spreadsheet;
//global using DMSVml = DocumentModel.Spreadsheet.Vml;
global using DMUI = DocumentModel.UI;
//global using DMValid = DocumentModel.Validation;
global using DMVT = DocumentModel.VariantTypes;
global using DMVml = DocumentModel.Vml;
global using DMWebExt = DocumentModel.WebExtensions;
global using DMWebExtUI = DocumentModel.WebExtensions.UI;
global using DMW = DocumentModel.Wordprocessing;
//global using DMWDrawCnv = DocumentModel.Wordprocessing.DrawingCanvas;
global using DMWDraws = DocumentModel.Wordprocessing.Drawings;
//global using DMWDrawShp = DocumentModel.Wordprocessing.DrawingShape;
global using DMWOEmb = DocumentModel.Wordprocessing.OEmbed;
global using DMWVml = DocumentModel.Wordprocessing.Vml;
