<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="LineProperties.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\NamespaceMappings\OpenXmlUsings.cs" Link="OpenXmlUsings.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutoEditLib\AutoEditLib.csproj" />
  </ItemGroup>

</Project>
