namespace DocumentModel.Interop.Core;

/// <summary>
/// Specifies properties of a signature.
/// </summary>
/// <remarks>
/// See `https://learn.microsoft.com/en-us/dotnet/api/microsoft.office.core.signaturetype?view=office-pia` for Office interop details.
/// </remarks>
[OfficeInteropEnumType("SignatureType")]
public enum SignatureType
{
  /// <summary>
  /// A signature not generated by Office.
  /// </summary>
  [OfficeInteropEnumValue("sigtypeUnknown")]
  Unknown,
  /// <summary>
  /// A signature that is not visible in the content of the document.
  /// </summary>
  [OfficeInteropEnumValue("sigtypeNonVisible")]
  NonVisible,
  /// <summary>
  /// A signature that is visible in the content of the document.
  /// </summary>
  [OfficeInteropEnumValue("sigtypeSignatureLine")]
  SignatureLine,
  /// <summary>
  /// Specifies the maximum number of the signature types available in the current version of Office.
  /// </summary>
  [OfficeInteropEnumValue("sigtypeMax")]
  Max
}
