namespace DocumentModel.Interop.Core;

/// <summary>
/// Specifies properties of a signature.
/// </summary>
public enum SignatureType
{
  /// <summary>
  /// A signature not generated by Office. sigtypeNonVisible1 A signature that is not visible in the content of the
  /// document. sigtypeSignatureLine2 A signature that is visible in the content of the document.
  /// </summary>
  Unknown,
  /// <summary>
  /// Specifies properties of a signature.
  /// </summary>
  NonVisible,
  /// <summary>
  /// Specifies properties of a signature.
  /// </summary>
  SignatureLine,
  /// <summary>
  /// Specifies the maximum number of the signature types available in the current version of Office.
  /// </summary>
  Max
}
