//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocxEd {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocxEd.CommonStrings", typeof(CommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted types.
        /// </summary>
        public static string AcceptedTypes {
            get {
                return ResourceManager.GetString("AcceptedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add docs.
        /// </summary>
        public static string AddDocs {
            get {
                return ResourceManager.GetString("AddDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adding docs to {0} of {1} types, added to {2} types.
        /// </summary>
        public static string adding_docs_0_of_1_types_added_to_2_types {
            get {
                return ResourceManager.GetString("adding_docs_0_of_1_types_added_to_2_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All types.
        /// </summary>
        public static string AllTypes {
            get {
                return ResourceManager.GetString("AllTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checked {0} of {1} types.
        /// </summary>
        public static string checked_0_of_1_types {
            get {
                return ResourceManager.GetString("checked_0_of_1_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked types.
        /// </summary>
        public static string CheckedTypes {
            get {
                return ResourceManager.GetString("CheckedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code output path not defined.
        /// </summary>
        public static string Code_output_path_not_defined {
            get {
                return ResourceManager.GetString("Code_output_path_not_defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeCompilation.
        /// </summary>
        public static string CodeCompilation {
            get {
                return ResourceManager.GetString("CodeCompilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation error list.
        /// </summary>
        public static string CompilationErrorList {
            get {
                return ResourceManager.GetString("CompilationErrorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation errors.
        /// </summary>
        public static string CompilationErrors {
            get {
                return ResourceManager.GetString("CompilationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted types.
        /// </summary>
        public static string ConvertedTypes {
            get {
                return ResourceManager.GetString("ConvertedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to converting {0} of {1} types, converted {2} types.
        /// </summary>
        public static string converting_0_of_1_types_converted_2_types {
            get {
                return ResourceManager.GetString("converting_0_of_1_types_converted_2_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert types.
        /// </summary>
        public static string ConvertTypes {
            get {
                return ResourceManager.GetString("ConvertTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of phase {0}.
        /// </summary>
        public static string End_of_phase_0 {
            get {
                return ResourceManager.GetString("End_of_phase_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final check.
        /// </summary>
        public static string FinalCheck {
            get {
                return ResourceManager.GetString("FinalCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed properties.
        /// </summary>
        public static string FixedProperties {
            get {
                return ResourceManager.GetString("FixedProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed types.
        /// </summary>
        public static string FixedTypes {
            get {
                return ResourceManager.GetString("FixedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate code.
        /// </summary>
        public static string GenerateCode {
            get {
                return ResourceManager.GetString("GenerateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to generated {0} of {1} types in {2} namespaces.
        /// </summary>
        public static string generated_0_of_1_types_in_2_namespaces {
            get {
                return ResourceManager.GetString("generated_0_of_1_types_in_2_namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation file list.
        /// </summary>
        public static string GeneratedFileList {
            get {
                return ResourceManager.GetString("GeneratedFileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation files.
        /// </summary>
        public static string GeneratedFiles {
            get {
                return ResourceManager.GetString("GeneratedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated types.
        /// </summary>
        public static string GeneratedTypes {
            get {
                return ResourceManager.GetString("GeneratedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator type constructor not found.
        /// </summary>
        public static string Generator_type_constructor_not_found {
            get {
                return ResourceManager.GetString("Generator_type_constructor_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator type not defined.
        /// </summary>
        public static string Generator_type_not_defined {
            get {
                return ResourceManager.GetString("Generator_type_not_defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator type not found.
        /// </summary>
        public static string Generator_type_not_found {
            get {
                return ResourceManager.GetString("Generator_type_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in {0} namespaces.
        /// </summary>
        public static string in_0_namespaces {
            get {
                return ResourceManager.GetString("in_0_namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input name not defined.
        /// </summary>
        public static string Input_assembly_not_defined {
            get {
                return ResourceManager.GetString("Input_assembly_not_defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid properties.
        /// </summary>
        public static string InvalidProperties {
            get {
                return ResourceManager.GetString("InvalidProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidTypes.
        /// </summary>
        public static string InvalidTypes {
            get {
                return ResourceManager.GetString("InvalidTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model configuration is not defined..
        /// </summary>
        public static string Model_configuration_not_defined {
            get {
                return ResourceManager.GetString("Model_configuration_not_defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process cancelled.
        /// </summary>
        public static string ProcessCancelled {
            get {
                return ResourceManager.GetString("ProcessCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process continuation.
        /// </summary>
        public static string ProcessContinue {
            get {
                return ResourceManager.GetString("ProcessContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process finished.
        /// </summary>
        public static string ProcessFinished {
            get {
                return ResourceManager.GetString("ProcessFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start processing.
        /// </summary>
        public static string ProcessStart {
            get {
                return ResourceManager.GetString("ProcessStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name not defined.
        /// </summary>
        public static string Project_name_not_defined {
            get {
                return ResourceManager.GetString("Project_name_not_defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registered {0} of {1} types in {2} namespaces.
        /// </summary>
        public static string registered_0_of_1_types_in_2_namespaces {
            get {
                return ResourceManager.GetString("registered_0_of_1_types_in_2_namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registed types.
        /// </summary>
        public static string RegisteredTypes {
            get {
                return ResourceManager.GetString("RegisteredTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected types.
        /// </summary>
        public static string RejectedTypes {
            get {
                return ResourceManager.GetString("RejectedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed properties.
        /// </summary>
        public static string RemovedProperties {
            get {
                return ResourceManager.GetString("RemovedProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renamed types.
        /// </summary>
        public static string RenamedTypes {
            get {
                return ResourceManager.GetString("RenamedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename types.
        /// </summary>
        public static string RenameTypes {
            get {
                return ResourceManager.GetString("RenameTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to renaming {0} of {1} types, renamed {2} types.
        /// </summary>
        public static string renaming_0_of_1_types_renamed_2_types {
            get {
                return ResourceManager.GetString("renaming_0_of_1_types_renamed_2_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan type name not defined.
        /// </summary>
        public static string Scan_type_name_not_defined {
            get {
                return ResourceManager.GetString("Scan_type_name_not_defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned {0} namespaces.
        /// </summary>
        public static string Scanned_0_Namespaces {
            get {
                return ResourceManager.GetString("Scanned_0_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan source.
        /// </summary>
        public static string ScanSource {
            get {
                return ResourceManager.GetString("ScanSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution name not defined.
        /// </summary>
        public static string Solution_name_not_defined {
            get {
                return ResourceManager.GetString("Solution_name_not_defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of phase {0}.
        /// </summary>
        public static string Start_of_phase_0 {
            get {
                return ResourceManager.GetString("Start_of_phase_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target namespaces.
        /// </summary>
        public static string TargetNamespacesOnly {
            get {
                return ResourceManager.GetString("TargetNamespacesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target types.
        /// </summary>
        public static string TargetTypesOnly {
            get {
                return ResourceManager.GetString("TargetTypesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time:.
        /// </summary>
        public static string time_ {
            get {
                return ResourceManager.GetString("time_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total time.
        /// </summary>
        public static string TotalTime {
            get {
                return ResourceManager.GetString("TotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types with added description.
        /// </summary>
        public static string TypesWithAddedDescription {
            get {
                return ResourceManager.GetString("TypesWithAddedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types with description.
        /// </summary>
        public static string TypesWithDescription {
            get {
                return ResourceManager.GetString("TypesWithDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types with meaningless description.
        /// </summary>
        public static string TypesWithMeaninglessDescription {
            get {
                return ResourceManager.GetString("TypesWithMeaninglessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types without description.
        /// </summary>
        public static string TypesWithoutDescription {
            get {
                return ResourceManager.GetString("TypesWithoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types with same name.
        /// </summary>
        public static string TypesWithSameName {
            get {
                return ResourceManager.GetString("TypesWithSameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validated types.
        /// </summary>
        public static string ValidatedTypes {
            get {
                return ResourceManager.GetString("ValidatedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid types.
        /// </summary>
        public static string ValidTypes {
            get {
                return ResourceManager.GetString("ValidTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verifying {0} of {1} types, invalid {2} types.
        /// </summary>
        public static string verifying_0_of_1_types_invalid_2_types {
            get {
                return ResourceManager.GetString("verifying_0_of_1_types_invalid_2_types", resourceCulture);
            }
        }
    }
}
