<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <RootNamespace>DocumentModel</RootNamespace>
    <Description>Definition of document model based on OpenXML</Description>
    <Authors>Yarreck Qhta</Authors>
    <Version>1.0</Version>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <DocumentationFile>docs\DocumentMode.Interfaces.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;8766;0618,1584</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;8766;0618,1584</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove=".github\**" />
    <EmbeddedResource Remove=".github\**" />
    <None Remove=".github\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Application\DispObjs\_IMsoDispObj.Inheritance.cs" />
    <Compile Remove="Wordprocessing\Documents\Document.Methods.cs" />
    <Compile Remove="Wordprocessing\Fonts\TextFormat.Methods.cs" />
    <Compile Remove="Wordprocessing\Fonts\TextFormat2.cs" />
    <Compile Remove="Wordprocessing\Settings\Options.SpellChecking.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DeepEqual" Version="5.1.0" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.4.1" />
    <PackageReference Include="DocumentFormat.OpenXml.Framework" Version="3.4.1" />
    <PackageReference Include="Qhta.Collections" Version="5.4.0" />
    <PackageReference Include="Qhta.Xml" Version="3.3.0" />
    <PackageReference Include="Qhta.Xml.Serialization" Version="4.2.0" />
    <PackageReference Include="System.IO.Packaging" Version="10.0.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DocumentModel.BaseConverters\DocumentModel.BaseConverters.csproj" />
    <ProjectReference Include="..\DocumentModel.BaseTypes\DocumentModel.BaseTypes.csproj" />
    <ProjectReference Include="..\DocumentModel.EnumTypes\DocumentModel.EnumTypes.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\..\Scripts\UpdateXmlComments.py" Link="Scripts\UpdateXmlComments.py" />
    <None Include="..\..\..\Scripts\RemoveTypeNamesFromEnums.py" Link="Scripts\RemoveTypeNamesFromEnums.py" />
    <None Include="..\..\..\Scripts\TrimEnumFieldNames.py" Link="Scripts\TrimEnumFieldNames.py" />
    <None Include="..\..\..\Scripts\CompareEnumTypes.py" Link="Scripts\CompareEnumTypes.py" />
    <None Include="..\..\..\Scripts\AddPiaCoreLink.py" Link="Scripts\AddPiaCoreLink.py" />
    <None Include="..\..\..\Scripts\AddPiaWordLink.py" Link="Scripts\AddPiaWordLink.py" />
    <None Include="..\..\..\Scripts\RenameInterfaces.py" Link="Scripts\RenameInterfaces.py" />
  </ItemGroup>
</Project>