<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <GenerateDocumentationFile>False</GenerateDocumentationFile>
    <RootNamespace>DocumentModel</RootNamespace>
    <Description>Definition of document model based on OpenXML</Description>
    <Authors>Yarreck Qhta</Authors>
    <Version>1.0</Version>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;8766;0618</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;8766;0618</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Drawings.Charts\Classes\**" />
    <Compile Remove="Properties\Classes\**" />
    <Compile Remove="Settings\**" />
    <EmbeddedResource Remove="Drawings.Charts\Classes\**" />
    <EmbeddedResource Remove="Properties\Classes\**" />
    <EmbeddedResource Remove="Settings\**" />
    <None Remove="Drawings.Charts\Classes\**" />
    <None Remove="Properties\Classes\**" />
    <None Remove="Settings\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="CustomUI\DropDownRegular.cs" />
    <Compile Remove="CustomUI\DynamicMenu.cs" />
    <Compile Remove="CustomUI\DynamicMenuRegular.cs" />
    <Compile Remove="CustomUI\EditBox.cs" />
    <Compile Remove="CustomUI\Gallery.cs" />
    <Compile Remove="CustomUI\GalleryRegular.cs" />
    <Compile Remove="CustomUI\Group.cs" />
    <Compile Remove="CustomUI\GroupBox.cs" />
    <Compile Remove="CustomUI\Menu.cs" />
    <Compile Remove="CustomUI\MenuRegular.cs" />
    <Compile Remove="CustomUI\MenuSeparator.cs" />
    <Compile Remove="CustomUI\RadioGroup.cs" />
    <Compile Remove="CustomUI\Separator.cs" />
    <Compile Remove="CustomUI\ToggleButton.cs" />
    <Compile Remove="CustomUI\ToggleButtonRegular.cs" />
    <Compile Remove="Math\Classes\OfficeMathArgumentType.cs" />
    <Compile Remove="Properties\DigitalSignature.cs" />
    <Compile Remove="Properties\VectorVariantType.cs" />
    <Compile Remove="Wordprocessing\Document\Document.ext.cs" />
    <Compile Remove="Wordprocessing\Enums\DocumentProtectionKind.cs" />
    <Compile Remove="Wordprocessing\Abstract interfaces\ICommonRunContent.cs" />
    <Compile Remove="Wordprocessing\Run properties\DualBoolTypeConverter.cs" />
    <Compile Remove="Wordprocessing\Table properties\ConditionalFormatStyle.cs" />
    <Compile Remove="Wordprocessing\Table properties\ConditionalFormatStyleTypeConverter.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DeepEqual" Version="5.1.0" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.3.0" />
    <PackageReference Include="Microsoft.Office.Interop.Word" Version="15.0.4797.1004" />
    <PackageReference Include="Qhta.TypeUtils" Version="1.5.0" />
    <PackageReference Include="Qhta.Xml" Version="3.2.0" />
    <PackageReference Include="Qhta.Xml.Serialization" Version="4.2.0" />
    <PackageReference Include="System.IO.Packaging" Version="10.0.1" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Drawings.Office.ScriptLink\Classes\" />
    <Folder Include="Drawings\Enums\" />
    <Folder Include="Office.Drawing\" />
    <Folder Include="Office2013.Word.Drawing\" />
    <Folder Include="Vml\Classes\" />
  </ItemGroup>
  <ItemGroup>
    <None Include="CustomUI\Ribbon\TabSetCollectioncs.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DocumentModel.BaseTypes\DocumentModel.BaseTypes.csproj" />
  </ItemGroup>
</Project>