<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <DocumentationFile>docs\BaseConvertes.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AlternateContentChoiceConverter.cs" />
    <Compile Remove="AlternateContentConverter.cs" />
    <Compile Remove="AlternateContentFallbackConverter.cs" />
    <Compile Remove="ElementCollectionConverter%28E,T%29.cs" />
    <Compile Remove="ElementCollectionConverter%28T%29.cs" />
    <Compile Remove="IdPartPairConverter.cs" />
    <Compile Remove="Int64ValueConverter.cs" />
    <Compile Remove="ModelElementConverter.cs" />
    <Compile Remove="ModelObjectComparer.cs" />
    <Compile Remove="NumericValueConverter.cs" />
    <Compile Remove="OnOffConverter.cs" />
    <Compile Remove="OnOffToggleConverter.cs" />
    <Compile Remove="OpenXmlPackageConverter.cs" />
    <Compile Remove="OpenXmlPartConverter.cs" />
    <Compile Remove="ReferenceConverter.cs" />
    <Compile Remove="ReferenceRelationshipConverter.cs" />
    <Compile Remove="SimpleValueConverter - Copy.cs" />
    <Compile Remove="VariantConverter - Copy.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\NamespaceMappings\OpenXmlUsings.cs" Link="OpenXmlUsings.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
    <PackageReference Include="DocumentFormat.OpenXml.Framework" Version="3.5.1" />
    <PackageReference Include="Qhta.Collections" Version="5.4.0" />
    <PackageReference Include="Qhta.TypeUtils" Version="1.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DocumentModel.BaseTypes\DocumentModel.BaseTypes.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Schema\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Schema\dc.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Schema\dcmitype.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Schema\dcterms.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Schema\dml-chart.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Schema\dml-chartDrawing.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Schema\dml-diagram.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Schema\dml-lockedCanvas.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Schema\dml-main.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Schema\dml-picture.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Schema\dml-spreadsheetDrawing.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Schema\dml-wordprocessingDrawing.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Schema\opc-contentTypes.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Schema\opc-coreProperties.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Schema\opc-digSig.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Schema\opc-relationships.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Schema\pml.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Schema\shared-additionalCharacteristics.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Schema\shared-bibliography.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Schema\shared-commonSimpleTypes.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Schema\shared-customXmlDataProperties.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Schema\shared-customXmlSchemaProperties.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Schema\shared-documentPropertiesCustom.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Schema\shared-documentPropertiesExtended.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Schema\shared-documentPropertiesVariantTypes.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Schema\shared-math.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Schema\shared-relationshipReference.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Schema\sml.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Schema\wml.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Schema\xml.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
