using System.Windows.Controls;
using System.Windows.Data;

namespace ModelGenApp.Views;
/// <summary>
/// Interaction logic for TypeListView.xaml
/// </summary>
public partial class TypeListView : UserControl
{
  public TypeListView()
  {
    InitializeComponent();
  }

  private void DataGrid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
  {
    var items = (sender as DataGrid)?.ItemsSource;
    if (items != null)
    {
      var itemsType = items.GetType();
      if (itemsType.IsEnumerable(out var itemType))
      {
        var prop = itemType.GetProperty(e.PropertyName);
        if (prop != null)
        {
          var dataGridColumnAttr = prop.GetCustomAttribute<DataGridColumnAttribute>();
          if (dataGridColumnAttr != null)
          {
            if (!dataGridColumnAttr.IsAutoGenerated)
              e.Cancel = true;
            else
            {
              if (dataGridColumnAttr.Header != null)
                e.Column.Header = dataGridColumnAttr.Header;
              if (dataGridColumnAttr.HeaderStringFormat != null)
                e.Column.HeaderStringFormat = dataGridColumnAttr.HeaderStringFormat;
              var b = dataGridColumnAttr.IsReadOnly;
              if (b != null)
                e.Column.IsReadOnly = (bool)b;
              e.Column.MaxWidth = dataGridColumnAttr.MaxWidth;
              e.Column.MinWidth = dataGridColumnAttr.MinWidth;
              var d = dataGridColumnAttr.Width;
              if (d != null)
                e.Column.Width = (double)d;
              e.Column.CanUserReorder = dataGridColumnAttr.CanUserReorder;
              e.Column.CanUserResize = dataGridColumnAttr.CanUserResize;
              e.Column.CanUserSort = dataGridColumnAttr.CanUserSort;
              e.Column.SortMemberPath = dataGridColumnAttr.SortMemberPath;
              e.Column.SortDirection = dataGridColumnAttr.SortDirection;
              var s = dataGridColumnAttr.ClipboardContentPath;
              if (s != null)
                e.Column.ClipboardContentBinding = new Binding(s);
              var n = dataGridColumnAttr.DisplayIndex;
              if (n != null)
                e.Column.DisplayIndex = (int)n;
              n = (int)Convert.ChangeType(dataGridColumnAttr.Visibility, typeof(int));
              e.Column.Visibility = (System.Windows.Visibility)Enum.ToObject(typeof(System.Windows.Visibility), n);
            }
          }
        }
      }
    }
  }
}
