global using DM = DocumentModel;
global using DocumentModel.Attributes;
global using DMCP = DocumentModel.CustomProperties;
global using DMCUI = DocumentModel.CustomUI;
global using DMCUI10 = DocumentModel.CustomUI10;
global using DMCX = DocumentModel.CustomXml;
global using DMD = DocumentModel.Drawings;
global using DMDCD = DocumentModel.Drawings.ChartDrawing;
global using DMDCD10 = DocumentModel.Drawings.ChartDrawings10;
global using DMDCD16 = DocumentModel.Drawings.ChartDrawings16;
global using DMDC = DocumentModel.Drawings.Charts;
global using DMDC10 = DocumentModel.Drawings.Charts10;
global using DMDC13 = DocumentModel.Drawings.Charts13;
global using DMDCS = DocumentModel.Drawings.ChartsStyle;
global using DMDD1 = DocumentModel.Drawings.Diagram1;
global using DMDD2 = DocumentModel.Drawings.Diagram2;
global using DMDD = DocumentModel.Drawings.Diagrams;
global using DMDIF = DocumentModel.Drawings.ImageFormula;
global using DMDOE = DocumentModel.Drawings.OEmbed;
global using DMDO = DocumentModel.Drawings.Office;
global using DMDSL = DocumentModel.Drawings.ScriptLink;
global using DMDSS = DocumentModel.Drawings.SketchyShapes;
global using DMDSVG = DocumentModel.Drawings.SVG;
global using DMDW = DocumentModel.Drawings.Wordprocessing;
global using DMD10 = DocumentModel.Drawings10;
global using DMEP = DocumentModel.ExtendedProperties;
global using DMM = DocumentModel.Math;
global using DMPACK = DocumentModel.Packaging;
global using DMT = DocumentModel.Theme;
global using DMVML = DocumentModel.Vml;
global using DMEX = DocumentModel.WebExtensions;
global using DMWEP = DocumentModel.WebExtensionsPane;
global using DMW10 = DocumentModel.Word10;
global using DMW13 = DocumentModel.Word13;
global using DMW20 = DocumentModel.Word20;
global using DMW = DocumentModel.Wordprocessing;
global using DMWD = DocumentModel.Wordprocessing.Drawings;
global using System;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.Text;
