global using DX = DocumentFormat.OpenXml;
global using System;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.Text;
global using System.ComponentModel;
global using System.Runtime.Serialization;
global using DocumentModel.Attributes;
global using DM = DocumentModel;
global using DocumentModel.OpenXml;
global using DMVT = DocumentModel.VariantTypes;
global using DXVT = DocumentFormat.OpenXml.VariantTypes;
global using DXW = DocumentFormat.OpenXml.Wordprocessing;
global using DXO21DT = DocumentFormat.OpenXml.Office2021.DocumentTasks;
global using DXO13DCS = DocumentFormat.OpenXml.Office2013.Drawing.ChartStyle;
global using DMDCS = DocumentModel.Drawings.ChartsStyle;
global using DXO16DCD = DocumentFormat.OpenXml.Office2016.Drawing.ChartDrawing;
global using DMDCD16 = DocumentModel.Drawings.ChartDrawings16;
global using DXD = DocumentFormat.OpenXml.Drawing;
global using DMD = DocumentModel.Drawings;
global using DXDC = DocumentFormat.OpenXml.Drawing.Charts;
global using DMDC = DocumentModel.Drawings.Charts;
global using DXCXDP = DocumentFormat.OpenXml.CustomXmlDataProperties;
global using DMCX = DocumentModel.CustomXml;
global using DXDDD = DocumentFormat.OpenXml.Drawing.Diagrams;
global using DMDD = DocumentModel.Drawings.Diagrams;
global using DXOD = DocumentFormat.OpenXml.Office.Drawing;
global using DMDO = DocumentModel.Drawings.Office;
global using DXO21WCE = DocumentFormat.OpenXml.Office2021.Word.CommentsExt;
global using DXO19WC = DocumentFormat.OpenXml.Office2019.Word.Cid;
global using DMW = DocumentModel.Wordprocessing;
global using DXV = DocumentFormat.OpenXml.Vml;
global using DXVO = DocumentFormat.OpenXml.Vml.Office;
global using DMVML = DocumentModel.Vml;
global using DXO13W = DocumentFormat.OpenXml.Office2013.Word;
global using DMW13 = DocumentModel.Word13;
global using DXEP = DocumentFormat.OpenXml.ExtendedProperties;
global using DMEP = DocumentModel.ExtendedProperties;
global using DXOCUI = DocumentFormat.OpenXml.Office.CustomUI;
global using DMCUI = DocumentModel.CustomUI;
global using DXO10CUI = DocumentFormat.OpenXml.Office2010.CustomUI;
global using DMCUI10 = DocumentModel.CustomUI10;
global using DXO13WEP = DocumentFormat.OpenXml.Office2013.WebExtentionPane;
global using DMWEP = DocumentModel.WebExtensionsPane;
global using DXO13WE = DocumentFormat.OpenXml.Office2013.WebExtension;
global using DMEX = DocumentModel.WebExtensions;
