var test = new DocxDocument.Test.ReadWriteTest();
test.Output = Console.Out;
test.Initialize();
Console.WriteLine($"Opening directory: {test.SamplesPath}");
Console.WriteLine();
//test.TestOpen();
test.TestCreate();
test.TestCopyProperties();
//test.TestReadProperties();
//test.TestReadSettings();
