public AlignBorderAndEdges? AlignBorderAndEdges { get; set; }
public BordersDoNotSurroundFooter? BordersDoNotSurroundFooter { get; set; }
public BordersDoNotSurroundHeader? BordersDoNotSurroundHeader { get; set; }
public DisplayBackgroundShape? DisplayBackgroundShape { get; set; }
public DoNotDisplayPageBoundaries? DoNotDisplayPageBoundaries { get; set; }
public EmbedSystemFonts? EmbedSystemFonts { get; set; }
public EmbedTrueTypeFonts? EmbedTrueTypeFonts { get; set; }
public GutterAtTop? GutterAtTop { get; set; }
public HideGrammaticalErrors? HideGrammaticalErrors { get; set; }
public HideSpellingErrors? HideSpellingErrors { get; set; }
public MirrorMargins? MirrorMargins { get; set; }
public PrintFormsData? PrintFormsData { get; set; }
public PrintFractionalCharacterWidth? PrintFractionalCharacterWidth { get; set; }
public PrintPostScriptOverText? PrintPostScriptOverText { get; set; }
public RemoveDateAndTime? RemoveDateAndTime { get; set; }
public RemovePersonalInformation? RemovePersonalInformation { get; set; }
public SaveFormsData? SaveFormsData { get; set; }
public SaveSubsetFonts? SaveSubsetFonts { get; set; }
public View? View { get; set; }
public WriteProtection? WriteProtection { get; set; }
public Zoom? Zoom { get; set; }
