<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net4.8;net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Core\TaskPanes\" />
    <Folder Include="Word\AutoCorrect\" />
    <Folder Include="Word\Bibliography\" />
    <Folder Include="Word\Bookmarks\" />
    <Folder Include="Word\Breaks\" />
    <Folder Include="Word\BuildingBlocks\" />
    <Folder Include="Word\Captions\" />
    <Folder Include="Word\CoAuthoring\" />
    <Folder Include="Word\Common\" />
    <Folder Include="Word\ContentControls\" />
    <Folder Include="Word\CustomXml\" />
    <Folder Include="Word\Dictionaries\" />
    <Folder Include="Word\Document\" />
    <Folder Include="Word\Drawings\" />
    <Folder Include="Word\Editors\" />
    <Folder Include="Word\Fields\" />
    <Folder Include="Word\Find and replace\" />
    <Folder Include="Word\Fonts\" />
    <Folder Include="Word\Footnotes and endnotes\" />
    <Folder Include="Word\FormFields\" />
    <Folder Include="Word\Frames and framesets\" />
    <Folder Include="Word\Headers and footers\" />
    <Folder Include="Word\Indexes\" />
    <Folder Include="Word\Info\" />
    <Folder Include="Word\InlineShapes\" />
    <Folder Include="Word\KeyBindings\" />
    <Folder Include="Word\Lists\" />
    <Folder Include="Word\Math\" />
    <Folder Include="Word\Numbering\" />
    <Folder Include="Word\Pages\" />
    <Folder Include="Word\Paragraph properties\" />
    <Folder Include="Word\Ranges\" />
    <Folder Include="Word\Revisions\" />
    <Folder Include="Word\Ruby\" />
    <Folder Include="Word\Run content\" />
    <Folder Include="Word\Run properties\" />
    <Folder Include="Word\Sdt\" />
    <Folder Include="Word\Settings\" />
    <Folder Include="Word\SmartTags\" />
    <Folder Include="Word\Styles\" />
    <Folder Include="Word\Table properties\" />
    <Folder Include="Word\TableOf\" />
    <Folder Include="Word\Tables\" />
    <Folder Include="Word\Versioning\" />
    <Folder Include="Word\Views\" />
    <Folder Include="Word\Vml\" />
    <Folder Include="Word\Windows\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Office.Interop.Word" Version="15.0.4797.1004" />
    <PackageReference Include="MicrosoftOfficeCore" Version="15.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DocumentModel.Attributes\DocumentModel.Attributes.csproj" />
  </ItemGroup>

</Project>
