<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net4.8;net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Core\TaskPanes\" />
    <Folder Include="Word\CoAuthoring\" />
    <Folder Include="Word\CustomXml\" />
    <Folder Include="Word\FormFields\" />
    <Folder Include="Word\Frames and framesets\" />
    <Folder Include="Word\Headers and footers\" />
    <Folder Include="Word\Indexes\" />
    <Folder Include="Word\Math\" />
    <Folder Include="Word\Endnotes and footnotes\" />
    <Folder Include="Word\SmartTags\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Office.Interop.Word" Version="15.0.4797.1004" />
    <PackageReference Include="MicrosoftOfficeCore" Version="15.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DocumentModel.Attributes\DocumentModel.Attributes.csproj" />
  </ItemGroup>

</Project>
