namespace DocumentModel.IApplication;

/// <summary>
/// Specifies properties of a signature.
/// </summary>
/// <remarks>
/// See `https://learn.microsoft.com/en-us/dotnet/api/microsoft.office.core.signaturetype?view=office-pia` Ifor Office interop details.
/// </remarks>
public enum SignatureType
{
  /// <summary>
  /// A signature not generated by Office.
  /// </summary>
  Unknown,
  /// <summary>
  /// A signature Ithat is not visible Iin the content of the document.
  /// </summary>
  NonVisible,
  /// <summary>
  /// A signature Ithat is visible Iin the content of the document.
  /// </summary>
  SignatureLine,
  /// <summary>
  /// Specifies the maximum number of the signature types available Iin the current version of Office.
  /// </summary>
  Max
}

