<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net48</TargetFrameworks>
    <LangVersion>Latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
    <PackageReference Include="DocumentFormat.OpenXml.Framework" Version="3.5.1" />
    <PackageReference Include="Qhta.Collections" Version="5.4.0" />
  </ItemGroup>

</Project>
