// Global using directives

global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Globalization;
global using System.IO;
global using System.Linq;

global using DM = DocumentModel;
//global using DMB = DocumentModel.Bibliography;
global using DMCX = DocumentModel.CustomXml;
global using DMD = DocumentModel.Drawings;
//global using DMDA = DocumentModel.Drawings.Animation;
//global using DMDA3D = DocumentModel.Drawings.Animation.Model3D;
global using DMDCD = DocumentModel.Drawings.ChartDrawing;
global using DMDCDs = DocumentModel.Drawings.ChartDrawings;
global using DMDC = DocumentModel.Drawings.Charts;
global using DMDCS = DocumentModel.Drawings.ChartsStyle;
global using DMDD1 = DocumentModel.Drawings.Diagram1;
global using DMDD2 = DocumentModel.Drawings.Diagram2;
global using DMDD = DocumentModel.Drawings.Diagrams;
//global using DMDL = DocumentModel.Drawings.Legacy;
//global using DMDLCv = DocumentModel.Drawings.LockedCanvas;
//global using DMD3D = DocumentModel.Drawings.Model3D;
global using DMDO = DocumentModel.Drawings.Office;
global using DMDOOE = DocumentModel.Drawings.Office.OEmbed;
global using DMDOSL = DocumentModel.Drawings.Office.ScriptLink;
//global using DMDPc = DocumentModel.Drawings.Pictures;
//global using DMDSl = DocumentModel.Drawings.Slicer;
//global using DMDS = DocumentModel.Drawings.Spreadsheet;
global using DMDSVG = DocumentModel.Drawings.SVG;
global using DMDW = DocumentModel.Drawings.Wordprocessing;
//global using DME = DocumentModel.EMMA;
//global using DMF = DocumentModel.Framework;
global using DMM = DocumentModel.Math;
global using DMPack = DocumentModel.Packaging;
//global using DMPt = DocumentModel.Painting;
//global using DMP = DocumentModel.Presentation;
//global using DMPV = DocumentModel.Presentation.Vml;
global using DMP = DocumentModel;
//global using DMP = DocumentModel;
//global using DMS = DocumentModel.Spreadsheet;
//global using DMSV = DocumentModel.Spreadsheet.Vml;
global using DMUI = DocumentModel.UI;
//global using DMVl = DocumentModel.Validation;
global using DMVT = DocumentModel.VariantTypes;
global using DMV = DocumentModel.Vml;
global using DMWE = DocumentModel.WebExtensions;
global using DMWEUI = DocumentModel.WebExtensions.UI;
global using DMW = DocumentModel.Wordprocessing;
//global using DMWDC = DocumentModel.Wordprocessing.DrawingCanvas;
global using DMWD = DocumentModel.Wordprocessing.Drawings;
//global using DMWDS = DocumentModel.Wordprocessing.DrawingShape;
global using DMWOE = DocumentModel.Wordprocessing.OEmbed;
global using DMWV = DocumentModel.Wordprocessing.Vml;

global using DMX = DocumentModel.OpenXml;
//global using DMXB = DocumentModel.OpenXml.Bibliography;
global using DMXCX = DocumentModel.OpenXml.CustomXml;
global using DMXD = DocumentModel.OpenXml.Drawings;
//global using DMXDA = DocumentModel.OpenXml.Drawings.Animation;
//global using DMXDA3D = DocumentModel.OpenXml.Drawings.Animation.Model3D;
global using DMXDCD = DocumentModel.OpenXml.Drawings.ChartDrawing;
global using DMXDCDs = DocumentModel.OpenXml.Drawings.ChartDrawings;
global using DMXDC = DocumentModel.OpenXml.Drawings.Charts;
global using DMXDCS = DocumentModel.OpenXml.Drawings.ChartsStyle;
global using DMXDD1 = DocumentModel.OpenXml.Drawings.Diagram1;
global using DMXDD2 = DocumentModel.OpenXml.Drawings.Diagram2;
global using DMXDD = DocumentModel.OpenXml.Drawings.Diagrams;
//global using DMXDLegacy = DocumentModel.OpenXml.Drawings.Legacy;
//global using DMXDLockCanv = DocumentModel.OpenXml.Drawings.LockedCanvas;
//global using DMXD3D = DocumentModel.OpenXml.Drawings.Model3D;
global using DMXDO = DocumentModel.OpenXml.Drawings.Office;
global using DMXDOOEmb = DocumentModel.OpenXml.Drawings.Office.OEmbed;
global using DMXDOScptLnk = DocumentModel.OpenXml.Drawings.Office.ScriptLink;
//global using DMXDPict = DocumentModel.OpenXml.Drawings.Pictures;
//global using DMXDSlicer = DocumentModel.OpenXml.Drawings.Slicer;
//global using DMXDS = DocumentModel.OpenXml.Drawings.Spreadsheet;
global using DMXDSVG = DocumentModel.OpenXml.Drawings.SVG;
global using DMXDW = DocumentModel.OpenXml.Drawings.Wordprocessing;
//global using DMXEMMA = DocumentModel.OpenXml.EMMA;
//global using DMXFwork = DocumentModel.OpenXml.Framework;
global using DMXM = DocumentModel.OpenXml.Math;
global using DMXPack = DocumentModel.OpenXml.Packaging;
//global using DMXPainting = DocumentModel.OpenXml.Painting;
//global using DMXP = DocumentModel.OpenXml.Presentation;
//global using DMXPVml = DocumentModel.OpenXml.Presentation.Vml;
global using DMXP = DocumentModel.OpenXml.Properties;
//global using DMXS = DocumentModel.OpenXml.Spreadsheet;
//global using DMXSVml = DocumentModel.OpenXml.Spreadsheet.Vml;
global using DMXUI = DocumentModel.OpenXml.UI;
//global using DMXVl = DocumentModel.OpenXml.Validation;
//global using DMXVT = DocumentModel.OpenXml.VariantTypes;
global using DMXV = DocumentModel.OpenXml.Vml;
global using DMXWE = DocumentModel.OpenXml.WebExtensions;
global using DMXWEUI = DocumentModel.OpenXml.WebExtensions.UI;
global using DMXW = DocumentModel.OpenXml.Wordprocessing;
//global using DMXWDC = DocumentModel.OpenXml.Wordprocessing.DrawingCanvas;
global using DMXWD = DocumentModel.OpenXml.Wordprocessing.Drawings;
//global using DMXWDS = DocumentModel.OpenXml.Wordprocessing.DrawingShape;
global using DMXWOE = DocumentModel.OpenXml.Wordprocessing.OEmbed;
global using DMXWV = DocumentModel.OpenXml.Wordprocessing.Vml;
