namespace DocumentModel.Wordprocessing;

#pragma warning disable CS1591

public partial class Document
{
  public bool ShouldSerializeAttachedTemplate() => AttachedTemplate is not null && ShouldSerialize(AttachedTemplate);
  public bool ShouldSerializeAutoFormatOverride() => AutoFormatOverride == true;
  public bool ShouldSerializeAutoHyphenation() => AutoHyphenation == true;
  public bool ShouldSerializeBackground() => Background is not null && ShouldSerialize(Background);
  public bool ShouldSerializeChartDataPointTrack() => ChartDataPointTrack == true;
  public bool ShouldSerializeClickAndTypeParagraphStyle() => ClickAndTypeParagraphStyle is not null;
  public bool ShouldSerializeConsecutiveHyphensLimit() => ConsecutiveHyphensLimit is not null;
  public bool ShouldSerializeDefaultTabStop() => DefaultTabStop is not null;
  public bool ShouldSerializeDefaultTargetFrame() => !String.IsNullOrEmpty(DefaultTargetFrame);
  public bool ShouldSerializeDisableFeatures() => DisableFeatures == true;
  public bool ShouldSerializeDisableFeaturesIntroducedAfter() => DisableFeaturesIntroducedAfter is not null && ShouldSerialize(DisableFeaturesIntroducedAfter);
  public bool ShouldSerializeDoNotEmbedSystemFonts() => DoNotEmbedSystemFonts == true;
  public bool ShouldSerializeEmbedLinguisticData() => EmbedLinguisticData == true;
  public bool ShouldSerializeEmbedSmartTags() => EmbedSmartTags == true;
  public bool ShouldSerializeEmbedTrueTypeFonts() => EmbedTrueTypeFonts == true;
  public bool ShouldSerializeEncryptionProvider() => !String.IsNullOrEmpty(EncryptionProvider);
  public bool ShouldSerializeEnforceStyle() => EnforceStyle == true;
  public bool ShouldSerializeFarEastLineBreakLanguage() => FarEastLineBreakLanguage is not null && ShouldSerialize(FarEastLineBreakLanguage);
  public bool ShouldSerializeFarEastLineBreakLevel() => FarEastLineBreakLevel is not null && ShouldSerialize(FarEastLineBreakLevel);
  public bool ShouldSerializeFinal() => Final == true;
  public bool ShouldSerializeFormattingShowClear() => FormattingShowClear == true;
  public bool ShouldSerializeFormattingShowFilter() => FormattingShowFilter is not null && ShouldSerialize(FormattingShowFilter);
  public bool ShouldSerializeFormattingShowFont() => FormattingShowFont == true;
  public bool ShouldSerializeFormattingShowNextLevel() => FormattingShowNextLevel == true;
  public bool ShouldSerializeFormattingShowNumbering() => FormattingShowNumbering == true;
  public bool ShouldSerializeFormattingShowParagraph() => FormattingShowParagraph == true;
  public bool ShouldSerializeFormattingShowUserStyleName() => FormattingShowUserStyleName == true;
  public bool ShouldSerializeGrammarChecked() => GrammarChecked == true;
  public bool ShouldSerializeGridDistanceHorizontal() => GridDistanceHorizontal is not null;
  public bool ShouldSerializeGridDistanceVertical() => GridDistanceVertical is not null;
  public bool ShouldSerializeGridOriginFromMargin() => GridOriginFromMargin == true;
  public bool ShouldSerializeGridOriginHorizontal() => GridOriginHorizontal is not null;
  public bool ShouldSerializeGridOriginVertical() => GridOriginVertical is not null;
  public bool ShouldSerializeGridSpaceBetweenHorizontalLines() => GridSpaceBetweenHorizontalLines is not null;
  public bool ShouldSerializeGridSpaceBetweenVerticalLines() => GridSpaceBetweenVerticalLines is not null;
  public bool ShouldSerializeHasMailer() => HasMailer == true;
  public bool ShouldSerializeHasRoutingSlip() => HasRoutingSlip == true;
  public bool ShouldSerializeHyphenateCaps() => HyphenateCaps == true;
  public bool ShouldSerializeHyphenationZone() => HyphenationZone is not null;
  public bool ShouldSerializeJustificationMode() => JustificationMode is not null && ShouldSerialize(JustificationMode);
  public bool ShouldSerializeKerningByAlgorithm() => KerningByAlgorithm == true;
  public bool ShouldSerializeKind() => Kind is not null && ShouldSerialize(Kind);
  public bool ShouldSerializeLanguageDetected() => LanguageDetected == true;
  public bool ShouldSerializeLockQuickStyleSet() => LockQuickStyleSet == true;
  public bool ShouldSerializeLockTheme() => LockTheme == true;
  public bool ShouldSerializeNoLineBreakAfter() => !String.IsNullOrEmpty(NoLineBreakAfter);
  public bool ShouldSerializeNoLineBreakBefore() => !String.IsNullOrEmpty(NoLineBreakBefore);
  public bool ShouldSerializeOMathBreakBin() => OMathBreakBin is not null && ShouldSerialize(OMathBreakBin);
  public bool ShouldSerializeOMathBreakSub() => OMathBreakSub is not null && ShouldSerialize(OMathBreakSub);
  public bool ShouldSerializeOMathFontName() => !String.IsNullOrEmpty(OMathFontName);
  public bool ShouldSerializeOMathIntSubSupLim() => OMathIntSubSupLim == true;
  public bool ShouldSerializeOMathJc() => OMathJc is not null && ShouldSerialize(OMathJc);
  public bool ShouldSerializeOMathLeftMargin() => OMathLeftMargin is not null;
  public bool ShouldSerializeOMathNarySupSubLim() => OMathNarySupSubLim == true;
  public bool ShouldSerializeOMathRightMargin() => OMathRightMargin is not null;
  public bool ShouldSerializeOMathSmallFrac() => OMathSmallFrac == true;
  public bool ShouldSerializeOMathWrap() => OMathWrap is not null;
  public bool ShouldSerializeOptimizeForWord97() => OptimizeForWord97 == true;
  public bool ShouldSerializePageSetup() => PageSetup is not null && ShouldSerialize(PageSetup);
  public bool ShouldSerializePassword() => !String.IsNullOrEmpty(Password);
  public bool ShouldSerializePrintFormsData() => PrintFormsData == true;
  public bool ShouldSerializePrintFractionalWidths() => PrintFractionalWidths == true;
  public bool ShouldSerializePrintPostScriptOverText() => PrintPostScriptOverText == true;
  public bool ShouldSerializePrintRevisions() => PrintRevisions == true;
  public bool ShouldSerializeReadingLayoutSizeX() => ReadingLayoutSizeX is not null;
  public bool ShouldSerializeReadingLayoutSizeY() => ReadingLayoutSizeY is not null;
  public bool ShouldSerializeReadingModeLayoutFrozen() => ReadingModeLayoutFrozen == true;
  public bool ShouldSerializeReadOnlyRecommended() => ReadOnlyRecommended == true;
  public bool ShouldSerializeRemoveDateAndTime() => RemoveDateAndTime == true;
  public bool ShouldSerializeRemovePersonalInformation() => RemovePersonalInformation == true;
  public bool ShouldSerializeSaved() => Saved == true;
  public bool ShouldSerializeSaveEncoding() => SaveEncoding is not null && ShouldSerialize(SaveEncoding);
  public bool ShouldSerializeSaveFormsData() => SaveFormsData == true;
  public bool ShouldSerializeSaveSubsetFonts() => SaveSubsetFonts == true;
  public bool ShouldSerializeShowGrammaticalErrors() => ShowGrammaticalErrors == true;
  public bool ShouldSerializeShowRevisions() => ShowRevisions == true;
  public bool ShouldSerializeShowSpellingErrors() => ShowSpellingErrors == true;
  public bool ShouldSerializeShowSummary() => ShowSummary == true;
  public bool ShouldSerializeSmartTagsAsXMLProps() => SmartTagsAsXMLProps == true;
  public bool ShouldSerializeSnapToGrid() => SnapToGrid == true;
  public bool ShouldSerializeSnapToShapes() => SnapToShapes == true;
  public bool ShouldSerializeSpellingChecked() => SpellingChecked == true;
  public bool ShouldSerializeStyleSortMethod() => StyleSortMethod is not null && ShouldSerialize(StyleSortMethod);
  public bool ShouldSerializeSummaryLength() => SummaryLength is not null;
  public bool ShouldSerializeSummaryViewMode() => SummaryViewMode is not null && ShouldSerialize(SummaryViewMode);
  public bool ShouldSerializeTextEncoding() => TextEncoding is not null && ShouldSerialize(TextEncoding);
  public bool ShouldSerializeTextLineEnding() => TextLineEnding is not null && ShouldSerialize(TextLineEnding);
  public bool ShouldSerializeTrackFormatting() => TrackFormatting == true;
  public bool ShouldSerializeTrackMoves() => TrackMoves == true;
  public bool ShouldSerializeTrackRevisions() => TrackRevisions == true;
  public bool ShouldSerializeUpdateStylesOnOpen() => UpdateStylesOnOpen == true;
  public bool ShouldSerializeUseMathDefaults() => UseMathDefaults == true;
  public bool ShouldSerializeUserControl() => UserControl == true;
  public bool ShouldSerializeWritePassword() => !String.IsNullOrEmpty(WritePassword);
  public bool ShouldSerializeXMLHideNamespaces() => XMLHideNamespaces == true;
  public bool ShouldSerializeXMLSaveDataOnly() => XMLSaveDataOnly == true;
  public bool ShouldSerializeXMLSaveThroughXSLT() => !String.IsNullOrEmpty(XMLSaveThroughXSLT);
  public bool ShouldSerializeXMLShowAdvancedErrors() => XMLShowAdvancedErrors == true;
  public bool ShouldSerializeXMLUseXSLTWhenSaving() => XMLUseXSLTWhenSaving == true;
}
