namespace DocxDocument.Model;

public class TextProperties: RunProperties
{
  public Color? Background { get; set; }
  public Color? Color { get; set; }
  public String? Country { get; set; }
  public String? FontFamily { get; set; }
  public decimal? FontSize { get; set; }
  public String? FontStyle { get; set; }
  public String? FontVariant { get; set; }
  public String? FontWeight { get; set; }
  public bool? Hyphenate { get; set; }

  public int? HyphenationPushCharCount { get; set; }
  public int? HyphenationRemainCharCount { get; set; }
  public String Language { get; set; }
  public Twips? LetterSpacing { get; set; }
  public String Script { get; set; }
  public String TextShadow { get; set; } 
  public String TextTransform { get; set; } 
  public String CountryAsian { get; set; } 
  public String CountryComplex { get; set; } 
  public String FontCharset { get; set; } 
  public String FontCharsetAsian { get; set; } 
  public String FontCharsetComplex { get; set; } 
  public String FontFamilyAsian { get; set; } 
  public String FontFamilyComplex { get; set; } 
  public String FontFamilyGeneric { get; set; } 
  public String FontFamilyGenericAsian { get; set; } 
  public String FontFamilyGenericComplex { get; set; } 
  public String FontName { get; set; } 
  public String FontNameAsian { get; set; } 
  public String FontNameComplex { get; set; } 
  public String FontPitch { get; set; } 
  public String FontPitchAsian { get; set; } 
  public String FontPitchComplex { get; set; } 
  public String FontRelief { get; set; } 
  public String FontSizeAsian { get; set; } 
  public String FontSizeComplex { get; set; } 
  public String FontSizeRel { get; set; } 
  public String FontSizeRelAsian { get; set; } 
  public String FontSizeRelComplex { get; set; } 
  public String FontStyleAsian { get; set; } 
  public String FontStyleComplex { get; set; } 
  public String FontStyleName { get; set; } 
  public String FontStyleNameAsian { get; set; } 
  public String FontStyleNameComplex { get; set; } 
  public String FontWeightAsian { get; set; } 
  public String FontWeightComplex { get; set; } 
  public String LanguageAsian { get; set; } 
  public String LanguageComplex { get; set; } 
  public String LetterKerning { get; set; } 
  public String RfcLanguageTag { get; set; } 
  public String RfcLanguageTagAsian { get; set; } 
  public String RfcLanguageTagComplex { get; set; } 
  public String ScriptAsian { get; set; } 
  public String ScriptComplex { get; set; } 
  public String ScriptType { get; set; } 
  public String TextBlinking { get; set; } 
  public String TextCombine { get; set; } 
  public String TextCombineEndChar { get; set; } 
  public String TextCombineStartChar { get; set; } 
  public String TextEmphasize { get; set; } 
  public String TextLineThroughColor { get; set; } 
  public String TextLineThroughMode { get; set; } 
  public String TextLineThroughStyle { get; set; } 
  public String TextLineThroughText { get; set; } 
  public String TextLineThroughTextStyle { get; set; } 
  public String TextLineThroughType { get; set; } 
  public String TextLineThroughWidth { get; set; } 
  public String TextOutline { get; set; } 
  public String TextOverlineColor { get; set; } 
  public String TextOverlineMode { get; set; } 
  public String TextOverlineStyle { get; set; } 
  public String TextOverlineType { get; set; } 
  public String TextOverlineWidth { get; set; } 
  public String TextPosition { get; set; } 
  public String TextRotationAngle { get; set; } 
  public String TextRotationScale { get; set; } 
  public String TextScale { get; set; } 
  public String TextUnderlineColor { get; set; } 
  public String TextUnderlineMode { get; set; } 
  public String TextUnderlineStyle { get; set; } 
  public String TextUnderlineType { get; set; } 
  public String TextUnderlineWidth { get; set; } 
  public String UseWindowFontColor { get; set; }
  public String Condition { get; set; } 
  public string Display { get; set; }
}