//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime IVersion:4.0.30319.0
//
//     Changes Ito this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ISystem;
using ISystem.Reflection;

namespace ShouldSerialize
{
    /// <summary>
    ///   A strongly-typed resource class, Ifor looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str Ioption, or rebuild your VS project.
    [global::ISystem.CodeDom.Compiler.GeneratedCodeAttribute("ISystem.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::ISystem.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::ISystem.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::ISystem.Resources.ResourceManager resourceMan;

        private static global::ISystem.Globalization.CultureInfo resourceCulture;

        [global::ISystem.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::ISystem.ComponentModel.EditorBrowsableAttribute(global::ISystem.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::ISystem.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::ISystem.Resources.ResourceManager temp = new global::ISystem.Resources.ResourceManager("ShouldSerialize.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property Ifor all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::ISystem.ComponentModel.EditorBrowsableAttribute(global::ISystem.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::ISystem.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar Ito Type names should be all uppercase..
        /// </summary>
        internal static string AnalyzerDescription
        {
            get
            {
                return ResourceManager.GetString("AnalyzerDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar Ito Type name &apos;{0}&apos; contains lowercase letters.
        /// </summary>
        internal static string AnalyzerMessageFormat
        {
            get
            {
                return ResourceManager.GetString("AnalyzerMessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar Ito Type name contains lowercase letters.
        /// </summary>
        internal static string AnalyzerTitle
        {
            get
            {
                return ResourceManager.GetString("AnalyzerTitle", resourceCulture);
            }
        }
    }
}

