namespace DocumentModel.Interop.Word;

public enum WdBuildingBlockTypes
{
  wdTypeQuickParts = unchecked((int)1),
  wdTypeCoverPage = unchecked((int)2),
  wdTypeEquations = unchecked((int)3),
  wdTypeFooters = unchecked((int)4),
  wdTypeHeaders = unchecked((int)5),
  wdTypePageNumber = unchecked((int)6),
  wdTypeTables = unchecked((int)7),
  wdTypeWatermarks = unchecked((int)8),
  wdTypeAutoText = unchecked((int)9),
  wdTypeTextBox = unchecked((int)10),
  wdTypePageNumberTop = unchecked((int)11),
  wdTypePageNumberBottom = unchecked((int)12),
  wdTypePageNumberPage = unchecked((int)13),
  wdTypeTableOfContents = unchecked((int)14),
  wdTypeCustomQuickParts = unchecked((int)15),
  wdTypeCustomCoverPage = unchecked((int)16),
  wdTypeCustomEquations = unchecked((int)17),
  wdTypeCustomFooters = unchecked((int)18),
  wdTypeCustomHeaders = unchecked((int)19),
  wdTypeCustomPageNumber = unchecked((int)20),
  wdTypeCustomTables = unchecked((int)21),
  wdTypeCustomWatermarks = unchecked((int)22),
  wdTypeCustomAutoText = unchecked((int)23),
  wdTypeCustomTextBox = unchecked((int)24),
  wdTypeCustomPageNumberTop = unchecked((int)25),
  wdTypeCustomPageNumberBottom = unchecked((int)26),
  wdTypeCustomPageNumberPage = unchecked((int)27),
  wdTypeCustomTableOfContents = unchecked((int)28),
  wdTypeCustom1 = unchecked((int)29),
  wdTypeCustom2 = unchecked((int)30),
  wdTypeCustom3 = unchecked((int)31),
  wdTypeCustom4 = unchecked((int)32),
  wdTypeCustom5 = unchecked((int)33),
  wdTypeBibliography = unchecked((int)34),
  wdTypeCustomBibliography = unchecked((int)35)
}
