namespace DocumentModel.Interop.Word;

public enum WdInformation
{
  wdActiveEndAdjustedPageNumber = unchecked((int)1),
  wdActiveEndSectionNumber = unchecked((int)2),
  wdActiveEndPageNumber = unchecked((int)3),
  wdNumberOfPagesInDocument = unchecked((int)4),
  wdHorizontalPositionRelativeToPage = unchecked((int)5),
  wdVerticalPositionRelativeToPage = unchecked((int)6),
  wdHorizontalPositionRelativeToTextBoundary = unchecked((int)7),
  wdVerticalPositionRelativeToTextBoundary = unchecked((int)8),
  wdFirstCharacterColumnNumber = unchecked((int)9),
  wdFirstCharacterLineNumber = unchecked((int)10),
  wdFrameIsSelected = unchecked((int)11),
  wdWithInTable = unchecked((int)12),
  wdStartOfRangeRowNumber = unchecked((int)13),
  wdEndOfRangeRowNumber = unchecked((int)14),
  wdMaximumNumberOfRows = unchecked((int)15),
  wdStartOfRangeColumnNumber = unchecked((int)16),
  wdEndOfRangeColumnNumber = unchecked((int)17),
  wdMaximumNumberOfColumns = unchecked((int)18),
  wdZoomPercentage = unchecked((int)19),
  wdSelectionMode = unchecked((int)20),
  wdCapsLock = unchecked((int)21),
  wdNumLock = unchecked((int)22),
  wdOverType = unchecked((int)23),
  wdRevisionMarking = unchecked((int)24),
  wdInFootnoteEndnotePane = unchecked((int)25),
  wdInCommentPane = unchecked((int)26),
  wdInHeaderFooter = unchecked((int)28),
  wdAtEndOfRowMarker = unchecked((int)31),
  wdReferenceOfType = unchecked((int)32),
  wdHeaderFooterType = unchecked((int)33),
  wdInMasterDocument = unchecked((int)34),
  wdInFootnote = unchecked((int)35),
  wdInEndnote = unchecked((int)36),
  wdInWordMail = unchecked((int)37),
  wdInClipboard = unchecked((int)38),
  wdInCoverPage = unchecked((int)41),
  wdInBibliography = unchecked((int)42),
  wdInCitation = unchecked((int)43),
  wdInFieldCode = unchecked((int)44),
  wdInFieldResult = unchecked((int)45),
  wdInContentControl = unchecked((int)46)
}
