namespace DocumentModel.Interop.Word;

public enum WdPaperSize
{
  wdPaper10x14 = unchecked((int)0),
  wdPaper11x17 = unchecked((int)1),
  wdPaperLetter = unchecked((int)2),
  wdPaperLetterSmall = unchecked((int)3),
  wdPaperLegal = unchecked((int)4),
  wdPaperExecutive = unchecked((int)5),
  wdPaperA3 = unchecked((int)6),
  wdPaperA4 = unchecked((int)7),
  wdPaperA4Small = unchecked((int)8),
  wdPaperA5 = unchecked((int)9),
  wdPaperB4 = unchecked((int)10),
  wdPaperB5 = unchecked((int)11),
  wdPaperCSheet = unchecked((int)12),
  wdPaperDSheet = unchecked((int)13),
  wdPaperESheet = unchecked((int)14),
  wdPaperFanfoldLegalGerman = unchecked((int)15),
  wdPaperFanfoldStdGerman = unchecked((int)16),
  wdPaperFanfoldUS = unchecked((int)17),
  wdPaperFolio = unchecked((int)18),
  wdPaperLedger = unchecked((int)19),
  wdPaperNote = unchecked((int)20),
  wdPaperQuarto = unchecked((int)21),
  wdPaperStatement = unchecked((int)22),
  wdPaperTabloid = unchecked((int)23),
  wdPaperEnvelope9 = unchecked((int)24),
  wdPaperEnvelope10 = unchecked((int)25),
  wdPaperEnvelope11 = unchecked((int)26),
  wdPaperEnvelope12 = unchecked((int)27),
  wdPaperEnvelope14 = unchecked((int)28),
  wdPaperEnvelopeB4 = unchecked((int)29),
  wdPaperEnvelopeB5 = unchecked((int)30),
  wdPaperEnvelopeB6 = unchecked((int)31),
  wdPaperEnvelopeC3 = unchecked((int)32),
  wdPaperEnvelopeC4 = unchecked((int)33),
  wdPaperEnvelopeC5 = unchecked((int)34),
  wdPaperEnvelopeC6 = unchecked((int)35),
  wdPaperEnvelopeC65 = unchecked((int)36),
  wdPaperEnvelopeDL = unchecked((int)37),
  wdPaperEnvelopeItaly = unchecked((int)38),
  wdPaperEnvelopeMonarch = unchecked((int)39),
  wdPaperEnvelopePersonal = unchecked((int)40),
  wdPaperCustom = unchecked((int)41)
}
