namespace DocumentModel.Interop.Word;

public enum WdTableFormat
{
  wdTableFormatNone = unchecked((int)0),
  wdTableFormatSimple1 = unchecked((int)1),
  wdTableFormatSimple2 = unchecked((int)2),
  wdTableFormatSimple3 = unchecked((int)3),
  wdTableFormatClassic1 = unchecked((int)4),
  wdTableFormatClassic2 = unchecked((int)5),
  wdTableFormatClassic3 = unchecked((int)6),
  wdTableFormatClassic4 = unchecked((int)7),
  wdTableFormatColorful1 = unchecked((int)8),
  wdTableFormatColorful2 = unchecked((int)9),
  wdTableFormatColorful3 = unchecked((int)10),
  wdTableFormatColumns1 = unchecked((int)11),
  wdTableFormatColumns2 = unchecked((int)12),
  wdTableFormatColumns3 = unchecked((int)13),
  wdTableFormatColumns4 = unchecked((int)14),
  wdTableFormatColumns5 = unchecked((int)15),
  wdTableFormatGrid1 = unchecked((int)16),
  wdTableFormatGrid2 = unchecked((int)17),
  wdTableFormatGrid3 = unchecked((int)18),
  wdTableFormatGrid4 = unchecked((int)19),
  wdTableFormatGrid5 = unchecked((int)20),
  wdTableFormatGrid6 = unchecked((int)21),
  wdTableFormatGrid7 = unchecked((int)22),
  wdTableFormatGrid8 = unchecked((int)23),
  wdTableFormatList1 = unchecked((int)24),
  wdTableFormatList2 = unchecked((int)25),
  wdTableFormatList3 = unchecked((int)26),
  wdTableFormatList4 = unchecked((int)27),
  wdTableFormatList5 = unchecked((int)28),
  wdTableFormatList6 = unchecked((int)29),
  wdTableFormatList7 = unchecked((int)30),
  wdTableFormatList8 = unchecked((int)31),
  wdTableFormat3DEffects1 = unchecked((int)32),
  wdTableFormat3DEffects2 = unchecked((int)33),
  wdTableFormat3DEffects3 = unchecked((int)34),
  wdTableFormatContemporary = unchecked((int)35),
  wdTableFormatElegant = unchecked((int)36),
  wdTableFormatProfessional = unchecked((int)37),
  wdTableFormatSubtle1 = unchecked((int)38),
  wdTableFormatSubtle2 = unchecked((int)39),
  wdTableFormatWeb1 = unchecked((int)40),
  wdTableFormatWeb2 = unchecked((int)41),
  wdTableFormatWeb3 = unchecked((int)42)
}
