namespace DocumentModel.Drawings.Charts;
#pragma warning disable CS1591
public partial class StrDataExtension
{
  public bool ShouldSerializeAutoGeneratedCategories() => AutoGeneratedCategories is not null;
}
