namespace DocumentModel.Drawings.Charts;
/// <summary>
///   Represents an extension for string data in a chart.
///   This extension allows specifying whether categories are auto-generated.
/// </summary>
[OpenXmlType(typeof(DXDC.StrDataExtension))]
[DataContract]
[XmlRoot("StrDataExtension", Namespace = "DocumentModel.Drawings.Charts")]
public partial class StrDataExtension : Extension<DXDC.StrDataExtension>
{
 /// <summary>
 ///   Indicates whether the string categories are auto-generated.
 /// </summary>
 [OpenXmlElement(typeof(DXO13DC.AutoGeneneratedCategories))]
 public bool? AutoGeneratedCategories { get => _AutoGeneratedCategories; set => UpdateField(ref _AutoGeneratedCategories, value, nameof(AutoGeneratedCategories)); }
 private bool? _AutoGeneratedCategories;
}