<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>


  <ItemGroup>
    <Compile Remove="**\*.Methods.cs" />
  </ItemGroup>


  <ItemGroup>
    <Compile Remove="BaseInterfaces\InteropList.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include=".github\copilot-instructions.md" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DocumentModel.BaseTypes\DocumentModel.BaseTypes.csproj" />
    <ProjectReference Include="..\DocumentModel.EnumTypes\DocumentModel.EnumTypes.csproj" />
    <ProjectReference Include="..\DocumentModel.Interop.Enums\DocumentModel.Interop.Enums.csproj" />
  </ItemGroup>

</Project>
