<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>


  <ItemGroup>
    <Compile Remove="**\*.Methods.cs" />
  </ItemGroup>


  <ItemGroup>
    <Compile Remove="BaseInterfaces\InteropList.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include=".github\copilot-instructions.md" />
    <None Include="..\..\..\Scripts\UpdateXmlComments.py" Link="Scripts\UpdateXmlComments.py" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Office.Interop.Word" Version="15.0.4797.1004" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DocumentModel.BaseTypes\DocumentModel.BaseTypes.csproj" />
    <ProjectReference Include="..\DocumentModel.EnumTypes\DocumentModel.EnumTypes.csproj" />
    <ProjectReference Include="..\DocumentModel.Interop.Enums\DocumentModel.Interop.Enums.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="temp\" />
  </ItemGroup>

</Project>
