namespace DocxDocument.Model;

public record StyleEntry
{
  public StyleType Type;
  public string OrigName = null!;
  public string LocalName = null!;
}

public static class PredefinedStyles
{
  public static StyleEntry[] Mapping = new StyleEntry[]
  {
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Normal", LocalName="Normalny" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Heading 1", LocalName="Nagłówek 1" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Heading 2", LocalName="Nagłówek 2" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Heading 3", LocalName="Nagłówek 3" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Heading 4", LocalName="Nagłówek 4" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Heading 5", LocalName="Nagłówek 5" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Heading 6", LocalName="Nagłówek 6" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Heading 7", LocalName="Nagłówek 7" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Heading 8", LocalName="Nagłówek 8" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Heading 9", LocalName="Nagłówek 9" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Index 1", LocalName="Indeks 1" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Index 2", LocalName="Indeks 2" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Index 3", LocalName="Indeks 3" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Index 4", LocalName="Indeks 4" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Index 5", LocalName="Indeks 5" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Index 6", LocalName="Indeks 6" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Index 7", LocalName="Indeks 7" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Index 8", LocalName="Indeks 8" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Index 9", LocalName="Indeks 9" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="TOC 1", LocalName="Spis treści 1" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="TOC 2", LocalName="Spis treści 2" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="TOC 3", LocalName="Spis treści 3" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="TOC 4", LocalName="Spis treści 4" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="TOC 5", LocalName="Spis treści 5" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="TOC 6", LocalName="Spis treści 6" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="TOC 7", LocalName="Spis treści 7" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="TOC 8", LocalName="Spis treści 8" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="TOC 9", LocalName="Spis treści 9" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Normal Indent", LocalName="Wcięcie normalne" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Footnote Text", LocalName="Tekst przypisu dolnego" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Comment Text", LocalName="Tekst komentarza" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Header", LocalName="Nagłówek" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Footer", LocalName="Stopka" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Index Heading", LocalName="Nagłówek indeksu" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Caption", LocalName="Legenda" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Table of Figures", LocalName="Spis ilustracji" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Envelope Address", LocalName="Adres na kopercie" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Envelope Return", LocalName="Adres zwrotny na kopercie" },
    new StyleEntry{ Type=StyleType.Character, OrigName="Footnote Reference", LocalName="Odwołanie przypisu dolnego" },
    new StyleEntry{ Type=StyleType.Character, OrigName="Comment Reference", LocalName="Odwołanie do komentarza" },
    new StyleEntry{ Type=StyleType.Character, OrigName="Line Number", LocalName="Numer wiersza" },
    new StyleEntry{ Type=StyleType.Character, OrigName="Page Number", LocalName="Numer strony" },
    new StyleEntry{ Type=StyleType.Character, OrigName="Endnote Reference", LocalName="Odwołanie przypisu końcowego" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Endnote Text", LocalName="Tekst przypisu końcowego" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Table of Authorities", LocalName="Wykaz źródeł" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Macro Text", LocalName="Tekst makra" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="TOA Heading", LocalName="Nagłówek wykazu źródeł" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="List", LocalName="Lista" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="List Bullet", LocalName="Lista punktowana" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="List Number", LocalName="Lista numerowana" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="List 2", LocalName="Lista 2" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="List 3", LocalName="Lista 3" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="List 4", LocalName="Lista 4" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="List 5", LocalName="Lista 5" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="List Bullet 2", LocalName="Lista punktowana 2" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="List Bullet 3", LocalName="Lista punktowana 3" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="List Bullet 4", LocalName="Lista punktowana 4" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="List Bullet 5", LocalName="Lista punktowana 5" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="List Number 2", LocalName="Lista numerowana 2" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="List Number 3", LocalName="Lista numerowana 3" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="List Number 4", LocalName="Lista numerowana 4" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="List Number 5", LocalName="Lista numerowana 5" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Title", LocalName="Tytuł" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Closing", LocalName="Zwrot pożegnalny" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Signature", LocalName="Podpis" },
    new StyleEntry{ Type=StyleType.Character, OrigName="Default Paragraph Font", LocalName="Domyślna czcionka akapitu" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Body Text", LocalName="Tekst podstawowy" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Body Text Indent", LocalName="Tekst podstawowy wcięty" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="List Continue", LocalName="Lista - kontynuacja" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="List Continue 2", LocalName="Lista - kontynuacja 2" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="List Continue 3", LocalName="Lista - kontynuacja 3" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="List Continue 4", LocalName="Lista - kontynuacja 4" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="List Continue 5", LocalName="Lista - kontynuacja 5" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Message Header", LocalName="Nagłówek wiadomości" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Subtitle", LocalName="Podtytuł" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Salutation", LocalName="Zwrot grzecznościowy" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Date", LocalName="Data" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Body Text First Indent", LocalName="Tekst podstawowy z wcięciem" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Body Text First Indent 2", LocalName="Tekst podstawowy z wcięciem 2" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Note Heading", LocalName="Nagłówek notatki" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Body Text 2", LocalName="Tekst podstawowy 2" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Body Text 3", LocalName="Tekst podstawowy 3" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Body Text Indent 2", LocalName="Tekst podstawowy wcięty 2" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Body Text Indent 3", LocalName="Tekst podstawowy wcięty 3" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Block Text", LocalName="Tekst blokowy" },
    new StyleEntry{ Type=StyleType.Character, OrigName="Hyperlink", LocalName="Hiperłącze" },
    new StyleEntry{ Type=StyleType.Character, OrigName="FollowedHyperlink", LocalName="UżyteHiperłącze" },
    new StyleEntry{ Type=StyleType.Character, OrigName="Strong", LocalName="Pogrubienie" },
    new StyleEntry{ Type=StyleType.Character, OrigName="Emphasis", LocalName="Uwydatnienie" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Document Map", LocalName="Mapa dokumentu" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Plain Text", LocalName="Zwykły tekst" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="E-mail Signature", LocalName="Podpis e-mail" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="z-Top of Form", LocalName="Zagięcie od góry formularza" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="z-Bottom of Form", LocalName="Zagięcie od dołu formularza" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Normal (Web)", LocalName="Normalny (Web)" },
    new StyleEntry{ Type=StyleType.Character, OrigName="HTML Acronym", LocalName="HTML - akronim" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="HTML Address", LocalName="HTML - adres" },
    new StyleEntry{ Type=StyleType.Character, OrigName="HTML Cite", LocalName="HTML - cytat" },
    new StyleEntry{ Type=StyleType.Character, OrigName="HTML Code", LocalName="HTML - kod" },
    new StyleEntry{ Type=StyleType.Character, OrigName="HTML Definition", LocalName="HTML - definicja" },
    new StyleEntry{ Type=StyleType.Character, OrigName="HTML Keyboard", LocalName="HTML - klawiatura" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="HTML Preformatted", LocalName="HTML - wstępnie sformatowany" },
    new StyleEntry{ Type=StyleType.Character, OrigName="HTML Sample", LocalName="HTML - przykład" },
    new StyleEntry{ Type=StyleType.Character, OrigName="HTML Typewriter", LocalName="HTML - stała szerokość" },
    new StyleEntry{ Type=StyleType.Character, OrigName="HTML Variable", LocalName="HTML - zmienna" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Normal Table", LocalName="Standardowy" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Comment Subject", LocalName="Temat komentarza" },
    new StyleEntry{ Type=StyleType.List, OrigName="No List", LocalName="Bez listy" },
    new StyleEntry{ Type=StyleType.List, OrigName="Outline List 3", LocalName="1 / a / i" },
    new StyleEntry{ Type=StyleType.List, OrigName="Outline List 2", LocalName="1 / 1.1 / 1.1.1" },
    new StyleEntry{ Type=StyleType.List, OrigName="Outline List 1", LocalName="Artykuł / sekcja" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table Simple 1", LocalName="Tabela - Prosty 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table Simple 2", LocalName="Tabela - Prosty 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table Simple 3", LocalName="Tabela - Prosty 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table Classic 1", LocalName="Tabela - Klasyczny 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table Classic 2", LocalName="Tabela - Klasyczny 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table Classic 3", LocalName="Tabela - Klasyczny 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table Classic 4", LocalName="Tabela - Klasyczny 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table Colorful 1", LocalName="Tabela - Kolorowy 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table Colorful 2", LocalName="Tabela - Kolorowy 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table Colorful 3", LocalName="Tabela - Kolorowy 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table Columns 1", LocalName="Tabela - Kolumnowy 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table Columns 2", LocalName="Tabela - Kolumnowy 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table Columns 3", LocalName="Tabela - Kolumnowy 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table Columns 4", LocalName="Tabela - Kolumnowy 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table Columns 5", LocalName="Tabela - Kolumnowy 5" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table Grid 1", LocalName="Tabela - Siatka 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table Grid 2", LocalName="Tabela - Siatka 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table Grid 3", LocalName="Tabela - Siatka 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table Grid 4", LocalName="Tabela - Siatka 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table Grid 5", LocalName="Tabela - Siatka 5" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table Grid 6", LocalName="Tabela - Siatka 6" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table Grid 7", LocalName="Tabela - Siatka 7" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table Grid 8", LocalName="Tabela - Siatka 8" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table List 1", LocalName="Tabela - Lista 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table List 2", LocalName="Tabela - Lista 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table List 3", LocalName="Tabela - Lista 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table List 4", LocalName="Tabela - Lista 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table List 5", LocalName="Tabela - Lista 5" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table List 6", LocalName="Tabela - Lista 6" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table List 7", LocalName="Tabela - Lista 7" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table List 8", LocalName="Tabela - Lista 8" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table 3D effects 1", LocalName="Tabela - Efekty 3D 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table 3D effects 2", LocalName="Tabela - Efekty 3D 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table 3D effects 3", LocalName="Tabela - Efekty 3D 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table Contemporary", LocalName="Tabela - Współczesny" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table Elegant", LocalName="Tabela - Elegancki" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table Professional", LocalName="Tabela - Profesjonalny" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table Subtle 1", LocalName="Tabela - Delikatny 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table Subtle 2", LocalName="Tabela - Delikatny 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table Web 1", LocalName="Tabela - Sieć Web 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table Web 2", LocalName="Tabela - Sieć Web 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table Web 3", LocalName="Tabela - Sieć Web 3" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Balloon Text", LocalName="Tekst dymka" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table Grid", LocalName="Tabela - Siatka" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Table Theme", LocalName="Tabela - Motyw" },
    new StyleEntry{ Type=StyleType.Character, OrigName="Placeholder Text", LocalName="Tekst zastępczy" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="No Spacing", LocalName="Bez odstępów" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Light Shading", LocalName="Jasne cieniowanie" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Light List", LocalName="Jasna lista" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Light Grid", LocalName="Jasna siatka" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Shading 1", LocalName="Średnie cieniowanie 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Shading 2", LocalName="Średnie cieniowanie 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium List 1", LocalName="Średnia lista 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium List 2", LocalName="Średnia lista 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Grid 1", LocalName="Średnia siatka 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Grid 2", LocalName="Średnia siatka 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Grid 3", LocalName="Średnia siatka 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Dark List", LocalName="Ciemna lista" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Colorful Shading", LocalName="Kolorowe cieniowanie" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Colorful List", LocalName="Kolorowa lista" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Colorful Grid", LocalName="Kolorowa siatka" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Light Shading Accent 1", LocalName="Jasne cieniowanie — akcent 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Light List Accent 1", LocalName="Jasna lista — akcent 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Light Grid Accent 1", LocalName="Jasna siatka — akcent 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Shading 1 Accent 1", LocalName="Średnie cieniowanie 1 — akcent 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Shading 2 Accent 1", LocalName="Średnie cieniowanie 2 — akcent 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium List 1 Accent 1", LocalName="Średnia lista 1 — akcent 1" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Revision", LocalName="Poprawka" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="List Paragraph", LocalName="Akapit z listą" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Quote", LocalName="Cytat" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Intense Quote", LocalName="Cytat intensywny" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium List 2 Accent 1", LocalName="Średnia lista 2 — akcent 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Grid 1 Accent 1", LocalName="Średnia siatka 1 — akcent 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Grid 2 Accent 1", LocalName="Średnia siatka 2 — akcent 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Grid 3 Accent 1", LocalName="Średnia siatka 3 — akcent 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Dark List Accent 1", LocalName="Ciemna lista 2 — akcent 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Colorful Shading Accent 1", LocalName="Kolorowe cieniowanie — akcent 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Colorful List Accent 1", LocalName="Kolorowa lista — akcent 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Colorful Grid Accent 1", LocalName="Kolorowa siatka — akcent 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Light Shading Accent 2", LocalName="Jasne cieniowanie — akcent 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Light List Accent 2", LocalName="Jasna lista — akcent 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Light Grid Accent 2", LocalName="Jasna siatka — akcent 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Shading 1 Accent 2", LocalName="Średnie cieniowanie 1 — akcent 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Shading 2 Accent 2", LocalName="Średnie cieniowanie 2 — akcent 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium List 1 Accent 2", LocalName="Średnia lista 1 — akcent 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium List 2 Accent 2", LocalName="Średnia lista 2 — akcent 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Grid 1 Accent 2", LocalName="Średnia siatka 1 — akcent 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Grid 2 Accent 2", LocalName="Średnia siatka 2 — akcent 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Grid 3 Accent 2", LocalName="Średnia siatka 3 — akcent 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Dark List Accent 2", LocalName="Ciemna lista — akcent 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Colorful Shading Accent 2", LocalName="Kolorowe cieniowanie — akcent 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Colorful List Accent 2", LocalName="Kolorowa lista — akcent 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Colorful Grid Accent 2", LocalName="Kolorowa siatka — akcent 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Light Shading Accent 3", LocalName="Jasne cieniowanie — akcent 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Light List Accent 3", LocalName="Jasna lista — akcent 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Light Grid Accent 3", LocalName="Jasna siatka — akcent 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Shading 1 Accent 3", LocalName="Średnie cieniowanie 1 — akcent 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Shading 2 Accent 3", LocalName="Średnie cieniowanie 2 — akcent 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium List 1 Accent 3", LocalName="Średnia lista 1 — akcent 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium List 2 Accent 3", LocalName="Średnia lista 2 — akcent 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Grid 1 Accent 3", LocalName="Średnia siatka 1 — akcent 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Grid 2 Accent 3", LocalName="Średnia siatka 2 — akcent 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Grid 3 Accent 3", LocalName="Średnia siatka 3 — akcent 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Dark List Accent 3", LocalName="Ciemna lista — akcent 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Colorful Shading Accent 3", LocalName="Kolorowe cieniowanie — akcent 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Colorful List Accent 3", LocalName="Kolorowa lista — akcent 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Colorful Grid Accent 3", LocalName="Kolorowa siatka — akcent 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Light Shading Accent 4", LocalName="Jasne cieniowanie — akcent 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Light List Accent 4", LocalName="Jasna lista — akcent 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Light Grid Accent 4", LocalName="Jasna siatka — akcent 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Shading 1 Accent 4", LocalName="Średnie cieniowanie 1 — akcent 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Shading 2 Accent 4", LocalName="Średnie cieniowanie 2 — akcent 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium List 1 Accent 4", LocalName="Średnia lista 1 — akcent 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium List 2 Accent 4", LocalName="Średnia lista 2 — akcent 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Grid 1 Accent 4", LocalName="Średnia siatka 1 — akcent 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Grid 2 Accent 4", LocalName="Średnia siatka 2 — akcent 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Grid 3 Accent 4", LocalName="Średnia siatka 3 — akcent 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Dark List Accent 4", LocalName="Ciemna lista — akcent 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Colorful Shading Accent 4", LocalName="Kolorowe cieniowanie — akcent 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Colorful List Accent 4", LocalName="Kolorowa lista — akcent 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Colorful Grid Accent 4", LocalName="Kolorowa siatka — akcent 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Light Shading Accent 5", LocalName="Jasne cieniowanie — akcent 5" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Light List Accent 5", LocalName="Jasna lista — akcent 5" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Light Grid Accent 5", LocalName="Jasna siatka — akcent 5" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Shading 1 Accent 5", LocalName="Średnie cieniowanie 1 — akcent 5" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Shading 2 Accent 5", LocalName="Średnie cieniowanie 2 — akcent 5" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium List 1 Accent 5", LocalName="Średnia lista 1 — akcent 5" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium List 2 Accent 5", LocalName="Średnia lista 2 — akcent 5" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Grid 1 Accent 5", LocalName="Średnia siatka 1 — akcent 5" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Grid 2 Accent 5", LocalName="Średnia siatka 2 — akcent 5" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Grid 3 Accent 5", LocalName="Średnia siatka 3 — akcent 5" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Dark List Accent 5", LocalName="Ciemna lista — akcent 5" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Colorful Shading Accent 5", LocalName="Kolorowe cieniowanie — akcent 5" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Colorful List Accent 5", LocalName="Kolorowa lista — akcent 5" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Colorful Grid Accent 5", LocalName="Kolorowa siatka — akcent 5" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Light Shading Accent 6", LocalName="Jasne cieniowanie — akcent 6" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Light List Accent 6", LocalName="Jasna lista — akcent 6" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Light Grid Accent 6", LocalName="Jasna siatka — akcent 6" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Shading 1 Accent 6", LocalName="Średnie cieniowanie 1 — akcent 6" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Shading 2 Accent 6", LocalName="Średnie cieniowanie 2 — akcent 6" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium List 1 Accent 6", LocalName="Średnia lista 1 — akcent 6" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium List 2 Accent 6", LocalName="Średnia lista 2 — akcent 6" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Grid 1 Accent 6", LocalName="Średnia siatka 1 — akcent 6" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Grid 2 Accent 6", LocalName="Średnia siatka 2 — akcent 6" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Medium Grid 3 Accent 6", LocalName="Średnia siatka 3 — akcent 6" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Dark List Accent 6", LocalName="Ciemna lista — akcent 6" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Colorful Shading Accent 6", LocalName="Kolorowe cieniowanie — akcent 6" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Colorful List Accent 6", LocalName="Kolorowa lista — akcent 6" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Colorful Grid Accent 6", LocalName="Kolorowa siatka — akcent 6" },
    new StyleEntry{ Type=StyleType.Character, OrigName="Subtle Emphasis", LocalName="Wyróżnienie delikatne" },
    new StyleEntry{ Type=StyleType.Character, OrigName="Intense Emphasis", LocalName="Wyróżnienie intensywne" },
    new StyleEntry{ Type=StyleType.Character, OrigName="Subtle Reference", LocalName="Odwołanie delikatne" },
    new StyleEntry{ Type=StyleType.Character, OrigName="Intense Reference", LocalName="Odwołanie intensywne" },
    new StyleEntry{ Type=StyleType.Character, OrigName="Book Title", LocalName="Tytuł książki" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="Bibliography", LocalName="Bibliografia" },
    new StyleEntry{ Type=StyleType.Paragraph, OrigName="TOC Heading", LocalName="Nagłówek spisu treści" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Plain Table 1", LocalName="Zwykła tabela 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Plain Table 2", LocalName="Zwykła tabela 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Plain Table 3", LocalName="Zwykła tabela 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Plain Table 4", LocalName="Zwykła tabela 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Plain Table 5", LocalName="Zwykła tabela 5" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table Light", LocalName="Siatka tabeli — jasna" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 1 Light", LocalName="Tabela siatki 1 — jasna" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 2", LocalName="Tabela siatki 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 3", LocalName="Tabela siatki 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 4", LocalName="Tabela siatki 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 5 Dark", LocalName="Tabela siatki 5 — ciemna" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 6 Colorful", LocalName="Tabela siatki 6 — kolorowa" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 7 Colorful", LocalName="Tabela siatki 7 — kolorowa" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 1 Light Accent 1", LocalName="Tabela siatki 1 — jasna — akcent 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 2 Accent 1", LocalName="Tabela siatki 2 — akcent 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 3 Accent 1", LocalName="Tabela siatki 3 — akcent 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 4 Accent 1", LocalName="Tabela siatki 4 — akcent 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 5 Dark Accent 1", LocalName="Tabela siatki 5 — ciemna — akcent 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 6 Colorful Accent 1", LocalName="Tabela siatki 6 — kolorowa — akcent 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 7 Colorful Accent 1", LocalName="Tabela siatki 7 — kolorowa — akcent 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 1 Light Accent 2", LocalName="Tabela siatki 1 — jasna — akcent 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 2 Accent 2", LocalName="Tabela siatki 2 — akcent 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 3 Accent 2", LocalName="Tabela siatki 3 — akcent 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 4 Accent 2", LocalName="Tabela siatki 4 — akcent 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 5 Dark Accent 2", LocalName="Tabela siatki 5 — ciemna — akcent 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 6 Colorful Accent 2", LocalName="Tabela siatki 6 — kolorowa — akcent 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 7 Colorful Accent 2", LocalName="Tabela siatki 7 — kolorowa — akcent 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 1 Light Accent 3", LocalName="Tabela siatki 1 — jasna — akcent 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 2 Accent 3", LocalName="Tabela siatki 2 — akcent 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 3 Accent 3", LocalName="Tabela siatki 3 — akcent 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 4 Accent 3", LocalName="Tabela siatki 4 — akcent 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 5 Dark Accent 3", LocalName="Tabela siatki 5 — ciemna — akcent 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 6 Colorful Accent 3", LocalName="Tabela siatki 6 — kolorowa — akcent 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 7 Colorful Accent 3", LocalName="Tabela siatki 7 — kolorowa — akcent 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 1 Light Accent 4", LocalName="Tabela siatki 1 — jasna — akcent 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 2 Accent 4", LocalName="Tabela siatki 2 — akcent 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 3 Accent 4", LocalName="Tabela siatki 3 — akcent 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 4 Accent 4", LocalName="Tabela siatki 4 — akcent 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 5 Dark Accent 4", LocalName="Tabela siatki 5 — ciemna — akcent 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 6 Colorful Accent 4", LocalName="Tabela siatki 6 — kolorowa — akcent 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 7 Colorful Accent 4", LocalName="Tabela siatki 7 — kolorowa — akcent 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 1 Light Accent 5", LocalName="Tabela siatki 1 — jasna — akcent 5" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 2 Accent 5", LocalName="Tabela siatki 2 — akcent 5" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 3 Accent 5", LocalName="Tabela siatki 3 — akcent 5" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 4 Accent 5", LocalName="Tabela siatki 4 — akcent 5" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 5 Dark Accent 5", LocalName="Tabela siatki 5 — ciemna — akcent 5" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 6 Colorful Accent 5", LocalName="Tabela siatki 6 — kolorowa — akcent 5" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 7 Colorful Accent 5", LocalName="Tabela siatki 7 — kolorowa — akcent 5" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 1 Light Accent 6", LocalName="Tabela siatki 1 — jasna — akcent 6" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 2 Accent 6", LocalName="Tabela siatki 2 — akcent 6" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 3 Accent 6", LocalName="Tabela siatki 3 — akcent 6" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 4 Accent 6", LocalName="Tabela siatki 4 — akcent 6" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 5 Dark Accent 6", LocalName="Tabela siatki 5 — ciemna — akcent 6" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 6 Colorful Accent 6", LocalName="Tabela siatki 6 — kolorowa — akcent 6" },
    new StyleEntry{ Type=StyleType.Table, OrigName="Grid Table 7 Colorful Accent 6", LocalName="Tabela siatki 7 — kolorowa — akcent 6" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 1 Light", LocalName="Tabela listy 1 — jasna" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 2", LocalName="Tabela listy 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 3", LocalName="Tabela listy 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 4", LocalName="Tabela listy 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 5 Dark", LocalName="Tabela listy 5 — ciemna" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 6 Colorful", LocalName="Tabela listy 6 — kolorowa" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 7 Colorful", LocalName="Tabela listy 7 — kolorowa" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 1 Light Accent 1", LocalName="Tabela listy 1 — jasna — akcent 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 2 Accent 1", LocalName="Tabela listy 2 — akcent 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 3 Accent 1", LocalName="Tabela listy 3 — akcent 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 4 Accent 1", LocalName="Tabela listy 4 — akcent 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 5 Dark Accent 1", LocalName="Tabela listy 5 — ciemna — akcent 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 6 Colorful Accent 1", LocalName="Tabela listy 6 — kolorowa — akcent 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 7 Colorful Accent 1", LocalName="Tabela listy 7 — kolorowa — akcent 1" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 1 Light Accent 2", LocalName="Tabela listy 1 — jasna — akcent 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 2 Accent 2", LocalName="Tabela listy 2 — akcent 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 3 Accent 2", LocalName="Tabela listy 3 — akcent 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 4 Accent 2", LocalName="Tabela listy 4 — akcent 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 5 Dark Accent 2", LocalName="Tabela listy 5 — ciemna — akcent 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 6 Colorful Accent 2", LocalName="Tabela listy 6 — kolorowa — akcent 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 7 Colorful Accent 2", LocalName="Tabela listy 7 — kolorowa — akcent 2" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 1 Light Accent 3", LocalName="Tabela listy 1 — jasna — akcent 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 2 Accent 3", LocalName="Tabela listy 2 — akcent 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 3 Accent 3", LocalName="Tabela listy 3 — akcent 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 4 Accent 3", LocalName="Tabela listy 4 — akcent 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 5 Dark Accent 3", LocalName="Tabela listy 5 — ciemna — akcent 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 6 Colorful Accent 3", LocalName="Tabela listy 6 — kolorowa — akcent 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 7 Colorful Accent 3", LocalName="Tabela listy 7 — kolorowa — akcent 3" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 1 Light Accent 4", LocalName="Tabela listy 1 — jasna — akcent 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 2 Accent 4", LocalName="Tabela listy 2 — akcent 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 3 Accent 4", LocalName="Tabela listy 3 — akcent 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 4 Accent 4", LocalName="Tabela listy 4 — akcent 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 5 Dark Accent 4", LocalName="Tabela listy 5 — ciemna — akcent 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 6 Colorful Accent 4", LocalName="Tabela listy 6 — kolorowa — akcent 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 7 Colorful Accent 4", LocalName="Tabela listy 7 — kolorowa — akcent 4" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 1 Light Accent 5", LocalName="Tabela listy 1 — jasna — akcent 5" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 2 Accent 5", LocalName="Tabela listy 2 — akcent 5" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 3 Accent 5", LocalName="Tabela listy 3 — akcent 5" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 4 Accent 5", LocalName="Tabela listy 4 — akcent 5" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 5 Dark Accent 5", LocalName="Tabela listy 5 — ciemna — akcent 5" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 6 Colorful Accent 5", LocalName="Tabela listy 6 — kolorowa — akcent 5" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 7 Colorful Accent 5", LocalName="Tabela listy 7 — kolorowa — akcent 5" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 1 Light Accent 6", LocalName="Tabela listy 1 — jasna — akcent 6" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 2 Accent 6", LocalName="Tabela listy 2 — akcent 6" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 3 Accent 6", LocalName="Tabela listy 3 — akcent 6" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 4 Accent 6", LocalName="Tabela listy 4 — akcent 6" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 5 Dark Accent 6", LocalName="Tabela listy 5 — ciemna — akcent 6" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 6 Colorful Accent 6", LocalName="Tabela listy 6 — kolorowa — akcent 6" },
    new StyleEntry{ Type=StyleType.Table, OrigName="List Table 7 Colorful Accent 6", LocalName="Tabela listy 7 — kolorowa — akcent 6" },
    new StyleEntry{ Type=StyleType.Character, OrigName="Mention", LocalName="Wzmianka" },
    new StyleEntry{ Type=StyleType.Character, OrigName="Smart Hyperlink", LocalName="Inteligentny hiperlink" },
    new StyleEntry{ Type=StyleType.Character, OrigName="Hashtag", LocalName="Hasztag" },
    new StyleEntry{ Type=StyleType.Character, OrigName="Unresolved Mention", LocalName="Nierozpoznana wzmianka" },
    new StyleEntry{ Type=StyleType.Character, OrigName="Smart Link", LocalName="Inteligentny link" },
  };
}