namespace DocumentModel.Drawings.Charts;

/// <summary>
///   Represents an extension for string data in a chart.
///   This extension allows specifying whether categories are auto-generated.
/// </summary>
public interface StrDataExtension: Extension
{
  /// <summary>
  ///   Indicates whether the string categories are auto-generated.
  /// </summary>
  public bool? AutoGeneratedCategories { get; set; }
}